### ISSUE TITLE
jQuery not defined knockout template

### ISSUE THREAD

**Issue by dragouf** [aspnet/JavaScriptServices#1007]
I created a new knockout project with yoman and when I start it I get in the browser :

`Uncaught ReferenceError: jQuery is not defined.`

I checked webpack.config.vendor.js and I have this line : 

`new webpack.ProvidePlugin({ $: 'jquery', jQuery: 'jquery' }),`

And vendo.js is loaded correctly. I don't understand why $ is defined but not jQuery.

Any idea ?

**Comment by SteveSandersonMS** [comment]
I just tried to repro this by creating a new KO application using `generator-aspnetcore-spa` version 0.9.3, but no such problem occurred.

I'm guessing therefore that this doesn't just happen out of the box for you, but rather you are writing some code of your own that fails with this error. That being the case, this is a webpack config question, so could you check Webpack docs or raise it with the Webpack community? Thanks!

**Comment by dbakuntsev** [comment]
It certainly is a problem with the generator version 0.9.3 - a new, unmodified, Knockout project fails with the unresolved reference error.

The original poster has probably given up on this, that's why there was no further reply.

But the problem exists. Makes you wonder how many people are actually using this generator to begin with, eh?
