### ISSUE TITLE
Not working with .net core 2.0

### ISSUE THREAD

**Issue by sherry-ummen** [aspnet/JavaScriptServices#1021]
Hi,

I am trying yo aspnetcore-spa + react & redux

But I get this error:

C:\Program Files\dotnet\sdk\2.0.0-preview1-005977\NuGet.targets(97,5): error : Unable to resolve 'Microsoft.AspNetCore.SpaServices (>= 1.1.1)' for '.NETCoreApp,Version=v1.1'. [C:\MyDrive\Personal\react\ReactTest1.csproj]

Any solution to this?

**Comment by SteveSandersonMS** [comment]
The code in the `dev` branch in this repo is already based on .NET Core 2.0. The template packages built here are based on this: https://ci.appveyor.com/project/aspnetci/javascriptservices/history. When .NET Core 2.0 Preview 2 ships, we'll be including updated SPA templates with it.

It's probably better for you not to try to use .NET Core 2.0 with the SPA templates before Preview 2 ships because there's no support or docs for that. But it won't be long now until it ships!

**Comment by sherry-ummen** [comment]
ok thank you
