### ISSUE TITLE
Visual Studio breakpoints stop working after webpack middleware rebuild

### ISSUE THREAD

**Issue by thesmallbang** [aspnet/JavaScriptServices#1040]
using template: dotnet net aurelia  with dotnet --version 1.0.4

Reproduce:
Start debugging the project everything works as expected and breakpoints are hit.
Save a change to a typescript file

Result:
No more breakpoints are hit in visual studio (even with browser refresh).

**Comment by SteveSandersonMS** [comment]
I suppose this is a limitation in VS's support for debugging code running in browsers - it doesn't know about changes you've made after the debugging session started. AFAIK that's not something that could be addressed in this repo, so I'll close this. If you want to you could report this to VS, though they are likely to understand the request better if you phrase it in terms of working with Webpack HMR generally rather than anything specific to JavaScriptServices templates.
