### ISSUE TITLE
Can not debug typescript code on server side

### ISSUE THREAD

**Issue by seven1986** [aspnet/JavaScriptServices#1047]
I don't know where went wrong. always broken after I visit localhost:5000

![image](https://user-images.githubusercontent.com/20808494/27329781-7799cfec-55e9-11e7-9582-e891e0c78481.png)

![image](https://user-images.githubusercontent.com/20808494/27329794-86eeeb4e-55e9-11e7-9098-fd0ca9f95421.png)

**Comment by SteveSandersonMS** [comment]
This is a known issue due to a breaking change in a recent version of Node (might be 6.x, not sure). As a temporary workaround you can use an older version of Node.

The underlying issue in JavaScriptServices is fixed already and that fix will be included in the next release which is most likely in the next couple of weeks. Sorry for the inconvenience!
