### ISSUE TITLE
[question] Why HMR does not work for typescript files?

### ISSUE THREAD

**Issue by shahabganji** [aspnet/JavaScriptServices#1063]
I created a project based on what you have said on the page. Every change is detected by HMR and applied to browser pages without the need to refresh the browser. Although changes in typescript files detected, they are not affecting browser pages until we change other files such as  ```.html, .css```, etc. files.

While this feature works properly for angular projects, I was wondering is there any issues for Aurelia projects or something else should be run behind the scene?

**Comment by SteveSandersonMS** [comment]
I'm not sure what's breaking it in your environment, but `.ts` file changes (e.g., on component classes) do take effect automatically as far as I know. It certainly worked fine when I just checked it.

If you're able to track down what's broken it in your project/environment and are able to reproduce it as a bug in the code in this repo, please let us know the repro steps so we can fix it! Thanks.

**Comment by HamedFathi** [comment]
@SteveSandersonMS ,

thanks for your answer but I have problem like @shahabganji not in specific project just in your latest simple template (nothing changed or added)

`dotnet new install microsoft.aspnetcore.spatemplates::*`
`dotnet new aurelia`

[Microsoft.AspNetCore.SpaTemplates 0.9.3
](https://www.nuget.org/packages/Microsoft.AspNetCore.SpaTemplates/)

we discussed about that before because we thought the problem came from aurelia or aurelia webpack plugin

[How to use HMR for typescript ](https://github.com/aurelia/hot-module-reload/issues/15)



May I ask you check your latest template again ?
because both of us tested the problem in three different systems (1 mac / 2 pc) with standard template not more !

Can you confirm again just works for you ?

**Comment by SteveSandersonMS** [comment]
> Can you confirm again just works for you ?

Yes, it really, definitely does! Note that I'm running the latest templates in this repo, *not* the much older `0.9.3` ones. The latest templates will be published as part of the .NET Core 2.0 release.

**Comment by shahabganji** [comment]
Hi dear @SteveSandersonMS and @HamedFathi 
I found the root cause of this problem, when I'm using nodejs version 8.x the typescript files do not get affected for HMR, however when using the latest stable version 6.11.2 everything works properly and fine.
