### ISSUE TITLE
Angular - Policy for Framework version (in package.json)

### ISSUE THREAD

**Issue by fredrik-lundin** [aspnet/JavaScriptServices#1068]
What's the plan when it comes to keeping the `@angular/*` packages up to date in the template? I noticed that they are hard coded to specific versions (4.1.2 as of today).

Some options:

- Could it be considered to use the `package: ^version` syntax, like the Angular CLI team is doing?
- Could it be considered to accept PR's from the community with updated Angular versions when they are released?
- Would it be preferred that the maintainer manage it on his/her own?

**Comment by SteveSandersonMS** [comment]
Thanks for raising this - it's a good thing to clear up.

We can't really afford to have 3rd-party package updates break the templates right out of the box, which with 100% probability they will if the versions aren't locked down completely. For most of the last year we relied on ranges like `"^2.0.0"` and stuff was breaking all the time (and not just due to prerelease packages).

Semver rules are not sufficient to ensure compatibility, because (1) package authors don't take back-compat that seriously, and (2) if they actually did, we'd be on TypeScript major version 7948 and Angular major version 2648 by now, and then in effect the usability would be the same as if you pinned to an exact minor version today.

As of a change today, subsequent versions of the templates are going to include an `npm-shrinkwrap.json` file to ensure that *all* dependencies (including transitive ones) are pinned to known-good versions. At this point, we *could* relax the version specifiers in `package.json` to `^version` if we want, since by default NPM will restore the known-good versions regardless of what has shipped since then. But it doesn't really make a difference to use `^version` rather than `version` in `package.json` when `npm-shrinkwrap.json` is imposing a stricter rule, so I don't really mind either way whether we do that.

> Could it be considered to accept PR's from the community with updated Angular versions when they are released?

If someone wants to submit a PR that updates `package.json` and `npm-shrinkwrap.json` to newer known-good configurations, that will definitely be fine. If they don't, I'll be applying updates on a semi-regular basis.

Closing as this is a discussion rather than a bug or future feature, but please feel free to continue the discussion below!
