### ISSUE TITLE
The data method in the sample data controller should not return an IEnumerable directly.

### ISSUE THREAD

**Issue by bbarry** [aspnet/JavaScriptServices#1076]
Looking at the controller for data for the angular sample (but the issue appears to apply to all of them) I see:

    [HttpGet("[action]")]
    public IEnumerable<WeatherForecast> WeatherForecasts()
    ...

Returning data this way from an action results in a json object representing an array and enables consumers to depend on the array type as a top level artifact. If in the future the result would need to be enhanced (for example to something representing paged data), consumers could be broken by the change from an array to an object.

It would be better instead to promote usage of a simple data structure containing the enumerable on a well known path:

    [HttpGet("[action]")]
    public Result<IEnumerable<WeatherForecast>> WeatherForecasts()
    ...

    public class Result<T>
    {
        T Data { get; set; }
    }

**Comment by SteveSandersonMS** [comment]
Thanks for the suggestion! I appreciate that your alternative data shape would be more extensible and that many developers will want to structure their API responses like that in many scenarios.

For this sample code, though, the focus is on showing client-server interactions rather than trying to cover all aspects of extensibility and future-proofing. For example, we're not trying to reflect all aspects of REST philosophy and its notions of resource naming there either. Unless this becomes a problem for a larger number of users, I think we'd prefer to keep the simplest data structure for now. Hope that's OK!
