### ISSUE TITLE
Angular 2 Duplicating the <HTML> & <HEAD>

### ISSUE THREAD

**Issue by SharePointPro** [aspnet/JavaScriptServices#1080]
After running `dotnet new angular` from the `Microsoft.AspNetCore.SpaTemplates::*` the sample project is duplicating <html> <head> and <body>.

The check this you can load the sample project, then press Control U in the browser.
The Snippit of the html is below (notice the duplicated elements)

```
<html>                        <!-- HEAD 1 -->
    <head>
        <meta charset="utf-8" />
        <meta name="viewport" content="width=device-width, initial-scale=1.0" />
        <title>Home Page - temp</title>
        <base href="/" />
        <link rel="stylesheet" href="/dist/vendor.css?v=2OSKmU2Rna58MvkZa-1vCDjb7C1cgTMqz-guh-WoUGU" />
    </head>
    <body>               <!-- BODY 1 -->
        
<app><html><head><style>@media (max-width: 767px) {    <!-- HTML 2 / HEAD 2 / APP 1 -->
    ...
@media (min-width: 768px) {..
...
}</style></head><body><app _nghost-c0="" ng-version="4.1.2"><div _ngcontent-c0=""  
class="container-fluid">   <!-- BODY 2 / APP 2 -->
    <div _ngcontent-c0="" class="row">
        <div _ngcontent-c0="" class="col-sm-3">
            <nav-menu _ngcontent-c0="" _nghost-c1=""><div _ngcontent-c1="" class="main-nav">
            </ul>
        </div>
    </div>
</div>
<script src="/dist/vendor.js?v=8G5nuphpleAMB8hDVj0v8l9es64guglhqGWIwYdey3M"></script>


        
    <script src="/dist/main-client.js?v=mDzK2Vggpkqz7CNaSstSNAR7vz3wBRBzl8SBziBUh84"></script>

    </body>
</html>

```

**Comment by SteveSandersonMS** [comment]
Yes, this is a limitation of how Angular handles server-side prerendering. You can read more discussion about it here: https://github.com/aspnet/JavaScriptServices/issues/662

If this is a problem for you, two things you can do:

 1. Add logic to your `boot-server.ts` file to capture `state.renderToString()` as a string, and then manually strip off the unwanted parts.
 2. Report this as a bug to Angular. Basically, you would be asking for an alternative to `state.renderToString()` that does not insist on wrapping its output in extra HTML doc elements. You will have to supply a repro case that does *not* involve the JavaScriptServices template, otherwise they will (reasonably) not know whether the issue is occuring on their side or not.
