### ISSUE TITLE
incorporating css-reset / global CSS file into the template

### ISSUE THREAD

**Issue by jakubkrupka** [aspnet/JavaScriptServices#1082]
Question, in particular, about the CSS-Reset file. Is the vendor file proper place to put this?
This question can be made more generic, i.e. when I have a file which I'd like to apply globally to the app, like bootstrap-overrides.

On the side: ideally, I would even incorporate (finally?) an LESS / SASS loader for the vendor file.

https://github.com/aspnet/JavaScriptServices/issues/305 already shows similar case. Maybe we could incorporate this in the template?

**Comment by SteveSandersonMS** [comment]
It's an interesting question. Thanks for raising it!

In general it's important that developers working with these technologies learn what the technologies do and how they can customise them for their own projects. It would be impossible for a template to cover everyone's requirements, and attempting to do so would just make it completely incomprehensible in its complexity. So I think it's more important that people learn how to install and configure a LESS/SASS loader than havng one in by default. And as it happens, we have [docs walking through this exact process](https://github.com/aspnet/JavaScriptServices/tree/dev/src/Microsoft.AspNetCore.SpaServices#example-a-simple-webpack-setup-that-builds-less) :)

> Question, in particular, about the CSS-Reset file. Is the vendor file proper place to put this

You can include it in your vendor bundle if you want - it will work either way. Typically it makes sense to do this if it was provided by a third party (a "vendor") because then the contents are likely to change rarely, rather than every time you ship an update to your application.
