### ISSUE TITLE
Bootstrap not working in template

### ISSUE THREAD

**Issue by DickvdBrink** [aspnet/JavaScriptServices#1117]
After running `yo aspnetcore-spa` I chose angular and executing `dotnet restore && dotnet run` I try to open the url in the browser. Everything is looking good (style and stuff) but the bootstrap menu isn't working, if you make the page small you get the hamburger menu but it doesn't open on a click.
When you add the following code
```
 <script src="https://ajax.googleapis.com/ajax/libs/jquery/1.12.4/jquery.min.js"></script>
<script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/js/bootstrap.min.js" integrity="sha384-Tc5IQib027qvyjSMfHjOMaLkfuWVxZxUPnCJA7l2mCWNIpG9mGCD8wGNIcPD7Txa" crossorigin="anonymous"></script>
``` 
to the html it starts to work again, so i suspect something is wrong with the bundle and the bootstrap javascript isn't executed

**Comment by SteveSandersonMS** [comment]
The version of the templates on Yeoman was missing [this line](https://github.com/aspnet/JavaScriptServices/blob/2df0febfbae9d9d148de9234d27c7ed8222615cd/templates/AngularSpa/ClientApp/boot.browser.ts#L3). If you add it to your `boot-client.ts` file, things should be working as expected.

This is already fixed in the sources in this repo, hence closing as resolved.

**Comment by stibay** [comment]
This is still the issue in angular template from dotnet new
`import 'bootstrap'; ` needs to be added to boot-client-ts
