### ISSUE TITLE
[Angular] Server Side Rendering Issue with angular "^4.2.6"

### ISSUE THREAD

**Issue by pfrendo** [aspnet/JavaScriptServices#1118]
Update to angular 4.2.6 and update server side rendering
```
System.Exception: Call to Node module failed with error: Prerendering failed because of error: TypeError: Object prototype may only be an Object or null: undefined
```

**Comment by SteveSandersonMS** [comment]
I'm not sure what project you're upgrading from, or how exactly you're doing the upgrade, but I just tried it and it worked fine.

Specifically, I started with **the version of the template in this repo** (which is already on Angular 4.2.5), and then ran:

* `npm install --save-exact --save @angular/animations@4.2.6 @angular/common@4.2.6 @angular/compiler@4.2.6 @angular/compiler-cli@4.2.6 @angular/core@4.2.6 @angular/forms@4.2.6 @angular/http@4.2.6 @angular/platform-browser@4.2.6 @angular/platform-browser-dynamic@4.2.6 @angular/platform-server@4.2.6 @angular/router@4.2.6 zone.js@0.8.13`
* `webpack --config webpack.config.vendor.js`
* `webpack`

Then upon restarting the application, it all worked without problems.

I'll close this because it is working with the latest template. However if you track down the issue in your specific case and think it's a fault in some code in this repo, please let us know what you think we have wrong. Hope that's OK!

**Comment by pfrendo** [comment]
@SteveSandersonMS .. When will the new version be released? As the one on npm is still pointing to the old template :)

**Comment by SteveSandersonMS** [comment]
@pfrendo As soon as .NET Core 2.0 is released.
