### ISSUE TITLE
Linter for templates

### ISSUE THREAD

**Issue by AllainPL** [aspnet/JavaScriptServices#1122]
Hi, while being quite new to the JS world(I have mostly strong C# background) i noticed that a lot of projects/templates use linters. For JS it's mostly ESLint but for the TS world there is a TSLint package. I was thinking maybe it would be good to have in the templates tslint added in devDependencies with a sample(recommended) tslint.json file?

**Comment by SteveSandersonMS** [comment]
It's an interesting idea. We would definitely be happy to have instructions in this repo's wiki giving suggested setup steps. However we probably wouldn't include it in the template by default because the templates already contain a large number of concepts and we're trying to keep them reasonable for newcomers to understand. Hope that's OK!
