### ISSUE TITLE
Release Cadence for JavaScriptServices?

### ISSUE THREAD

**Issue by pkellner** [aspnet/JavaScriptServices#1127]
Two Questions:

Is JavaScriptServices meant to be a Microsoft written and supported part of ASP.NET Core Only? 

Is there a release cadence of JavaScriptServices with ASP.NET Core 1., 2.,... If so, is there a roadmap of features (like special React branch features similar to Angular Forms Validation)?

**Comment by SteveSandersonMS** [comment]
> Is JavaScriptServices meant to be a Microsoft written and supported part of ASP.NET Core Only

It is Microsoft-written, and is part of ASP.NET Core.

> Is there a release cadence of JavaScriptServices with ASP.NET Core 1., 2.,...

It's part of ASP.NET Core, so primarily it releases at the same time that ASP.NET Core does. That's when any substantial features will ship. For example, in the upcoming ASP.NET Core 2.0 release, the SPA templates are all dramatically updated (e.g., for the Angular template, we now have AoT compilation on by default).

In the specific case of SPA project templates, we *might* ship updates to those template in between ASP.NET Core releases. We'd do that if they were getting out-of-date (e.g., because of updates to third-party JS frameworks).
