### ISSUE TITLE
Hundreds of errors when creating web app with React or React + Redux template

### ISSUE THREAD

**Issue by cesarbs** [aspnet/JavaScriptServices#1134]
Create a web app using the React or React+Redux template. Build. Results:

![image](https://user-images.githubusercontent.com/924164/28395273-a879093c-6ca7-11e7-8509-b69c56f5c4cb.png)

Despite that, the app runs and appears to work. After the first run, the errors are gone.

**Comment by SteveSandersonMS** [comment]
Do you have some kind of nonstandard TypeScript add-in for Visual Studio? I don't get any errors like that. From your screenshot, it kind of looks like it's trying to do intellisense before it's restored the NPM dependencies, but I can't repro that (VS 2017.3 Preview 5, .NET Core SDK 2.0.0-preview3-006857).

I'd be surprised if this was happening on other machines, since the verification folks are very keen on reporting any issues with unexpected warnings or errors, and they didn't report anything like this.

Can you repro it on any other machine with VS 2017.3 Preview 5? Can you give repro instructions other than "create a project", since that doesn't cause it in my case? Thanks!

**Comment by cesarbs** [comment]
I think that was a one off thing - or it was fixed incidentally lately. I just did another test pass with the latest candidate bits and I'm not seeing that happen anymore.

**Comment by SteveSandersonMS** [comment]
OK thanks - closing then.
