### ISSUE TITLE
aspnet-* package dependencies upgrade advice?

### ISSUE THREAD

**Issue by DanHarman** [aspnet/JavaScriptServices#1135]
Hi,

Is there any guidance as to when we should be bumping versions on these, and what the changes are for each version? Its quite hard to know what they even do without looking at the code.

From what I can see the template hasn't been updated for a while so we have major version bumps waiting in npm, but `package.json` for at least the react-redux generator is locked on the previous iterations .

I'm not sure if feasible, but it would also be helpful if there were tags in git for each release version of the packages so we could track changes which would help anticipate any breaks that might occur.

Thanks,

Dan

**Comment by DanHarman** [comment]
Also worth mentioning that the current dependencies have a peer dependency on webpack 2...
I get the following when upgrading to 3.3.0

```
npm WARN aspnet-webpack-react@2.0.1 requires a peer of webpack@^2.2.0 but none was installed.
npm WARN aspnet-webpack@1.0.29 requires a peer of webpack@^1.13.2 || ^2.1.0-beta but none was installed.
```

**Comment by SteveSandersonMS** [comment]
We're generally following semver, so if there's a major version bump in NPM, that implies there was a breaking change which people with existing apps shouldn't get because it would break them.

Once you've created a project with a particular version of the template, it's not expected that you should need to upgrade any `aspnet-*` NPM packages, since the `aspnet-*` packages exist precisely to support that version of your template. It's only relevant to have newer versions if you create a new project with a newer template. Of course, you'll want to upgrade other third-party NPM packages, but that's separate.

If you are keen to change your project to match a newer template and its package dependencies, you'd need to diff the old and new template outputs to establish what changes to make. I know that would be supremely inconvenient but unfortunately we don't have capacity to document every change in a way that would adequately describe its effects and what other combination of changes it depends on. The general idea with the templates is that it's just a starting point, not some kind of framework, so once you have your working app you continune with it and just update whatever third-party dependencies you want to.

> Also worth mentioning that the current dependencies have a peer dependency on webpack 2

See #1126
