### ISSUE TITLE
Include Jest in React and React-Redux template

### ISSUE THREAD

**Issue by chunliu** [aspnet/JavaScriptServices#1138]
In Angular template, Karma was configured for testing. Suggest to have a test framework like Jest loaded for react templates as well. 

Also the Karma config in Angular template used Chrome as the browser which didn't work well with build servers like VSTS. Suggest to change it to other headless browsers like for example PhantomJS.

**Comment by SteveSandersonMS** [comment]
Thanks for the suggestion! We will consider this.

TBH we might be more likely to put in Karma to the React templates, since it provides browser automation (whereas Jest is just standalone unit testing).

Closing as there's no immediate plan to do this, but we might well do it in the future if people keep requesting. Of course, you can add Jest/Karma/whatever to your own project after creating it.
