### ISSUE TITLE
Improve developer workflow

### ISSUE THREAD

**Issue by antmdvs** [aspnet/JavaScriptServices#114]
Is it still necessary to manually run webpack (ReactGrid)? Can this be a post-build step or something of the sort?

**Comment by SteveSandersonMS** [comment]
In development mode (i.e., with the environment variable `ASPNETCORE_Environment` set to `Development`), you don't have to run `webpack` manually.

The ReactGrid sample, along with the other React templates and samples, all use `UseWebpackDevMiddleware` in their `Startup.cs`, which means that Webpack artifacts are built and refreshed automatically on demand.

For production deployments, you *do* still need to run `webpack` because typically in production you don't want to have development-time middleware running in the background - you just want to serve prebuilt static assets as fast as possible.

> Can this be a post-build step or something of the sort?

That would be great. If you have a suggestion on how best to enable that, please let me know. Last time I checked, the `dotnet` CLI's scripts feature wasn't doing anything, but I'm sure that will be sorted out soon.

**Comment by antmdvs** [comment]
Hi Steve, thanks for your prompt reply and helpful info. Tony
