### ISSUE TITLE
Namespace in HomeController.cs does not match the default name I chose on Yeoman command line

### ISSUE THREAD

**Issue by Seefer** [aspnet/JavaScriptServices#1144]
I created a folder called **vega**, entered that folder and ran `yo aspnetcore-spa`.

For the project questions I entered the following:

```
? Framework Angular
? Do you want to include unit tests? No
? Your project name vega
```
For the last question, I simply pressed enter as it seemed to detect the project folder name as vega.

Taking a look at the files created I noticed that in HomeController.cs, the namespace in there seems incorrect.

```
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;

using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;

namespace WebApplicationBasic.Controllers
{
    public class HomeController : Controller
    {
        public IActionResult Index()
        {
            return View();
        }

        public IActionResult Error()
        {
            return View();
        }
    }
}
{
    public class HomeController : Controller
    {
        public IActionResult Index()
        {
            return View();
        }

        public IActionResult Error()
        {
            return View();
        }
    }
}
```
Why is the namespace `WebApplicationBasic.Controllers`. Should it not reflect my project name vega?

**Comment by SteveSandersonMS** [comment]
Sorry for the inconvenience with that. If should reflect your project name, so for now you'll need to change it manually.

Note that this works correctly in the latest `dotnet new` templates.

Very soon we'll be deprecating and removing the Yeoman templates, simply because there's no advantage to using them as compared with the `dotnet new` ones. The `dotnet new` templates produce exactly the same SPA projects (without bugs like this one you've reported) and are just easier to work with. I'll close this as not-going-to-fix since we're not doing any further work on the Yeoman templates right before removing them.
