### ISSUE TITLE
Webpack HMR not able to run on a domain other than localhost

### ISSUE THREAD

**Issue by drosskopf** [aspnet/JavaScriptServices#1158]
For our project, we are wanting to run under a specific domain/port like app-dev.lds.org:8201.  However we find when we do this that the webpack hot module replacement doesn't work.  Any ideas how to get this to work.  I tried looking through the documentation, and the setup for this isn't well known.

**Comment by SteveSandersonMS** [comment]
It's perfectly OK to run on a different host/port, as long as `localhost` *also* resolves to your dev machine (e.g., the loopback address, which is usually 127.0.0.1). Is it possible that `localhost` isn't resolving on your machine? That would be an unusual and potentially problematic network configuration.

Another possibility is that you might be using a really old version of the templates which didn't proxy the HMR endpoint completely like the current version does.

Since AFAICT it is working OK on the current version I'll close this, but if you can repro an issue with this running the .NET Core 2.0 version of the template and on a machine where `localhost` resolves to that same dev machine, please let us know!
