### ISSUE TITLE
Missing main-server.js after dotnet publish

### ISSUE THREAD

**Issue by bpicolo** [aspnet/JavaScriptServices#1159]
Seems that ClientApp/dist isn't getting copied with publish. 

Seems this is required for full production builds (but is not currently in the config)?
```
    <ItemGroup>
      <DistFiles Include="ClientApp\dist\**" />
      <ResolvedFileToPublish Include="@(DistFiles-&gt;'%(FullPath)')" Exclude="@(ResolvedFileToPublish)">
        <RelativePath>%(DistFiles.Identity)</RelativePath>
        <CopyToPublishDirectory>PreserveNewest</CopyToPublishDirectory>
      </ResolvedFileToPublish>
    </ItemGroup>
```

**Comment by stephtr** [comment]
At the moment all templates which utilize server side rendering (Angular and ReactRedux) have ```<DistFiles Include="wwwroot\dist\**; ClientApp\dist\**" />``` already included in their project file.
Which template and version are you talking about?

**Comment by bpicolo** [comment]
@stephtr  think it might be the baseline react spa?
https://github.com/aspnet/JavaScriptServices/blob/d2eaa36372a4c78f5598783063260d315f98dd42/templates/ReactSpa/ReactSpa.csproj

**Comment by stephtr** [comment]
The react spa template doesn't use server side rendering, therefore no server bundle gets generated. As far as I know the react redux template copies the server bundle since they [started using csproj](https://github.com/aspnet/JavaScriptServices/blob/a76b6e25d44d75f0beaa0ab42fbde673dd1b855b/templates/ReactReduxSpa/ReactReduxSpa.csproj).

**Comment by bpicolo** [comment]
@stephtr Huh. It's possible I did some weird copy pasting between dirs of different setups. :) I'll close this out. Thanks for taking a look!
