### ISSUE TITLE
[at-loader] Checking finished with 5 errors

### ISSUE THREAD

**Issue by johndhunter** [aspnet/JavaScriptServices#1167]
Impact: fails to work

Repro steps attached

Followed the steps to the letter but have almost immediate problem - fails in VS2017 as well as from admin command line.

Site loads in browser but quickly fails.

The question is:  Is this because of a version issue with not having 2.0 preview (1.1 only) or something else?
Just learning react and redux but wondering whether I should wait for 2.0.
thanks in advance.

[cmd_dump.txt](https://github.com/aspnet/JavaScriptServices/files/1197224/cmd_dump.txt)

**Comment by SteveSandersonMS** [comment]
There are several problems with the 0.9.2 version of the React/Redux templates, because of breaking changes in third-party libraries since they were released. If you search among older issues in this repo, you'll find descriptions of how to update the `package.json` file to get compatible versions of packages.

All these issues are fixed in the latest version of the templates that will ship soon in .NET Core 2.0 SDK. Plus the newer templates use `npm-shrinkwrap.json` to ensure that third-party changes don't break them out of the box (because they are fixed on known-good versions of dependencies).

**Comment by johndhunter** [comment]
Thanks, will do
