### ISSUE TITLE
incorrect webpack config of 'publicPath':

### ISSUE THREAD

**Issue by kennywangjin** [aspnet/JavaScriptServices#1171]
Current templates set webpack configuration  'publicPath' to 'dist/', which will cause "The path in 'value' must start with '/'" error when start requesting.
when changing to '/dist/', it works.

**Comment by SteveSandersonMS** [comment]
The requirement to start with a forward slash was removed in the .NET Core 2.0 version of the packages. The templates don't use a leading forward slash because doing so will break the app if you deploy it to a virtual directory. If you're deploying to a root URL then it doesn't matter - you'll be fine either way.
