### ISSUE TITLE
What is the purpose of domain-task?

### ISSUE THREAD

**Issue by snoobvn** [aspnet/JavaScriptServices#1187]
In React-Redux-Spa template:
```
import { fetch, addTask } from 'domain-task';
...
            let fetchTask = fetch(`/api/SampleData/WeatherForecasts?startDateIndex=${ startDateIndex }`)
                .then(response => response.json() as Promise<WeatherForecast[]>)
                .then(data => {
                    dispatch({ type: 'RECEIVE_WEATHER_FORECASTS', startDateIndex: startDateIndex, forecasts: data });
                });

            addTask(fetchTask); // Ensure server-side prerendering waits for this to complete
```

Can you explain what is the purpose of `fetch` and `addTask` function, can I just use axios for fetch?

**Comment by rosieks** [comment]
As you can read in last line `addTask` 
> Ensure server-side prerendering waits for this to complete

And regarding `fetch` method it add some logic to make request on server-side. When you run your code on server-side it's you cannot use relative URL so it convert it absolute to make correct request.

If you remove server-side rendering there is no problem with using axios. Otherwise you have to write some similar logic like it is in `fetch` function.

**Comment by SteveSandersonMS** [comment]
Thanks for answering, @rosieks!
