### ISSUE TITLE
Setting [Route("/")] blocks MapSpaFallbackRoute()

### ISSUE THREAD

**Issue by jamesgurung** [aspnet/JavaScriptServices#1189]
## Repro
```
yo aspnetcore-spa
(Select "Vue")
dotnet run
```
Navigating to "/counter" in the address bar correctly opens the relevant SPA route.

Now edit in `HomeController.cs`:
```C#
[Route("/")] // Add this line
public IActionResult Index()
{
  return View();
}
```
```
dotnet run
```
Navigating to "/counter" in the address bar no longer works (HTTP 404).

**Comment by SteveSandersonMS** [comment]
Your `[Route("/")]` annotation is preventing that action from handling requests for any other URL, even if the SPA fallback route points to it. So this behaviour is as expected.

I'm assuming there's some reason why you want to put `[Route("/")]` on that action, but to provide useful guidance, could you let us know why it's necessary to do that? Perhaps then we can suggest an alternative.

In the meantime I'll mark this closed since it is as designed.
