### ISSUE TITLE
how to solve chinese simply mass code 

### ISSUE THREAD

**Issue by 1483523635** [aspnet/JavaScriptServices#1190]
I am using Microsoft.AspNetCore.NodeServices nuget package and fellowing the guide https://code.msdn.microsoft.com/How-to-export-HTML-to-PDF-c5afd0ce  export html page to pdf ,then when I am using chinese simply code  on the html page ,and this return me an mess code pdf file ,how to solve this ?

**Comment by SteveSandersonMS** [comment]
When you save your `.html` (etc.) files, make sure to save them in UTF-8-with-BOM format. Otherwise the simplified Chinese characters won't necessarily be interpreted correctly.

The templates currently produce files in UTF-8-without-BOM format by default, but [we're considering changing that](https://github.com/aspnet/Mvc/issues/6716#issuecomment-327942853).
