### ISSUE TITLE
Call to Node module failed with error: Error: [object Object] = Bad Error Message

### ISSUE THREAD

**Issue by JohnGalt1717** [aspnet/JavaScriptServices#1193]
As is clearly the case when this error message is thrown by the Prerenderer.ReturnToString there is an object with the full error message available from node but it isn't properly parsed from json and thus we don't actually know what failed.

It would be really nice if this was parsed properly by the spa services and we got a real error message.

Thanks!

**Comment by SteveSandersonMS** [comment]
I agree that's not a good error message!

The better news is we improved the error reporting a while ago. As far as I can tell, this should already be fixed in the current version. Grepping through the sources, I don't see any strings prefixed with `Error:` any more.

However, if you have any way to repro this bad error message with a current .NET Core 2.0 SDK app, please let us know!

**Comment by JohnGalt1717** [comment]
Hi @SteveSandersonMS  it is indeed better under .net core 2 after our upgrade. It's still like trying to find needles in a haystack.  I wish there was a recipe on the Vs code site for hooking up .net core, chrome and nodejs debuggers in vs code to debug what's going on in node. (the other two are easy)  Getting node debugging working has still been elusive here.
