### ISSUE TITLE
Confusing Template Segregation

### ISSUE THREAD

**Issue by MiniverCheevy** [aspnet/JavaScriptServices#1200]
Prior to the 1.0.0 release of Microsoft.AspNetCore.SpaTemplates the react and angular templates were included.  These have been moved to the Microsoft.DotNet.Web.Spa.ProjectTemplates.  I cannot find where this was announced anywhere and a new install of both the .net Core 2.0 SDK and Visual Studio 2017.3 does not install them.  

If you google "dotnet new react" the first entry takes you to Hanselman's blog [post ](https://www.hanselman.com/blog/dotnetNewAngularAndDotnetNewReact.aspx) which instructs you to get the templates by running 

`dotnet new --install Microsoft.AspNetCore.SpaTemplates::*`

If Microsoft.DotNet.Web.Spa.ProjectTemplates is intentionally the new permanent home it should be mentioned in the Microsoft.AspNetCore.SpaTemplates package description somewhere.  Also, it might be wise to deprecate the existing the existing Microsoft.AspNetCore.SpaTemplates package and rename it to Microsoft.DotNet.Web.Spa.ProjectTemplates.Extras or something to make it a little more discoverable.

**Comment by SteveSandersonMS** [comment]
> If Microsoft.DotNet.Web.Spa.ProjectTemplates is intentionally the new permanent home it should be mentioned in the Microsoft.AspNetCore.SpaTemplates package description somewhere

The package you mention (`Microsoft.DotNet.Web.Spa.ProjectTemplates`) is built into the .NET Core 2.0 SDK, so people never need to download and install it manually. So we hopefully don't need to ever mention its name in the docs, as nobody will need to reference it. People can just assume that the Angular/React/Redux templates are built into the SDK and they don't need to take any steps to get them.

> If you google "dotnet new react" the first entry takes you to Hanselman's blog post 

Great point. I'll get in touch with Scott Hanselman to see he will post a note to update people on the newer arrangement.

> Also, it might be wise to deprecate the existing the existing Microsoft.AspNetCore.SpaTemplates package and rename it to Microsoft.DotNet.Web.Spa.ProjectTemplates.Extras or something to make it a little more discoverable.

That's an interesting possibility. It's probably too late to make a futher change like that now the 2.0 SDK has already shipped. Hopefully since nobody will need to know that `Microsoft.DotNet.Web.Spa.ProjectTemplates` even exists, they wouldn't expect other template packages to have a similar name to it.
