### ISSUE TITLE
How can I determine which modules are tree shakable?

### ISSUE THREAD

**Issue by tonywr71** [aspnet/JavaScriptServices#1215]
The new Angular template introduces AOT and the concept of tree shakable modules, something the old template didn't have. Can someone please explain how I can determine which modules are tree shakable and which ones are not?

**Comment by coneslager** [comment]
Some examples of integrations with 3rd party controls, like Angular Material, PrimeNG, jqxwidgets would be great.  Along with the shakable comments, some guidance on what to put into the app.module.(browser, shared, server) would be nice.  Excited about the template, just needs more documentation and real life examples.

**Comment by SteveSandersonMS** [comment]
You can put all modules in the `treeShakableModules` list as long as they are referenced somewhere in your code. If they are not referenced anywhere in your TypeScript code (e.g., because they are only there to cause side-effects such as adding properties to the global `window` context) then tree shaking would strip them out. If in doubt, try putting it into `treeShakableModules` and check if the results are what you want.

Re: docs - yes, agreed. The trouble is that third-party stuff is constantly changing and it's tricky to maintain such docs. We are reviewing what gets documented and I'll try to get the SPA-related stuff some more focus.
