### ISSUE TITLE
Angular template with Visual Studio Code issue

### ISSUE THREAD

**Issue by NeilIrvingMacc** [aspnet/JavaScriptServices#1219]
I am getting the following error when debugging a project in VS Code 1.15.1:

Got the template using this:

npm install -g yo generator-aspnetcore-spa
yo aspnetcore-spa

Made sure I had the correct webpack:

npm install webpack@2.5.1

Webpacked the files:

webpack  --config webpack.config.vendor.js
webpack  --config webpack.config.js

changed TemplateURL: to template: and Styleurls: to styles: see this article:

https://stackoverflow.com/questions/41797199/angular2-asp-net-no-resourceloader-implementation-has-been-provided-cant-re

Pressed F5 / debug in VS Code and got this:

Call to Node module failed with error: Error: Uncaught (in promise): Error: Cannot find primary outlet to load 'HomeComponent'

Is it that the typescript needs to be compiled again?

Using VSCode as I am doing a personal project

Thanks

Neil

**Comment by SteveSandersonMS** [comment]
I'm not familiar with that specific error message, but it sounds like the version of Angular you're using isn't compatible with your code.

Instead of using the Yeoman templates (which are deprecated and will be removed soon), please start your project using the `dotnet new` templates. Install the .NET Core 2.0 SDK, and then you'll be able to run `dotnet new angular` to get a clean and working Angular 4 + ASP.NET Core 2.0 app starting point.
