### ISSUE TITLE
Where to go now that JSS is deprecated?

### ISSUE THREAD

**Issue by ManuelDeLeon** [aspnet/JavaScriptServices#1221]
Where do we go with bugs and issues now that JSS is deprecated?

https://github.com/dotnet/templating issues doesn't have the same kind of issues you typically see here. Things like "The Angular project is giving X error when run for the first time".

**Comment by tehOPEologist** [comment]
@ManuelDeLeon ...JSS is deprecated?  O_o;;  do you have a link to that announcement?  i don't see why they would deprecate this, since it's the heart of .net core + spa integrations, amongst other things...

**Comment by ManuelDeLeon** [comment]
https://raw.githubusercontent.com/aspnet/JavaScriptServices/dev/templates/package-builder/src/yeoman/package.json

**Comment by tehOPEologist** [comment]
oh, the yeoman spa generator is deprecated, not JavaScriptServices itself..  i would modify this issue's title / contents to reflect that you're talking about.

**Comment by SteveSandersonMS** [comment]
@tehOPEologist is correct. This repo is definitely **not** deprecated. The only thing we've deprecated is the Yeoman generator specifically, because it's outdated and no longer updated, and everyone should use `dotnet new` (or Visual Studio if you're more of a Windows IDE person) to create new JavaScriptServices-based SPA projects instead.

I'll modify the issue title to minimise confusion.
