### ISSUE TITLE
Default Angular Template creates duplicate html and body tags

### ISSUE THREAD

**Issue by RonPeters** [aspnet/JavaScriptServices#1233]
Create a new ASP.NET Core 2.0 Web App with the default Angular template. Build and run. View the source. Note the html, head, and body tags located within the <app> tag. The console also enumerates the errors. This is obviously unintended, and I assume is an artifact of the pre-renderer.

**Comment by ltctech** [comment]
I'm not sure why this is still a problem even though it was supposedly fixed:
https://github.com/angular/universal/issues/347

I ended up putting the following in boot.server.ts for now:
```typescript
                    resolve({
                        html: state.renderToString()
                            .replace('<html><head>', '')
                            .replace('</head><body>', '')
                            .replace(/<\s*app.*?>/,'')
                            .replace('</app></body></html>', '')
                    });
```

**Comment by SteveSandersonMS** [comment]
@ltctech I don't see anywhere in that issue that they say they fixed it. AFAIK it remains an issue.

@MarkPieszak has been working with the Angular team on hopefully improving the APIs around server-side rendering so we can get the distinct outputs (HTML, title, styles, etc.) separately instead of them all being mashed together in a big HTML document string. If Angular does implement that then we'll certainly make use of it, but failing that @ltctech's workaround is as good as it gets.

**Comment by pravinpatil83** [comment]
@Anyone found a solution to this problem?
