### ISSUE TITLE
NodeInvocationException: Prerendering failed because of error: TypeError: e is not a function

### ISSUE THREAD

**Issue by beam-codegrind** [aspnet/JavaScriptServices#1255]
I've tried moving old project created in yeoman generator into new stack released with net core 2.0.

Webpack build pass correctly, but there's runtime error:
`NodeInvocationException: Prerendering failed because of error: TypeError: e is not a function`
Any idea how to fix this? I've also provided some of my configs. (I have no idea if these are enough)

[WebApplication1.zip](https://github.com/aspnet/JavaScriptServices/files/1273668/WebApplication1.zip)

**Comment by SteveSandersonMS** [comment]
Sorry @beam-codegrind, I'm afraid I don't have an answer for what's wrong with your application code. You'll need to debug and track this down yourself. Since your exception is occurring during server-side prerendering, if I was you I'd start by disabling server-side prerendering (remove the `asp-prerender-module` tag helper from your `Index.cshtml`) and then most likely you'll find the same error occurs during client-side rendering. It might be easier to diagnose during client-side rendering because you'll have access to the browser's debugger there.
