### ISSUE TITLE
An unhandled exception has occurred while executing the request

### ISSUE THREAD

**Issue by tutok** [aspnet/JavaScriptServices#1262]
I am receiving errors like this:

    Microsoft.AspNetCore.Diagnostics.DeveloperExceptionPageMiddleware[0]
       An unhandled exception has occurred while executing the request
    System.Threading.Tasks.TaskCanceledException: A task was canceled.
       at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
       at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Tasktask)
       at System.Runtime.CompilerServices.ConfiguredTaskAwaitable`1.ConfiguredTaskAwaiter.GetResult()
       at System.Net.Http.DiagnosticsHandler.<SendAsync>d__2.MoveNext()

Is there any way to find out what is causing it?

I realized that it is likely to happen when web server is running in dev mode, and then I introduce even small change in code to trigger package rebuilding, then hit f5 to refresh page. 

After that, asp.net server can not communicate with node and this error is thown constantlly:

    Microsoft.AspNetCore.Diagnostics.DeveloperExceptionPageMiddleware[0]
      An unhandled exception has occurred while executing the request
    System.Net.Http.HttpRequestException: An error occurred while sending the request. ---> 
    System.Net.Http.WinHttpException: A connection with the server could not be established
       at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
       at System.Threading.Tasks.RendezvousAwaitable`1.GetResult()
       at System.Net.Http.WinHttpHandler.<StartRequest>d__105.MoveNext()

it looks like dev server is crashing durring rebuilding, but stack trace does not contan any info where.

It could be caused by some timeout?  I tried to set InvocationTimeoutMilliseconds into 5 minutes but it not helps.

of course `webpack  --progress --display-error-details` is fine

**Comment by SteveSandersonMS** [comment]
Sorry for the inconvenience. I expect you're right that some aspect of your code or build config is preventing the build from completing, but even so, build errors should just be reported as clear build errors rather than the generic "can't communicate" messages you're getting.

Can you give any steps for reproducing this issue, starting from a new project? If I could repro it myself I'd certainly aim to provide a fix to ensure the error message clearly reported the underlying cause.

> Is there any way to find out what is causing it?

First, have you checked all through your application's console output? If there's an error within the Node part of the process, it's very likely to get logged there. An easy way to see the console output is to run your app from a command line using `dotnet run`, if that's not what you're already doing.

If that doesn't work, it's not simple, but you could edit some of the files in your `node_modules` directory to add additional logging. For example, node_modules\aspnet-webpack\WebpackDevMiddleware.js contains the Node side of the Webpack dev middleware implementation. If you add extra `console.log(...);` calls there, you'll be able to find out how far it gets through its processes and where the fault is raised.

**Comment by SteveSandersonMS** [comment]
I'll close this due to lack of response, but please let us know if you do find a repro or some way we could make this better.
