### ISSUE TITLE
Is there a timeline for pre-rendering in React?

### ISSUE THREAD

**Issue by pkellner** [aspnet/JavaScriptServices#1271]
I notice that the template for Angular has pre-rendering but the React one does not. Is there a timeline for that?  Where can I find a roadmap that talks about this and other JavaScript Services feature and timeline plans?

**Comment by SteveSandersonMS** [comment]
The React-Redux template does do server-side prerendering.

It's not desirable to have this feature in the React-only (i.e., non-Redux) template. Unlike with Angular, the whole isomorphic philosophy in React involves ensuring that the HTML rendered on the server is identical to the first render on the client. If that's not the case you get an error. So to make sure this happens, it's necessary to transfer the server-side state to the client. Redux makes this happen perfectly and transparently. If you didn't have Redux, you'd have to invent your own version of it so that the state transfer happens. Rather than reinvent a poorer version of Redux, it's better to say just use Redux (or an equivalent state container, but not just React alone).
