### ISSUE TITLE
HMR errors when using yarn

### ISSUE THREAD

**Issue by lyphtec** [aspnet/JavaScriptServices#1278]
Hi,

I get HMR errors running sample React app with latest version:

## Versions
```
> yarn --version
1.0.2
> dotnet --version
2.0.2-vspre-006949
> node --version
v8.5.0
> npm --version
5.3.0
```

## Steps to reproduce
- `dotnet new react`
- `yarn install`
- `dotnet run` (in dev mode)

## Errors from Chrome console
```
[HMR] connected
client.js:160 [HMR] bundle has 678 errors
client.js:161 [at-loader] ./node_modules/@types/react-dom/node_modules/@types/react/index.d.ts:3464:13 
    TS2403: Subsequent variable declarations must have the same type.  Variable 'a' must be of type 'HTMLProps<HTMLAnchorElement>', but here has type 'DetailedHTMLProps<AnchorHTMLAttributes<HTMLAnchorElement>, HTMLAnchorElement>'.
[at-loader] ./node_modules/@types/react-dom/node_modules/@types/react/index.d.ts:3465:13 
    TS2403: Subsequent variable declarations must have the same type.  Variable 'abbr' must be of type 'HTMLProps<HTMLElement>', but here has type 'DetailedHTMLProps<HTMLAttributes<HTMLElement>, HTMLElement>'.
[at-loader] ./node_modules/@types/react-dom/node_modules/@types/react/index.d.ts:3466:13 
    TS2403: Subsequent variable declarations must have the same type.  Variable 'address' must be of type 'HTMLProps<HTMLElement>', but here has type 'DetailedHTMLProps<HTMLAttributes<HTMLElement>, HTMLElement>'.
[at-loader] ./node_modules/@types/react-dom/node_modules/@types/react/index.d.ts:3467:13 
    TS2403: Subsequent variable declarations must have the same type.  Variable 'area' must be of type 'HTMLProps<HTMLAreaElement>', but here has type 'DetailedHTMLProps<AreaHTMLAttributes<HTMLAreaElement>, HTMLAreaElement>'.
    ...
```

Interestingly, if I use `npm` it works fine?

Here's my `yarn.lock` if it helps:
[yarn.zip](https://github.com/aspnet/JavaScriptServices/files/1306472/yarn.zip)

**Comment by lyphtec** [comment]
Further investigation shows that this is due to `webpack@2.5.1` in the template.

Updating to `webpack@3.6.0` seems to have fixed the issue.  So I guess the template needs updating?

**Comment by SteveSandersonMS** [comment]
The `npm-shrinkwrap.json` feature is vital to having a working project, because third-party packages introduce breaking changes all the time, despite expectations of semver compliance. That's why we have `npm-shrinkwrap.json` in the project by default.

So if you want to get a reliable result, I strongly recommend you use `npm`, since Yarn doesn't respect `npm-shrinkwrap.json`. I know Yarn used to be a lot faster, but `npm@5` is much closer to the speed and behaviour of Yarn.

If you are keen to use Yarn though, you'll need to convert `npm-shrinkwrap.json` into an equivalent `yarn.lock` file (maybe using [something like this](https://www.npmjs.com/package/shrinkwrap-to-lockfile)).

I know it would be better if it worked with Yarn out of the box, but there's no universally standard lockfile format in the Node world, so we had to pick the one thing we know everyone has access to.
