### ISSUE TITLE
Angular Template : Getting template parse errors

### ISSUE THREAD

**Issue by KshitizGIT** [aspnet/JavaScriptServices#1283]
I need to add a wysiwyg editor for my project.  I am getting Template parse errors whenever I install any of the popular wysiwyg editors. I have tried [angular-froala-wysiwyg](https://github.com/froala/angular-froala-wysiwyg), [angular2-tinymce](https://github.com/Ledzz/angular2-tinymce).

I am importing the modules in app.module.browser.ts file.

They work fine when using with an Angular CLI project. 

Please any help regarding this would be appreciated.

**Comment by SteveSandersonMS** [comment]
> I am importing the modules in app.module.browser.ts file.

That will be the issue. Assuming you still have server-side prerendering enabled, then it's not enough to load the editor module into `app.module.browser.ts`; you also need it in `app.module.server.ts` otherwise your templates won't be valid for server-side prerendering. Even better, just put it in `app.module.shared.ts` so it applies to both.

If you have any trouble enabling server-side prerendering for the wysiwyg editor (e.g., if it doesn't support running under Node), then you'll need to disable server-side prerendering by removing the `asp-prerender-module` tag helper from your `Index.cshtml` file.

**Comment by KshitizGIT** [comment]
The froala editor doesnt support running under Node. I had to disable the server-side prerendering to get it to work as you explained.

But I want to be able to get the benefits of server-side prerendering. Could you suggest me  any wysiwyg editor that would work with server- side rendering?
