### ISSUE TITLE
Cyrillic is not displayed correctly

### ISSUE THREAD

**Issue by NazirTemirov** [aspnet/JavaScriptServices#1287]
Hi

I created a new project with Angular template,
After RenderBody() cyrillic is not displayed correctly.

![1](https://user-images.githubusercontent.com/15430650/30589955-3c588c0e-9d45-11e7-9033-7113cc362075.png)
![2](https://user-images.githubusercontent.com/15430650/30589954-3c44c6ce-9d45-11e7-896f-f6996e5aa47c.png)
![3](https://user-images.githubusercontent.com/15430650/30589953-3c42b118-9d45-11e7-8afa-e4cef3068c18.png)
![4](https://user-images.githubusercontent.com/15430650/30589952-3c40aa94-9d45-11e7-83a6-e46ab37e4404.png)

**Comment by SteveSandersonMS** [comment]
The files created by the project system are saved in UTF-8-without-BOM format. If you put non-western characters into that file, the lack of a BOM means there's no guarantee that other tools and libraries will interpret the characters like you intended.

So, if you're including non-western characters, when you save your changes, please be sure to save the file with UTF8-with-BOM format. Since you're using Visual Studio, the first time you save one of these files with a non-western character, it will prompt to ask you if it can change the encoding to include a BOM. Make sure you choose "yes" when it does that.

Or if you've already saved it with the wrong encoding, save again using "File -> Save As...", then in the dialog, click the arrow next to the *Save* button and choose "Save with Encoding" and choose the encoding "Unicode (UTF-8 with signature)".
