### ISSUE TITLE
Isomorphic Rendering Locale Issue

### ISSUE THREAD

**Issue by DanHarman** [aspnet/JavaScriptServices#1290]
Is there a recommended approach to setting the locale to match the browser when doing server side rendering? At the moment some of my components use `Date.toLocaleDateString()` and I get different results in the browser vs the pre-rendered page which invalidates the point of pre-rendering.

**Comment by DanHarman** [comment]
Adding a wrinkle to this, it appears that even when I explicitly set `date.toLocaleDateString('en-GB')` the version of node we have doesn't have internationalisation support?

Seems to be due to the following: https://github.com/nodejs/node/issues/8500

Is it possible to install additonal node modules such as full-icu or is that the point where we get stuck recompiling the whole node services component?

**Comment by SteveSandersonMS** [comment]
This is unfortunately something you'd need to implement manually - there's no automatic way for doing this. I'm not aware that it's even theoretically possible for this sort of thing in general to be done without application-specific logic. For example, JavaScript has APIs for formatting dates according to the local timezone, but the HTTP request to your server doesn't disclose the user's local timezone, so that couldn't be accounted for in server-side prerendering unless you add application-specific logic to acquire timezone information on a previous page load, then (for example) set it into a cookie.

> Is it possible to install additonal node modules such as full-icu or is that the point where we get stuck recompiling the whole node services component?

You don't need to recompile NodeServices, because NodeServices doesn't bundle Node with it. We are running whichever Node binary is present on your environment `PATH`. So you can install whatever build of Node you like and that is what will be used at runtime.

As for `full-icu`, you could reference the [`full-icu` NPM package](https://github.com/unicode-org/full-icu-npm) without needing to rebuild Node either.

Hope that helps, and sorry there isn't a quick solution to the more general problem of acquiring locale/timezone information from the browser automatically.
