### ISSUE TITLE
Suspected HMR issue in array-style webpack configs 

### ISSUE THREAD

**Issue by AdamWillden** [aspnet/JavaScriptServices#1307]
I see that array-style webpack config support was added in this commit: https://github.com/aspnet/JavaScriptServices/commit/2241c55a9000c83592ea02dab54c6bc4359caacf

I'm trying to leverage this functionality with both configs requiring HMR support (herein lies the issue). Whichever config is listed first in the array supports HMR and the other results in failed requests `<blah>.hot-update.json 404 (Not Found)`. Similarly if I comment out any one config the remaining functions with HMR as expected.

Having had a scan of the code, I suspect there's something around the fact the two configs share the same public path. @SteveSandersonMS does it seem likely/possible?

I'd like to provide a PR if you can help with the diagnosis. I may need some help getting the code to build on my machine for testing purposes.

**Comment by SteveSandersonMS** [comment]
Although I can't help you with the diagnosis, if you track this down and believe there's an issue in some code in this repo or the standard templates, please let us know the details!

I expect that you are right that the two configs would need to have different `publicPath` values for them to be used simultaneously (otherwise the HMR service for one would capture all the requests).

**Comment by AdamWillden** [comment]
Sure thing
