### ISSUE TITLE
Getting API endpoint configuration into TypeScript files

### ISSUE THREAD

**Issue by jrmcdona** [aspnet/JavaScriptServices#1314]
Hi Steve,
Do you have any or know of any examples of getting the configuration (appSetting.json) into the TypeScript?

Looking for a clean way to that.

I would be ok with Enviornments folder too that the Angular CLI uses.

This thread hasn't helped just yet.   Perhaps it might if they end up responding but when I look at that example I am not seeing what I am trying to do and it also doesn't look like a "dotnet new angular" project.
https://github.com/aspnet/JavaScriptServices/issues/1075

Thanks

**Comment by SteveSandersonMS** [comment]
You'll first need to read the config information into your .NET code. Please check ASP.NET or general .NET docs for info on doing that.

Then, you an supply it to your TypeScript code either during prerendering by passing the object containing the config information to `asp-prerender-data` (see docs about this [here](https://github.com/aspnet/JavaScriptServices/tree/dev/src/Microsoft.AspNetCore.SpaServices#3-supplying-javascript-code-to-perform-prerendering)), or during client-side execution by serializing the config information out as JSON in your HTML page and then writing client-side code to access it (e.g., serialize it in the form of an HTML block like `<script>window.myConfig = { data here };</script>`, then in TypeScript you can read it from `window.myConfig`).

**Comment by jrmcdona** [comment]
Thanks.  This doesn't feel like legit code to me.  Please note the if (isPlatformBrowser(this.platformId))  wrapped around the HTTP call to get the endpoint config, since Window object won't be availale on the server.  Isn't this going to mess up the server view flow of Universal? How would it get data?

```
public getLeaderboardItemsBySeason(season: number): Observable<any> {
    if (isPlatformBrowser(this.platformId)) {
      return this.http.get<ILeaderboard>(this.getEndPoint() + 'leaderboard?singular=1&seasonId=' + season);
    }
  }

  private getEndPoint(): string {
        return window['TRANSFER_CACHE'].myConfig.APISettings.AmbassadorsAPI;
  }
```

**Comment by SteveSandersonMS** [comment]
> Isn't this going to mess up the server view flow of Universal?

If you need equivalent code to run during prerendering, then you can add an `else` block after your `if (isPlatformBrowser(this.platformId))` to put in whatever logic you want during that phase.

> How would it get data?

Please see my previous comment about `asp-prerender-data`. But rather than having these if/else blocks scattered around your controllers, you might prefer to make your own Angular data service injected into the controllers via DI. Then you can configure different providers for that service in the client-side boot file (using `window['TRANSFER_CACHE']...`) and in the server-side boot file (using `params.data` which is populated from `asp-prerender-data`). Please see Angular docs for details on using its DI system.

**Comment by orionstudt** [comment]
I'm trying to accomplish the same thing, but with the React template. I'm having no issue getting that data client side using `asp-prerender-data` but I must be missing something trying to make that data accessible to my app when it is rendered server side.

So, what I'm passing is an HTTP URI that I need to be able to set in the appsettings.json. However the SSR needs access to that URI in order to hit that endpoint if that Route is the first one hit. With angular you suggested taking advantage of dependency injection using a service that you just build differently in `boot-server` versus within `boot-client`. Any idea how I could accomplish something similar in React?
