### ISSUE TITLE
Can aspnet-prerendering handle custom html bits for inlining on the server?

### ISSUE THREAD

**Issue by pheuter** [aspnet/JavaScriptServices#1328]
Continuing from [this](https://twitter.com/stevensanderson/status/916916828399656960) tweet. I'm using a CSS-in-JS library called [glamorous](https://glamorous.rocks/advanced/#server-side-rendering) that allows for static rendering of CSS on the server that's designed to be inlined into a `<style>` tag in head.

From digging around a bit it doesn't seem like `aspnet-prerendering` supports passing any other information from js back to asp.net other than `html` and `globals`—`html` appears to be inlined automatically into the element which invoked the `asp-prerender-module` tag and `globals` is automatically inserted into a `<script`> tag.

Is there a way I can pass a chunk of css from glamorous back to asp.net and have it inline in the head somewhere? Any guidance greatly appreciated.

**Comment by SteveSandersonMS** [comment]
Yes, it's not easy, but you can use the prerendering APIs directly inside an MVC action instead of using `asp-prerender-module` in its view. Example usage: https://github.com/aspnet/JavaScriptServices/commit/94fc84a9b457839802831544daab1a0da88fbec1#diff-ac9fabb76766dea5d503c5a5387e88e4

This lets you get back the `globals` and `html` in your C# code so you can insert parts of each into whatever part of the view you want. Documentation is light on this right now as we're in the process of simplifying things even further in the next version of the templates.
