### ISSUE TITLE
React Redux TS - Problem with components props received from Application State

### ISSUE THREAD

**Issue by rmateusz** [aspnet/JavaScriptServices#1348]
I have a problem with getting the data from ApplicationState in new component (Header), which is set in Layout component:

`
export class Layout extends React.Component<{}, {}> {
    public render() {
        return <div>
        <div className='container-fluid'>
            <div className='row'>
                <div className='col-sm-3'>
                    <NavMenu />
                </div>
                <div className='col-sm-9'>
                <div className="">
                    <Header  />
                </div>
                    { this.props.children }
                </div>
            </div>
            </div>
        </div>;
    }
}
`
![lay1](https://user-images.githubusercontent.com/10436373/31825289-feb613e6-b5b1-11e7-9965-a9bf6b58c76b.PNG)

Header component tries to get "count" value from state:

import * as React from "react";
import { NavLink, Link } from "react-router-dom";
import { connect } from 'react-redux';
import { ApplicationState }  from '../store';

type HeaderProps = {
    count: number
};

class Header extends React.Component<HeaderProps, any> {
    constructor(props : HeaderProps) {
        super(props);
    }
    
    public render() {
        return (
            <header className="header">
                <div>
                    Hello
                    {(this.props.count > 2) ? " Wazzzup" : null }
                </div>
            </header>
        );
    }
}

export default connect(
        (state: ApplicationState) => {
        return {
            count: state.counter.count
        }}
        ,{}
)(Header) as typeof Header;
![header2](https://user-images.githubusercontent.com/10436373/31825570-f589d310-b5b2-11e7-89f4-811c2f9f8d14.PNG)

With props type set to "HeaderProps", I get error:
![1](https://user-images.githubusercontent.com/10436373/31825236-d58c977e-b5b1-11e7-9dbd-794d6e91c355.PNG)

When I changed HeaderProps to any, it works:
![any1](https://user-images.githubusercontent.com/10436373/31825601-15e4a234-b5b3-11e7-8d78-7f80fa73430a.PNG)

Working result:
![result](https://user-images.githubusercontent.com/10436373/31825653-333e2c88-b5b3-11e7-96f8-f33362f56505.PNG)

**Comment by SteveSandersonMS** [comment]
Thanks for posting. I'm afraid we don't have the capacity to handle usage questions about third-party frameworks on this issue list, so since this is a Redux question, would you be able to take it to the Redux community?

I understand in this specific case it's an issue to do with the type annotations. The type definitions come from [the `@types` project](https://github.com/DefinitelyTyped/DefinitelyTyped) so you might want to let them know if you end up tracking down an issue to their type definitions.

If you do end up tracking this down and believe there's something wrong in the project template itself, please let us know what as we'd definitely want to fix it. Hope that's OK!
