### ISSUE TITLE
Issue with webpack warnings

### ISSUE THREAD

**Issue by chriscamplejohn** [aspnet/JavaScriptServices#1375]
Hi

If I get a warning from webpack such as

"Microsoft.AspNetCore.NodeServices:Error: (node:15980) DeprecationWarning: Chunk.modules is deprecated. Use Chunk.getNumberOfModules/mapModules/forEachModule/containsModule instead."

I end up in with webpack HMR continually rebuilding and re-loading. I am not certain this is a JavaScriptServices issue, but it does seem to start with it thinking the warning is an error.

Thanks
Chris

**Comment by chuantang** [comment]
I had a problem with this when I was upgrading to Angular 5. There was a package that I forgot to upgrade and webpack threw that error. Once I upgraded extract-text-webpack-plugin to the latest it stopped throwing the error on me and everything worked again.

Have you upgraded your npm packages lately? Make sure you get them all.

**Comment by chriscamplejohn** [comment]
Thanks for the response.

I have upgraded all my packages to the latest (I believe) - I was going to move back to my previous packages.json and see if the issue went away. The other thing I wasn't sure about is if the warning is actually causing an issue or not - if I suppress node warnings when setting up the webpack dev middleware using 

`EnvironmentVariables = new Dictionary<string, string>() { { "NODE_NO_WARNINGS", "1" } }`

I still get the infinite webpack rebuilding despite not getting the deprecated warnings. I will look into the packages and post an update. I was also looking to see if I could run webpack in the same way the dev middleware does to see if it happens with webpack without the JavaScriptServices stuff.

**Comment by SteveSandersonMS** [comment]
Thanks for the answer @chuantang. @chriscamplejohn, this is not something I personally have observed, and based on @chuantang's comments, it looks like this is an issue with upgrading packages in a particular way.

If anyone manages to repro this and has reason to believe it's a defect in the template or JavaScriptServices code that supports it, then please let us know the details and we'll fix it. In the meantime I'll close this since it does sound like an external issue with upgrading packages.

**Comment by chriscamplejohn** [comment]
@SteveSandersonMS interestingly this was caused by
`"allowJs": true,`
in my tsconfig.json. I am not sure what piece in the stack that points to as the possible culprit...
