### ISSUE TITLE
Lower case variable names for POCOs passed to NodeService.

### ISSUE THREAD

**Issue by navx2810** [aspnet/JavaScriptServices#1379]
I've noticed that when you pass an object to node server, the variable names become lowercase. 
```c#
class ViewModel {
    public int Age { get; set; }
    public string FirstName { get; set }
}

NodeServices.Invoke(path, new ViewModel { Age = 28, FirstName = "John" });
```
In javascript the object looks like
```js
{ age: 28, firstName: "John" }
```

Is this the intended design? If so, is there any way to override this?

**Comment by SteveSandersonMS** [comment]
This is the intended design. The serialization convention is set to use camelCase because that's the de-facto standard on the JavaScript side, and there has to be a single convention because the framework code needs to know how to interpret other data that it receives.

If you need to pass data with a different serialization convention, then you can pre-serialize it on the .NET side (e.g., using `JsonConvert.Serialize) using whatever conventions you want, then deserialize the received data on the JavaScript side using `JSON.parse`.
