### ISSUE TITLE
__webpack_hmr 404

### ISSUE THREAD

**Issue by DanubeRS** [aspnet/JavaScriptServices#1380]
After scratching my head when adding `UseWebpackDevMiddleware` to an existing project, I have cloned, and run `dotnet run` _(2.0.2)_ on seperate  machines (OSX and Win10) to which both have responded with;
```
GET http://localhost:5000/__webpack_hmr 404 (Not Found)
```
in chrome, and;
```
info: Microsoft.AspNetCore.Hosting.Internal.WebHost[1]
      Request starting HTTP/1.1 GET http://localhost:5000/__webpack_hmr
info: Microsoft.AspNetCore.Hosting.Internal.WebHost[2]
      Request finished in 0.1069ms 404
```
in the Katana output.

Installed packages;
```
•100% ➜ npm ls --depth 0
Webpack@0.0.0 /Users/daniel/Documents/GIT/JavaScriptServices/samples/misc/Webpack
├── aspnet-prerendering@1.0.7
├── aspnet-webpack@1.0.29
├── css-loader@0.23.1
├── extendify@1.0.0
├── extract-text-webpack-plugin@1.0.1
├── less@2.7.3
├── less-loader@2.2.3
├── style-loader@0.13.2
├── ts-loader@0.8.2
├── typescript@2.6.1
├── webpack@1.15.0
└── webpack-hot-middleware@2.20.0
```

Unsure what could be causing this, or whether it might involve `webpack-dev-middleware`? Feel free to quiz me on any other setup.

**Comment by SteveSandersonMS** [comment]
I'm afraid I don't know what specifically is missing or incorrect in your setup. If you could post a minimal repro project to GitHub then we could take a look. Or for a faster resolution, compare the setup in your project to the working example produced by creating a new "ASP.NET Core + React" (for example) project using the project template built into the .NET Core 2.0 SDK.

I'll close this since it's a support request rather than a bug report, but please let us know if you do get a minimal repro or have reason to believe there's a bug in some of the framework code. Thanks!

**Comment by DanubeRS** [comment]
@SteveSandersonMS Just for reference, it was a fresh clone of the project, running the "Webpack" sample project in both cases. Might do some more scratching around using the template builder to see if there is something it is installing/configuring that is missing in my current attempts.

Thanks anyway, and will keep this thread updated for public reference if I find anything, otherwise will delegate the support request to SO.

**Comment by xt0rted** [comment]
I tried setting this up and received the same 404 error. After trying everything I could think of I finally deleted the `.vs` folder along with the site's `bin` and `obj` folders. After rebuilding & running the 404 error went away and hot module replacement started to work. This might not fix everyone's issue but it's worth trying.
