### ISSUE TITLE
Using CDN in production

### ISSUE THREAD

**Issue by davidmorissette** [aspnet/JavaScriptServices#1383]
Using the Angular template, I target my CDN in order to load the _vendor.js_ and _main-client.js_ files. That part is easy and worked as expected:

![image](https://user-images.githubusercontent.com/5100885/32692116-4f5b9110-c6e0-11e7-9d4f-7f8b064279d2.png)

My application lazy loads different modules and has to deal with different chunk files in order to accomplish that. My problem concerns the loading of these files. How can I load these files from my CDN?

![image](https://user-images.githubusercontent.com/5100885/32692159-fed1be6c-c6e0-11e7-8cac-8aa44c9d1552.png)

Thank you!

**Comment by SteveSandersonMS** [comment]
Unless I'm misunderstanding, this sounds like a question about how to set up your CDN. That being the case, could you please use the support channel for your CDN? Thanks!

**Comment by davidmorissette** [comment]
@SteveSanderson : My CDN works properly and my question is not related to it directly.

Can you tell me how to adjust the configuration so that all the chunk files (i.e. 5.js) can point to my CDN (or any arbitrary URL for that matter) instead of using a relative URL?

As an example, let's say my url is "http://myapp.net". I can edit Index.cshtml in order to load the main-client.js file from "http://mycdn.net/dist". That works fine. However, I have no power on where the chunk files will be loaded from. In my example, out of the box, they will be loaded from "http://myapp.net/dist" instead of "http://mycdn.net/dist". How can I force the chunk files to be loaded from a specific place?

Thank you!

**Comment by SteveSandersonMS** [comment]
@davidmorissette I see - thanks for clarifying. In that case it's going to depend on exactly how you've enabled lazy loading, which isn't a feature enabled by default in the template. Could you please see Angular/Webpack docs for details? If for some reason you believe the question is specific to JavaScriptServices rather than Angular/Webpack in general, could you clarify in what way that is the case? Thanks.

**Comment by davidmorissette** [comment]
@SteveSandersonMS : I enabled lazy loading this way:

`{ test: /\.ts$/, use: isDevBuild ? ['awesome-typescript-loader?silent=true', 'angular2-template-loader', 'angular2-router-loader'] : '@ngtools/webpack' }`

Since I am concerned with the behavior only in production mode, I believe the lazy loading functionality is native to `@ngtools/webpack`.

I believe my question is specific to JavaScriptServices mainly for two reasons:

1. Lazy loading is fundamental to Angular and native to `@ngtools/webpack`, which is used out of the box by the JavaScriptServices Angular's template so being able to use lazy loading should be supported.

2. Deploying a SPA application on a CDN has many advantages and it makes sense for Microsoft to offer a template that would work easily when deploying on Azure CDN, for instance.

If you don't believe JavaScriptServices is the right place to offer that type of support, could you kindly advise where I should move this topic.

Thank you!

**Comment by SteveSandersonMS** [comment]
Yes, the lazy-loading functionality comes from the combination of `angular2-router-loader` and `@ngtools/webpack` that you have set up. As for how to control what URLs the lazy loader use, could you follow up with `angular2-router-loader` and/or `@ngtools/webpack` about that, since it isn't something that JavaScriptServices code controls or has any involvement in. Hope that's OK.
