### ISSUE TITLE
webpack-hot-middleware save in dependencies vs devdependencies

### ISSUE THREAD

**Issue by JohnGoldsmith** [aspnet/JavaScriptServices#1409]
Hi,  The install advice in HMR [here](https://github.com/aspnet/JavaScriptServices/tree/dev/src/Microsoft.AspNetCore.SpaServices#webpack-hot-module-replacement) is to save under dependencies.  Is there a reason for that?  I'd kind of assumed this was a build pipeline thing and so should be saved under devdependencies?

**Comment by SteveSandersonMS** [comment]
You're right - `devDepndencies` would be fine for this. If you want to submit a PR to update these docs, please go ahead. Thanks!

**Comment by JohnGoldsmith** [comment]
Thanks @SteveSandersonMS will do.  Is that the same all the way through that doc or are there places where webpack (and webpack-dev-middleware + webpack-hot-middleware) do need to be 'dependencies'?  In the pre-rendering maybe?

**Comment by SteveSandersonMS** [comment]
Anything that runs on the server in production (i.e., is reachable from prerendering logic, or the build system if you're running the build on the server e.g., when deploying from source control) needs to be in dependencies rather than devDependencies.

Overall, the benefit of differentiating dependencies from devDependencies is minimal to non-existent.
