### ISSUE TITLE
Angular-CLI-Based-Template: Angular CLI Upgrade Issues

### ISSUE THREAD

**Issue by naveedahmed1** [aspnet/JavaScriptServices#1418]
@SteveSandersonMS Angular CLI based projects contains a file `package-lock.json`. which doesn't seem to exist in project generated through this template.

The issue is when we try to upgrade the project generated through this template to a newer version of Angular CLI it throws errors like below:

`Cannot find module 'webpack/lib/dependencies/ContextElementDependency'`

The solutions suggested for such errors is to `delete the package-lock.json` and `node_modules` folder and then run `npm install`.

Since, I am unable to locate this file in this project, I am unable to upgrade to new version of Angular CLI.

**Comment by SteveSandersonMS** [comment]
Angular CLI projects don't contain a `package-lock.json` file on their own - that's something that gets generated if you perform the NPM restore using NPM 5+ and if your directory doesn't already have an `npm-shrinkwrap.json` file.

The new project template we're building *does* contain an `npm-shrinkwrap.json` file, which NPM uses instead of generating its own `package-lock.json`. You could delete `npm-shrinkwrap.json` instead of deleting `npm-shrinkwrap.json` if your goal is to stop lockingall the package versions.

Alternatively, and better, leave the shrinkwrap/package-lock files alone, and upgrade packages using `npm install --save <packagename>`. This will automatically update the shrinkwrap/package-lock files for you.

> The solutions suggested for such errors is to delete the package-lock.json and node_modules folder and then run npm install.

Not sure where you got that suggestion, but although it does work in the sense that it resets everything, it's not a great approach to take because it allows *everything* to update instead of just the packages you wanted to update, losing part of the benefit of having a shrinkwrap/lock file in the first place.
