### ISSUE TITLE
VS 2015 Debugging Story

### ISSUE THREAD

**Issue by antmdvs** [aspnet/JavaScriptServices#142]
What is the debugging story if using Visual Studio 2015? Should we be able to set breakpoints in the original .ts/.tsx files and have an integrated debugging experience within VS or are we expected to debug using the brower's tooling?

**Comment by laskoviymishka** [comment]
As far as i know debugging from visual studio will work only in IE.
Debug webpack now generate proper source map so any IDE which support debugging chrome via source map should work. So in vs code you can use both debuggers (c# back and typescript front). This is mostly visual studio issue, that will be fixed in some near future (you can track it here _https://visualstudio.uservoice.com/forums/121579-visual-studio-2015/suggestions/6205061-provide-integrated-javascript-debugging-in-firefox_).

**Comment by antmdvs** [comment]
> As far as i know debugging from visual studio will work only in IE.

Thanks, but I'm still confused about even getting IE to work...

![breakpoint](https://cloud.githubusercontent.com/assets/17127310/16208798/e2fbe9f8-3701-11e6-9b34-cedadd604630.png)

**Comment by SteveSandersonMS** [comment]
If you're taking about debugging the client-side code then yes, definitely use your browser. It's going to be a way more straightforward experience debugging closer to where the code is actually executing.

Since these templates give you a build system that includes source maps, you'll see the original `.ts` code in your browser and can set breakpoints, step through it, evaluate variables, etc. directly there.

**Comment by doczoidberg** [comment]
is typescript deubgging possible in VS code?
