### ISSUE TITLE
Angular-CLI-Based-Template: Set outDir for client app to wwwroot/dist

### ISSUE THREAD

**Issue by naveedahmed1** [aspnet/JavaScriptServices#1422]
@SteveSandersonMS In Angular CLI based template, it would be better to serve the client bundles from `wwwroot/dist` after publish.

We could add `"outDir": "./../wwwroot/dist",` for client app in `.angular-cli.json`. which will generate the dist folder in `wwwroot`.

This way we would stay aligned with .net core as well.

**Comment by SteveSandersonMS** [comment]
We did have it configured like that previously, but it leads to the extra complication that you also need to configure a `--deploy-url` value of `dist` too so that Angular can find its own bundles.

One of the key goals for the new template is to keep the default config as closely aligned to Angular CLI defaults as possible, so there are fewer reasons why people will experience any differences in behaviour or find that online tutorials require following different steps.

So for now at least we'll keep the `outDir` at its default value. We can still review this as time goes on if strong reasons to change it emerge.

**Comment by naveedahmed1** [comment]
With current configuration, all of the JavaScript bundles are served from root of the website. For large websites that also utilize CDN, we often need to configure page rules for cache settings. Its more convenient to set cache settings for contents, when the contents matching common cache settings are grouped in a folder rather than being served from root of the website.
