### ISSUE TITLE
NodeServices Sockets (1.1.0-beta-000002) doesn't work with 2.0.x SpaServices

### ISSUE THREAD

**Issue by magnus-tretton37** [aspnet/JavaScriptServices#1428]
Maybe the answer is in the title - the Sockets package is version 1.1, and not updated for SpaServices 2.0. According to the docs, however, I should be able to use the Sockets package to run that hosting model, but when trying to do so I get this error:

`Method not found: 'Void Microsoft.AspNetCore.NodeServices.HostingModels.OutOfProcessNodeInstance..ctor(System.String, System.String, System.String[], System.String, Microsoft.Extensions.Logging.ILogger, System.Collections.Generic.IDictionary``2<System.String,System.String>, Int32, Boolean, Int32)`

I'd like to be able to use the sockets hosting model since it does offer a marked performance benefit, making SSR as fast as would expected it to be. Please see my investigation here: #1368 (don't know if you get notifications on updates to closed issues). 

Things do seems to work with the latest github code (2.1), and I know the release is soon to be, but I'm not sure the Sockets package will get a release along with the rest? It's still in beta, and you say here (#163) it won't be released at all.

**Comment by SteveSandersonMS** [comment]
We're not planning to ship or support the sockets transport option - it was only ever an experiment and never has been released to NuGet as a non-beta release. This is because we haven't found the perf benefits to be significant.

I know you mention you have found a scenario where the perf difference is consequential to you. If many others report this we might consider building a production-supported sockets transport option. But if not and you're keen to use it, you might want to consider building your own sockets-transport NuGet package that you can edit and publish whenever you want. The existing sources in this repo would be a good starting point (and are Apache-2.0 licensed). We may remove the sockets transport sources from this repo in due course since they aren't planned to be used. Hope that's OK!
