### ISSUE TITLE
Webpack Angular 2 SASS

### ISSUE THREAD

**Issue by damienbod** [aspnet/JavaScriptServices#143]
Hi nice project. @scottaddie pointed me to this project.
https://github.com/aspnet/JavaScriptServices/tree/master/templates/Angular2Spa

I created, with @FabianGosebrink a similar template for Webpack, Visual Studio, angular 2 an ASP.NET core.

https://github.com/damienbod/Angular2WebpackVisualStudio

Maybe support for SASS could be added to this template.

Greetings Damien

Template issue: https://github.com/aspnet/Templates/issues/541

**Comment by SteveSandersonMS** [comment]
Thanks for the suggestion. Hopefully people will find it quite trivial to add SASS support to the projects generated with this template (or LESS, or any other CSS preprocessor) because it's just webpack. Simply adding a SASS/LESS/etc loader to `webpack.config.js` is enough to get SASS/LESS/etc support.

**Comment by SteveSandersonMS** [comment]
Closing as this is already covered by #132
