### ISSUE TITLE
Pass data from .NET code into TypeScript code

### ISSUE THREAD

**Issue by JCPuerto** [aspnet/JavaScriptServices#1444]
Greetings,

This is related to the _Microsoft.DotNet.Web.Spa.ProjectTemplates::2.0.0-preview1-final_ angular template.

In the [Use the Angular project template](https://docs.microsoft.com/en-us/aspnet/core/spa/angular?tabs=visual-studio) page it says : "For example, see how main.server.ts passes the BASE_URL value to any component whose constructor is declared to receive it".

In the recently created file **main.server.ts** in the `extraProviders` section there's this `{ provide: 'BASE_URL', useValue: params.origin + params.baseUrl }` line and I thought all I needed to do is create another entry like that one. However, it seems that the BASE_URL provider is actually ignored and is actually taken from the existing **main.ts** file. I could delete that provider in main.server.ts and nothing happens. If I delete the provider in the main.ts I get a `No provider for BASE_URL` error.

So could you please show us an example to get a custom value sent from .NET like the one you suggested in the article; `data["isHttpsRequest"] = context.Request.IsHttps;` ?.

Thank you very much!

Good work by the way. We really appreciated!

**Comment by SteveSandersonMS** [comment]
> I thought all I needed to do is create another entry like that one. However, it seems that the BASE_URL provider is actually ignored and is actually taken from the existing main.ts file. I could delete that provider in main.server.ts and nothing happens. If I delete the provider in the main.ts I get a No provider for BASE_URL error.

Under SSR, the code *only* uses `main.server.ts`. It doesn't use `main.ts` at all. Also it could never work if it took the value from `main.ts` because that relies on DOM APIs that don't exist when running under Node. So I think you must be mistaken about this. Perhaps you didn't recompile the application after making the change, or didn't save the change or something unexpected like that.

> So could you please show us an example to get a custom value sent from .NET like the one you suggested in the article; data["isHttpsRequest"] = context.Request.IsHttps; ?.

The existing `BASE_URL` example really is a complete example of how to do that. If you duplicate all the uses of `BASE_URL` but replacing the string `BASE_URL` with some other value, then you will have duplicated the behaviour of passing a value from `main.server.ts` into an Angular component. There's nothing else to it than that.

I'm not sure what went wrong when you tried it, but if you try again and can reproduce it not working, could you post repro steps? Thanks!

**Comment by JCPuerto** [comment]
Hi @SteveSandersonMS,

You said that the BASE_URL example is a complete example... but the thing is that according to your example, in Startup.cs I'm supposed to add

```
options.SupplyData = (context, data) =>
                    {
                        // Creates a new value called isHttpsRequest that is passed to TypeScript code
                        data["isHttpsRequest"] = context.Request.IsHttps;
                    };
```
So first, there's no "BASE_URL" variables at this point. While debugging, I only have 2 items: "originalHtml" and "isHttpRequest".

I see BASE_URL defined in main.ts as 
```
const providers = [
  { provide: 'BASE_URL', useFactory: getBaseUrl, deps: [] }
];
```
`getBaseUrl` is a method that reads the base tag from the DOM.

BASE_URL is also defined in main.server.ts which right now is

```
extraProviders: [
      provideModuleMap(LAZY_MODULE_MAP),
      { provide: APP_BASE_HREF, useValue: params.baseUrl },
      { provide: 'BASE_URL', useValue: params.origin + params.baseUrl }
    ]
```
I change the "useValue"  value and after recompiling nothing happens. BASE_URL is still coming from the DOM (set in main.ts). You can check what the constructor of fetch-data.component.ts is receiving.

To reproduce this, you can follow the instructions in the "Server-side rendering" section of https://docs.microsoft.com/en-us/aspnet/core/spa/angular?tabs=visual-studio, try to change the value of BASE_URL IN main.server.ts and check the result in fetch-data.component.ts.

Maybe I'm missing something somewhere, but I think it could be easier if in the example you take the value of the "isHttpsRequest" variable you guys created in Startup.cs and try to display it in some component using console.log or something. It will be less confusing that this thing with the BASE_URL variable coming from the DOM. :-)

Please let me know if you need more information.

Thank you!

**Comment by SteveSandersonMS** [comment]
@JCPuerto I think you're misunderstanding and imagining that the DI settings in `main.server.ts` (such as the `'BASE_URL'` entry in the default template) are meant to be passed from server to client. That is not the case. Instead, those values are being passed from .NET code into TypeScript code *when it runs on the server* (i.e., during SSR).

My guess is that your goal is to pass data from .NET code on the server to TypeScript code on the client. That's why you think the values always come from `main.ts` - because when the code runs on the client, that is indeed where the DI settings come from.

If I'm right and your goal is to pass data from .NET on the server to TypeScript code on the client, and you are doing SSR, then you can:

 * Pass the data from .NET into your `main.server.ts` code using the `SupplyData` callback. This lets you populate a dictionary with whatever key/value pairs you want to pass into `main.server.ts`
 * Then, in `main.server.ts`, receive the values as `params.data.yourKeyName`.
 * Now use whatever technique you want to include your data in the rendered HTML such that your client-side code can pick it up. For this part, it's up to you to make this work, because from here on you're entirely inside your Angular app and it's not something that ASP.NET controls. One possible technique is:
    * Use Angular's DI system to pass the data through into one of your components *when it runs on the server*, just the same as how the existing `'BASE_URL'` value is passed into `fetch-data.component.ts`.
    * In the component that receives it, cause the value to get rendered into the HTML somehow. For example, you could render some markup like `<script>window.myValue= {theValueJSONEncoded};</script>`.
    * Then to pick it up on the client, add some code that reads from `window.myValue`, but only when it runs on the client (e.g., inside a block like `if (typeof window !== undefined) { ... }`.

There are many other ways to arrange passing the data from your SSR code into client-side code, but that's all internal to your Angular application and doesn't involve ASP.NET code at all, so please consult Angular docs and/or the Angular community for details and suggestions.

**Comment by JCPuerto** [comment]
@SteveSandersonMS, you understood what I'm trying to do indeed.

I'll keep looking how to implement the Angular DI for the data received in `main.server.ts` like `params.data.yourKeyName`.

Thank you for your time. I really appreciated it.

:-)

**Comment by JohnGalt1717** [comment]
Hi @SteveSandersonMS I understand what you're saying to a point, but I need to pass a param from the environment variables (i.e. our Service Url Endpoint) to the server and I need to also write it to the client code. In the past this was easy, we just put it in the base tag as an attribute we called "api" because it was a view not a static file. Now this is impossible.

So according to the above we should write these values to the dom somehow on the server side in the main.server.ts presumably. However I cannot find any documentation on how I'd update the base tag in the dom on the server side to write this value (or anything else)

So do you know of any way of doing this? I would assume it's a pretty standard problem.

**Comment by SteveSandersonMS** [comment]
> However I cannot find any documentation on how I'd update the base tag in the dom on the server side to write this value (or anything else)

In the Angular CLI app model, Angular controls the whole page content. So it's a case of using applicable Angular APIs for modifying whatever part of the DOM you want. For example, the [Meta service](https://angular.io/api/platform-browser/Meta) supposedly has both browser and server equivalents, though I haven't personally tried it.

Another possibility you might consider, avoiding SSR entirely, it to pass the value from server to client as a cookie. Use ASP.NET middleware to attach the cookie to applicable responses, remember not to mark it as HttpOnly, then read the value in client-side JS.

**Comment by isaac2004** [comment]
@SteveSandersonMS I am having a similar issue as OP and figured I would post it here. I followed the steps in the doc to setup SSR, and I want to test passing around the isHttpsRequest from Startup. I added this code to main.server.ts

````
  { provide: 'isHttp', useValue: params.data.isHttpsRequest }
````
and this in fetch-data.component.ts
````
 constructor(http: HttpClient, @Inject('BASE_URL') baseUrl: string, @Inject('isHttp') isHttp: boolean) {
    var foo = isHttp;
    http.get<WeatherForecast[]>(baseUrl + 'api/SampleData/WeatherForecasts').subscribe(result => {
      this.forecasts = result;
    }, error => console.error(error));
  }
}
````

When I publish to Azure, I get this error in console when I go to the Fetch Data route

> Error: StaticInjectorError[isHttp]: 
  StaticInjectorError[isHttp]: 
    NullInjectorError: No provider for isHttp!

The reason this seems to happen is that isHttp is not provided in main.ts. I assumed that main.server.ts was used when in Production environment, is that not the case? 

Here is a repo with the code
https://github.com/isaac2004/TestSSR

and the site deployed to Azure
https://test-ssr.azurewebsites.net/


I assume I am missing a stupid step, but the doc isn't clear. Any help would be greatly appreciated. Thanks

**Comment by isaac2004** [comment]
@JohnGalt1717 were you able to figure this out? Having the exact same issue/need

**Comment by JohnGalt1717** [comment]
Yes. It's convoluted and I believe there is now a sample in JavaScriptServices to do it.

**Comment by isaac2004** [comment]
In this repo? I just looked around and found nothing. Link?
________________________________

**Comment by JohnGalt1717** [comment]
Should be in the templates which you have to dig for now but they're there.

**Comment by isaac2004** [comment]
I looked in the templates and there are not samples there either.
________________________________

**Comment by JohnGalt1717** [comment]
Sorry. They used to be there. My samples would all be pure webpack because .NET core is basically useless with Angular CLI. It's just a wrapper at this point. Better to use express under nodejs if you need SSR or just plain Static HTML if you don't if you're using the CLI. Cuts out the middle man that can't do anything anyhow.

**Comment by isaac2004** [comment]
I refuse to believe that it is impossible. I can get API calls to render in server with transfer, but not load index with data from server on build.
________________________________

**Comment by SteveSandersonMS** [comment]
@isaac2004 I don't have a specific sample, but:

1. Pass your data into any Angular component using the same pattern that the template uses for passing the base URI
2. Use the Angular component to render that data into the DOM. See Angular docs for how to do that.
3. Use JavaScript to read the data back from the DOM. Example:

```
if (typeof window !== 'undefined') { // This is client-side execution
    var element = document.getElementById('myElementId');
    var value = element.getAttribute('some-attribute');
    // Now do something with 'value'
}
```

**Comment by isaac2004** [comment]
Thanks for this, I think I am stuck the step before that. I understand how to load the data into components, but getting it into the html of the app is where I am stuck. I looked at most of the code in NodeServices but wasn't sure in what manner you need to get the data in main.ts. in main.server.ts I get it. The issue I am having is that I get a no provider error unless that value is provided in main.ts.

So if I add a value in SupplyData in Startup, what needs to go in main.ts to make it available to the rest of the app?
________________________________

**Comment by SteveSandersonMS** [comment]
Let's say you're adding an entry to DI with the key `APP_INSIGHTS_KEY`. That is, there's some entry for it in `providers` in both `main.ts` and `main.server.ts`. You have other components that receive this as a constructor parameter via `@Inject('APP_INSIGHTS_KEY') appInsightsKey: string`. One of these components is responsible for rendering it into the DOM as described above.

Your server-side provider for `APP_INSIGHTS_KEY` in `main.server.ts` would get it from `params.data.appInsightsKey` or whatever name the server supplies it under.

Your client-side version of `APP_INSIGHTS_KEY` in `main.ts` would read it from the DOM in the manner I described above.

**Comment by isaac2004** [comment]
But where is it put in the DOM? I think that is what I am failing to grasp. For baseurl it is a tag, but SupplyData does not do that for other items it seems.
________________________________

**Comment by JohnGalt1717** [comment]
You can put it anywhere you want. The provider simply goes and gets the value and passes it back. When you're doing server side there is a special way to push those values in. On client side you have to do it yourself.

eg:  { provide: SERVICE_URL, useFactory: AppModule.GetServiceUrl },

	static GetServiceUrl(): string {
		return document.getElementsByTagName('base')[0].getAttribute('api');
	}

**Comment by chamikasandamal** [comment]
Is there a way that we can inject dontnet config entry into angular? In above mentioned way it seems SSR inject will be valid only for the SSR code and we need to put another value in markup to get in into client side code.

**Comment by JohnGalt1717** [comment]
You have to inject it into your HTML. You can use the angular transferstate to do so.  Be careful to at least base64 encode the values or entire json object that gets written to HTML or you'll likely fail a PCI audit.

**Comment by blowdart** [comment]
Whilst I love the idea of people caring about PCI base64 encoding won't help you with an PCI obligations you have. It's just an encoder, it doesn't encrypt or protect anything in the way that PCI may require,.

**Comment by JohnGalt1717** [comment]
It isn't about encryption.  If you're passing that stuff don't!

It's about the fact that they will false positive you for so much as passing an email address in the HTML even though the user is going to enter it anyhow and it was directly available in your cookie or index db which is easily inspectable and lots of pages return those results on post back. That's ok, but a json object isn't because most PCI scans done don't actually look at how the data could be used, only that it's there.

Thus save yourself the hassle of BS scanners and ignorant people at your payment processor that don't understand code and just parrot the scanner and encode the json object it generates.

**Comment by blowdart** [comment]
Oh lord that's an even worse reason.

Puts on MSFT official hat

"Obviously we would never recommend any attempts to bypass a PCI scan in any way"

**Comment by JohnGalt1717** [comment]
Tell that to the Payment processors and their PCI scans that don't secure anything.  In fact, please work with the industry to educate them as to why their PCI scans are meaningless as currently written.

I'd love to not have to do this, but if you pass a JSON object directly in a page and there is so much as an @ sign in the text or one could be entered by their bots on a form somewhere you will fail and you won't be able to bypass it even though they can't give any use case where it would cause a security issue.

Thus, since json is no more dangerous if created carefully than a cookie or indexdb, the only solution is to base64 encode the data that you're passing from server to client side.

If you have a better suggestion I'm all ears but from where I've stood in this ridiculousness the way that the Server Transfer system is setup in angular requires you encode it if you don't want to get flagged.

**Comment by JohnGalt1717** [comment]
@SteveSandersonMS Looking at the above and the latest template it looks like everything is driven off of index.html now for Angular. So there doesn't appear to be aw at to inject server side values into the DOM like api configuration etc. like there used to be when this was a view.

So how do you suggest passing values to a site without SSR (SSR you can use the transfer state obviously and pass it through SSR to the client)

**Comment by syedm0** [comment]
@SteveSandersonMS 

I am having trouble passing data (logged on users Id from windows authentication). I believe I have followed all the steps however the element I use to pass the data is coming up as null! on the client side.  I took following steps:

a) In Startup.cs store the logged on users Id as follows:

                   options.SupplyData = (context, data) =>
                    {
                        data["userId"] =  context.User.Identity.Name;
                    }

b) In main.server.ts read it and make available to components:

  const options = {
              document: params.data.originalHtml,
               url: params.url,
               extraProviders: [
                    provideModuleMap(LAZY_MODULE_MAP),
                    { provide: APP_BASE_HREF, useValue: params.baseUrl },
                    { provide: 'BASE_URL', useValue: params.origin + params.baseUrl },
                    { provide: 'USER_LOGINID', useValue: params.data["userId"] }

c) Inject this into nav menu component (of template) and set it up in the html as anchor tag text:
    /* nav-menu.component.ts */
    constructor(@Inject('USER_LOGINID') userLoginId: string) {
          this.logonUserId = userLoginId;
    }

   /* nav-menu.component.html */
                 <a id="navbar_logon" href="#">
                  {{logonUserId}}
                </a>

 e) In the client side main.ts read the anchor tag text as follows :
   
   export getUserLoginId() {
       return document.getElementById('navbar_logon').innerText;
    }

    const providers = [
               { provide: 'BASE_URL', useFactory: getBaseUrl, deps: [] },
               { provide: 'USER_LOGINID', useFactory: getUserLoginId, deps: [] }
    ];

However it seems on the client side the document.getElementById() is returning a null

Can someone please advise where I may be wrong?

**Comment by JohnGalt1717** [comment]
@syedm0 FYI with Angular CLI enabled versions it now isn't possible to pass this data as previously discussed. You can still inject into Server Side Rendering and get results back as it was before, however you cannot pass results into the page in the same way. The best way to do it is to either use something like Redux or have the server side angular inject values into the DOM. 

Alternatively you can either use a cookie in your asp.net code that sets the values returned from SSR into the cookie, or you can use a WebApi endpoint that is called to get the values in a json object in your browser's main.ts file before anything else is kicked off.

I did this like this:

`

import { Globals } from './app/globals';
fetch('/config/get').then(response => {
	response.json().then(result => {
		Globals.Configuration = result;

		platformBrowserDynamic().bootstrapModule(AppBrowserModule)
			.catch(err => console.log(err));
	});
});
`

For fetch to work look at caniuse and/or put in a shim like we did.

It's all very hackish and Angular's SSR is still HORRIBLE even in Angular 6. It's gotten better but still isn't great. We gave up on it because it was taking WAY too much time and simply use http://prerender.io now for SSO.  Cheaper than the time wasted with SSR not working right all of the time, and makes everything transparent.  We render the menus at the top and footer in the <app-main></app-main> so that everything looks like it's loading and then the rest of the site, which we have down to about 1.5 seconds with angular 6 with all of the improvements.

**Comment by syedm0** [comment]
Agreed .. but in our case the API is completely decoupled with the app. 

I would think there must be a simpler way to pass authenticated user information information from server? Any suggestions?

We would like to not use SSR if possible. It has a dependency on nodejs on server side and if we want to add docker support I'm not sure how the nodejs dependency will be included in docker image (docker support is also greyed out when trying to use the current template).

It seems to me that the current template for dot net core with angular does not offer a straightforward solution. Does it mean one has to go back to MVC and try to integrate Angular into it. Because through MVC there is more server side control through the views and cshtml.  However, there seems to be no template for MVC-Angular. 

Any other suggestions Ideas?

**Comment by JohnGalt1717** [comment]
Our API is completely decoupled too. We put the WebAPI endpoint in a controller in the MVC solution using JavaScriptServices. All of the login stuff we put in a cookie that is passed in the SPA function listed in the docs.


My personal suggestion is don't use SSR, put in a template that looks like your nav and footer while it's loading and then use [www.prerender.io](prerender.io) and the .net core library for it to intercept bots and provide them with the fully rendered HTML for any given request.

We actually got better SSO as a result, a better user experience (SSR causes the UI to be rendered but not interactive which annoys users because they click stuff and it doesn't work or works badly) and everything is way faster and our developers aren't banging their heads against a wall constantly.

**Comment by syedm0** [comment]
Thanks John, Unfortunately we have a requirement to use open source code. One would imagine there should be some solution for this basic need.  I wish someone could respond with the right solution. This used to be so straightforward and simple with ASP.NET MVC and angularJS.

**Comment by JohnGalt1717** [comment]
Prerender.io is 100% open source.  [Prerender Node service](https://github.com/prerender/prerender)

All of the libraries for every language is also open source in the root of that project or similar.

**Comment by syedm0** [comment]
John.. what do you mean by 

 server side angular inject values into the DOM.

I guess its the same thing as 

Use the Angular component to render that data into the DOM

mentioned by @SteveSandersonMS and that's what I'm missing.

I put a breakpoint inside server.ts where I try to get the navbar anchor value (also tried with a hidden input element) however I dont see any elements under app-root. However I dont think I can add anything into app-root. 

Wish there was some clear documentation/example.. it seems such a basic thing to be able to pass a logged on user id to the client side.

**Comment by JohnGalt1717** [comment]
All of the original documentation relied on MVC driving the index.html page (csthml in that case.)  the CLI does not allow this to happen. It drives it's own index.html page with injected scripts etc.

Thus it isn't possible to pass server side to client side anymore without using a cookie or using an out of band fetch call as I noted. (I suppose you could write an interceptor for static content and inject it into the HTML stream... yuk)

That's why the documentation isn't clear. It is easy to pass values to the SSR renderer it is basically impossible without the approaches listed above to pass that information to the client and it's entirely a limitation on how the CLI works.

**Comment by syedm0** [comment]
Thanks a lot John.

**Comment by maxisam** [comment]
I think it is possible. I haven't really tested it through, but here is the solution in my mind

Change index.html in Angular to index.cshtml and change the setting in angular.json as well.

Probably need to use gulp to copy the file to view folder or use it in a different view file.

probably need to change deployUrl and output folder in angular.json.


I think the first one is the most important one. Once you can generate a cshtml, it gives you lots of possibilities to do what you want.

**Comment by chamikasandamal** [comment]
@maxisam : Angular CLI does not support cshtml. if you want to use that you need to generate the html using .cshtml before angular CLI runs. In that case you cannot pass any run time information.

**Comment by maxisam** [comment]
@chamikasandamal Have you tried it? It actually works. CLI can generate a chtml or whatever thing you want depending on the setting in angular.json.

Of course, using API to get data is always one way to go.

**Comment by syedm0** [comment]
Third party authentication solutions may not even offer api support. Case in point is CA siteminder which utilizes an isapi dll which basically uses redirection to redirect an incoming user to a authentication page and then redirects back to the web application. In this case it is essential and bare minimum that the server side be able to send the authenticated users information to the client. This would be utilized later by the client to make api calls on behalf of the user.

Cannot believe that there is no support for something as simple as this.

The earlier templates included in visual studio included support for server side cshtml rendering and passing of information from server side.

The latest templates do not contain this facility, and there is no code or example to demonstrate how ssr could be used to pass information.

I think this is a significant gap.

**Comment by lenart91** [comment]
@syedm0 I suspect that [TransferState](https://angular.io/api/platform-browser/TransferState) is what you're after.

So with that added to your project, you'd want something like this (note: still utilizing your existing injection token & .NET back-end code):
```
const USER_LOGINID_KEY = makeStateKey('userLoginId');

constructor(@Inject('USER_LOGINID') userLoginId: string) {
   const domDeserializedUserLoginId = this._state.get(USER_LOGINID_KEY, null as string);
   if (domDeserializedUserLoginId) {
      this.logonUserId = domDeserializedUserLoginId;
    }
    else {
      this._state.set(USER_LOGINID_KEY, userLoginId);
    }
}
```

This in effect means that when the server runs your code, it serializes your injected 'userLoginId' token value (data from .NET) and stuffs it into the DOM. When the client runs, it simply deserializes it and sets your class variable appropriately.

Hope this helps!

**Comment by zolakt** [comment]
I've found a workaround, not a great one, but works.

I didn't have any luck with rendering the data "however I wanted", as was mentioned previously, for passing the data from SSR to CSR. CSR removes the SSR render result, so an rendering a element, inside app html, wasn't working. However you can modify the html outside the angular root, and it shouldn't change, for example the body element.

Something like this:

in app.component.ts
`
export class AppComponent {
	constructor(@Inject('APP_CONFIG') config, @Inject(DOCUMENT) document) {
		if (document && config) {
			let body = document.getElementsByTagName('body')[0];
			body.setAttribute('data-jsTransfer', JSON.stringify(config));
		}
	}
}
`

and in main.ts
`
export function getAppConfig() {
	let element = document.getElementsByTagName('body')[0];
	return element ? JSON.parse(element.getAttribute('data-jsTransfer')) : {};
}

const providers = [
	{ provide: APP_BASE_HREF, useFactory: getBaseUrl, deps: [] },
	{ provide: 'APP_CONFIG', useFactory: getAppConfig, deps: [] }
];
`
