### ISSUE TITLE
Dealing with slow XHR requests while using Server Side Rendering

### ISSUE THREAD

**Issue by joelnotified** [aspnet/JavaScriptServices#1446]
Hi,
I've started using `Microsoft.AspNetCore.SpaServices.Extensions 2.0.0-preview1-final` (as described here https://github.com/aspnet/JavaScriptServices/issues/1288#issuecomment-346003334) to enable SSR.

It works just fine. However, during boot of my application I have an XHR request that for various reasons might take some time. If it does, then the SSR will timeout and I get an error like "NodeInvocationException: Prerendering timed out after 30000ms because the boot function in '../Clients/dist-server/main.bundle.js' returned a promise that did not resolve or reject".

Can I set some kind of fallback so that the server ignores requests or aborts SSR if if should take more than a couple of seconds?

**Comment by SteveSandersonMS** [comment]
You can certainly implement whatever kind of timeout and fallback logic you require. In your TypeScript/JavaScript code, whenever there is a `fetch` call, you could use a technique such as this: https://davidwalsh.name/fetch-timeout

If you want a top-level timeout that would cover all of the prerendering logic, you could modify your `main.server.ts` file so that the `renderPromise` that gets returned has a timeout associated with it and if the timeout fires, it supplies some placeholder HTML instead of the real SSR result, e.g.: https://italonascimento.github.io/applying-a-timeout-to-your-promises/
