### ISSUE TITLE
No Browser Link Connection

### ISSUE THREAD

**Issue by doczoidberg** [aspnet/JavaScriptServices#145]
In VS there is no browser link connection so that I can't reload the page via Control+Alt+Enter

**Comment by SteveSandersonMS** [comment]
I wouldn't expect Browser Link to interact well with HMR, and I'm not sure there would be significant benefits to having Browser Link on when you have a full HMR setup. So at least for now, this is by design.

If you find that you can enable Browser Link and can solve any issues it triggers with HMR, please feel free to reopen with a proposal on how to do that. Of course, please bear in mind that these templates are not VS specific and need to continue working cleanly in cross-platform (non-VS) scenarios too!
