### ISSUE TITLE
Angular-CLI / Angular 5 based template: Will it support Angular's i18n?

### ISSUE THREAD

**Issue by kadamgreene** [aspnet/JavaScriptServices#1456]
Will the JavascriptServices Angular CLI/ Angular 5 based  SPA template support i18n.  When you do production build of Angular 5, it bakes in the language (i18n support is compiler based and AOT removes the compiler).  So if you want to support multiple languages you do a build for each language, and pick which JS files to serve to the client based on some mechanism.

For this to work, JavascriptServices need to provide a mechanism per request that allows us to decide which set of javascript / css to service.  Does it provide such a mechanism?

**Comment by SteveSandersonMS** [comment]
Interesting question. It's not something we have a special feature for, but you do get to control what files get served, so it should be possible to implement what you need.

In the Angular CLI-based template, the following line in Startup.cs causes the Angular static files to be served from `ClientApp/dist` in production:

```
app.UseSpaStaticFiles();
```

If you removed that line and replaced it with some custom ASP.NET middleware to serve static files from `ClientApp\dist` according to your own localisation rules, that should achieve what you want.

I don't know how it's meant to work in development mode - how does Angular CLI's `ng serve` know which language files to serve? But since we're just proxying requests to Angular CLI, whatever feature they have for this should work just the same here too.
