### ISSUE TITLE
Question: React SSR via Microsoft.AspNetCore.SpaServices.Extensions

### ISSUE THREAD

**Issue by buvinghausen** [aspnet/JavaScriptServices#1457]
@SteveSandersonMS 

I'm trying to embrace the new way of doing things via the Extensions project (which I _**love**_ BTW) but the only challenge I'm having right now is getting SSR up and running.

In the Template.csproj you have the following configuration

```xml
    <!-- Set this to true if you enable server-side prerendering -->
    <BuildServerSideRenderer>true</BuildServerSideRenderer>
```

Under the covers it's just running npm run build:ssr but create-react-app doesn't have a script built by that name so it fails.  Unfortunately since this library is so brand spanking new I haven't found any suitable examples to follow out on the web.  

What I'm leaning towards right now is using the Extensions app only for development (HMR & no SSR) then using my old webpack.config which emits both server & client production optimized bundles to the wwwroot\dist folder and still using standard Static File Middleware + Razor Pages (asp-prerender-module & asp-prerender-data tag helpers) to serve the content the old way when not in development.

Before I undertake this process to get it all up and running I just want to verify that there isn't some better way to achieve what I want that will be closer in line with the vision you guys have for the future (and yes I'd much rather be using Blazor but that's still too experimental but I will be keeping an eye out going forward)

**EDIT** found the Angular examples just not sure how to proceed with react. Will test some things out tomorrow because I definitely would love to skip the razor pages + tag helpers stuff if possible.

Thanks,
Brian

**Comment by SteveSandersonMS** [comment]
Ah, the `<BuildServerSideRenderer>` property shouldn't be in the React-Redux template's csproj file. It's a mistake that it's there in the preview1 release, so I'll remove it from the subsequent releases. Thanks for pointing this out!

Since Create-React-App (CRA) itself doesn't support building SSR-compatible bundles, this means that the newer React and React-Redux ones don't have that feature out of the box either. If you need SSR, then you'll need to [eject from CRA](https://github.com/facebookincubator/create-react-app/blob/master/packages/react-scripts/template/README.md#npm-run-eject) and then follow whatever steps you have for implementing Node-based SSR for a React app, and invoke them from ASP.NET using the same APIs that the Angular template does.

Our goal is for developers to have the benefits of CRA, so we're not planning to add any SSR functionality to the React templates until CRA itself can support building SSR-compatible bundles. We don't want to be any more opinionated than CRA itself is about how this should work.
