### ISSUE TITLE
 prerendering.createServerRenderer pass null value to the callback function.

### ISSUE THREAD

**Issue by ElderJames** [aspnet/JavaScriptServices#1458]
I use the taghelper in view file,and call the prerender by `asp-prerender-module` attribute.
But the  `prerendering.createServerRenderer` function pass null value to the callback function.
It cause the Uncaught TypeError: Cannot set property '_registeredComponents' of  null and the context is nul. 

My code is here: https://github.com/ElderJames/vuetify-aspnetcore/blob/master/Views/Home/Index.cshtml

Now I must render by `ISpaPrerenderer`  instead of taghelper.

**Comment by SteveSandersonMS** [comment]
Thanks for letting us know. Unfortunately I can't really take any action on this report, because the problem you're describing is specific to your own code - for example, `_registeredComponents` is not a concept that exists in any of the code in this repo, and in the default templates, `createServerRenderer` definitely passes non-null values to its callback otherwise SSR would never work out of the box.

If you're able to track this down to something you can provide minimal repro steps for, could you please file it as a new bug with those repro steps? Ideally, start with one of the default templates (e.g., the Angular or React-Redux ones) and describe what minimal set of modifications cause an error that you don't think should occur. Thanks!
