### ISSUE TITLE
Add Server Side Rendering Support to Vue.js

### ISSUE THREAD

**Issue by RehanSaeed** [aspnet/JavaScriptServices#1471]
According to https://github.com/aspnet/JavaScriptServices/issues/754, SSR was removed from the Vue.js template because of a dependency on Node.js. This is no longer the case with [Vue 2.5.0](https://gist.github.com/yyx990803/9bdff05e5468a60ced06c29c39114c6b#environment-agnostic-ssr).

I don't know the details of how this would get implemented. Could I use the code removed in the [remove server side rendering commit](https://github.com/aspnet/JavaScriptServices/commit/c3ad9e8c2fc7e85bea2870eb0f8dce2fd2973de9) to implement this feature? I also found [this](http://mgyongyosi.com/2016/Vuejs-server-side-rendering-with-aspnet-core/) blog post.

**Comment by SteveSandersonMS** [comment]
I'm not certain how applicable the code you linked to is, since that was written a long time ago and Vue's APIs might have changed since then.

If someone in the community is interested in submitting a PR to enable SSR for Vue we'd certainly consider it (as the ASP.NET team is busy with other work items so we're unlikely to implement it soon ourselves). Hope that's OK!
