### ISSUE TITLE
Angular-CLI template .ts Visual Studio Debugging not working.

### ISSUE THREAD

**Issue by Qowy** [aspnet/JavaScriptServices#1474]
Hi,
I cannot get typescript debugging within Visual Studio to work with the new Angular-cli template.
The .ts files show up fine within chrome under webpack:// and I can debug there, but the support of setting breakpoints within VS seems to be broken.

Any ideas? (I am using rc1)

**Comment by pherbel** [comment]
Same issue here

**Comment by agegould** [comment]
Hi @SteveSandersonMS - Do you have any information regarding debugging Typescript using Visual Studio using the new Angular-CLI template JavaScriptServices and Angular CLI? 

Managed to successfully debug using VS Code attaching to Chrome with sourcemaps enabled but ideally should be debugging using Visual Studio.  

Thanks in advance...

**Comment by Kirtlander** [comment]
ditto here. After installing the templates (Microsoft.DotNet.Web.Spa.ProjectTemplates::2.0.0-rc1-final) and creating a new "angular" project, I was unable to run the sample code in the VS 2017 debugger until I updated my package.json dependencies for Angular from 5.0.0 to 5.2.1 (current). I had to downgrade Bootstrap to 3.x since it seems 4.0 creates breaking changes for the template markup.

Unfortunately, however, I am unable to set breakpoints in the browser-side JavaScript in Visual Studio 2017 and have them hit (they are hollow circles, indicating the map file wasn't loaded). This worked fine with the previous (production) template. It appears that the map files aren't accessible to the VS 2017 debugger, although they are accessible in Chrome Developer Tools under webpack://.

**Comment by agegould** [comment]
Debugging in the browser works well, so this is a way forward until VS Debugging is supported.

**Comment by SteveSandersonMS** [comment]
It looks like VS is not able to recognize the inline source maps that Angular CLI generates. You could report this to Visual Studio: https://visualstudio.uservoice.com/forums/121579-visual-studio-ide

**Comment by math07** [comment]
If someone is interested in voting for this issue on the Visual Studio Report site, here is the link https://visualstudio.uservoice.com/forums/121579-visual-studio-ide/suggestions/33300286-please-support-angular-cli-sourcemaps-generated-in

**Comment by OutSorcerer** [comment]
VS Code also had [issues](https://github.com/Microsoft/vscode-recipes/issues/81) with debugging Angular, but now it seems to support debugging with the latest angular cli.

**Comment by Zerendipity** [comment]
Is this still an issue? is there a workaround? 
I want to update the project but without debugging it would be impossible.
