### ISSUE TITLE
【Feature Request】Request Angular's template from razor views at build time.

### ISSUE THREAD

**Issue by ElderJames** [aspnet/JavaScriptServices#1478]
In order to use the taghelper feature with Angular, I must set a url to the TemplateUrl property of @Component.
Howerver,I can't build the angular project with AOT mode,and the template would request the asp.net server every time the page rendering.On the other hand,it would make the vender file very large.

So,I request a feature that at webpack build time, asp.net core can generate the rendered html template  for angular's AOT building.

Look forward to your good news, thanks!

![image](https://user-images.githubusercontent.com/7550366/34987377-eae8b768-faf5-11e7-987a-e99b89eb2163.png)

**Comment by UtilCore** [comment]
强烈支持，顶。
我现在也碰到这个问题，不知道Razor是否可以和Angular一起使用，而且没有性能问题。
我的项目地址是：https://github.com/dotnetcore/Util
目前在Util.Samples.Webs测试项目中摸索如何将Angular Material组件封装成TagHelper和HtmlHelper组件。

**Comment by SteveSandersonMS** [comment]
It's an interesting idea, but I don't think ASP.NET is the right tool to generate those files at build time. Since what you want is *build time* `.html` generation, it would make sense to use a build-time tool such as [T4](https://docs.microsoft.com/en-us/visualstudio/modeling/code-generation-and-t4-text-templates), rather than ASP.NET which deals with HTML generation as a runtime concern in response to HTTP requests (there aren't any HTTP requests at build time).
