### ISSUE TITLE
The SPA default page middleware could not return the default page '/index.html' because it was not found

### ISSUE THREAD

**Issue by gursin87** [aspnet/JavaScriptServices#1488]
I have published the app to Azure app service from visual studio. I am getting the following error when trying to browse to the application:

2018-01-23 16:27:24.118 +00:00 [Error] Microsoft.AspNetCore.Diagnostics.ExceptionHandlerMiddleware: An unhandled exception has occurred: The SPA default page middleware could not return the default page '/index.html' because it was not found, and no other middleware handled the request.
Your application is running in Production mode, so make sure it has been published, or that you have built your SPA manually. Alternatively you may wish to switch to the Development environment.

I copied the file index.htm to the folder "ClientApp/dist/index.htm". Now I am not getting the exception. But the page just renders the following:

![image](https://user-images.githubusercontent.com/18685917/35289771-51ce0058-008e-11e8-8687-961a976dd657.png)

Would appreciate if you could help me with what the issue might be. 

Thanks

**Comment by SteveSandersonMS** [comment]
Although you said that you published the application from VS, it looks like the app you're trying to run has not been published at all (in the sense that the "publish" config generates `ClientApp/dist/index.html` in the publish output location, so you should not have needed to put any file there manually). Can you please confirm that when publishing you are actually running "Publish" from the "Build" menu and deploying to Azure directly from that menu item ([instructions](https://docs.microsoft.com/en-us/aspnet/core/tutorials/publish-to-azure-webapp-using-vs))?

I'll close this for now since AFAIK this has been verified to work already, but if you still believe we have a bug and can supply repro steps, please let us know!

**Comment by gursin87** [comment]
Hi Steve, yes i am doing a "Publish" :) . I had an app with the old template published and i was trying to upgrade and publish. I noticed if i create an angular app from visual studio and try to publish it with no changes, i see the issue. If i create it from VS code using command line "dotnet new angular", it publishes fine.  I am checking to see what are the other scenarios i am able to repro the issue.

**Comment by joshpearce** [comment]
It's an IIS Default Document issue. Just add the following to your web.config:

```
<system.webServer>
   ...
      <defaultDocument enabled="false" />
</system.webServer>
```
