### ISSUE TITLE
Cshtml based start-up page as input for ng serve

### ISSUE THREAD

**Issue by cveld** [aspnet/JavaScriptServices#1493]
At our engagements we don't use nodejs server-side at production but really use a HomeController index.cshtml setup to feed the SPA with configuration and other cached initialization data that is generated by classic .NET.

During dev we depend on ng serve for HMR and all the other goodness.
So far we only see examples where ng serve generates its own index.html and feeds this output to the browser.
Is there a way to feed the browser with the output of HomeController's index.cshtml in combination with ng serve?

**Comment by SteveSandersonMS** [comment]
I'm afraid there isn't a known way of doing that. The whole `ng serve`-based approach relies on `ng serve` producing the `index.html` content. So in general it works best for initial dynamic data to be fetched by the client using an HTTP request rather than trying to embed it in `index.html`.

**Comment by zolakt** [comment]
I have a similar issue. And this would be really useful.
I'm upgrading from the old Angular template where it was handled through the asp flow.
I have a theme experiment system, it has a bunch of them, for A/B/N testing. I don't want to bundle everything into Angular components, because it's just a whole lot of plain css, and only a few of them are rendered at a time. I need a way to inject dynamic external css in the view, similar how it worked with the last template. Any suggestions?
