### ISSUE TITLE
Debugging Typescript

### ISSUE THREAD

**Issue by doczoidberg** [aspnet/JavaScriptServices#152]
Is it possible to debug the typescript code in VS/VSCode?

**Comment by zigzag95** [comment]
No. I tried playing with chrome debugger and some extensions to code but no way

**Comment by SteveSandersonMS** [comment]
I'm not aware of a way to do that. You might want to take this up with the VS/VS Code projects, since they would be the ones to implement anything like that.

**Comment by emzero** [comment]
The problem with debugging TS in the browser is that sometimes the syntax coloring is way off. Debugging original ES6 files works well because ES6 is actually partially supported by chrome.

But Chrome doesn't recognize the special TypeScript syntax and sometimes you end up going though a block of code that is colored like it was a comment.

Hopefully somebody would write a Chrome extension for proper TS syntax highlighting now that TS is becoming more popular.
