### ISSUE TITLE
Consider switching React-Redux template folder structure to fractal

### ISSUE THREAD

**Issue by emzero** [aspnet/JavaScriptServices#153]
Grouping files by type instead of modules/features usually results in code being harder to find and whole project becomes unorganized.

Instead, grouping it by "modules" (or features) makes it easier to follow, even in a really big project.

Here are a few examples of this structure implemented in a React/Redux app.

https://github.com/davezuko/react-redux-starter-kit/wiki/Fractal-Project-Structure
https://github.com/jaysoo/todomvc-redux-react-typescript/tree/master/client

**Comment by SteveSandersonMS** [comment]
Definitely happy to consider this. Do you want to provide details on how you'd reorganise `ReactReduxSpa`?

BTW, I thought the `ReactReduxSpa` already *was* organised by feature area, and not by file type. I went to some length to set it up this way, because I also strongly prefer organising by feature area. That's why, for example, everything related to "counter" is in the `Counter.tsx` file for the UI component, and `store/Counter.ts` for the store aspects of it. It's *not* structured like many Redux samples where you'd have "actions" in one folder, "action creators" in another folder, "reducers" in another folder, and so on.

I did retain the separation of "UI" versus "store" because that's pretty much the central concept of Flow/Redux, and if your goal is to test these independently, you'd really want to avoid unintended coupling of UI and store code. Not having a clear division between "store" and "UI" would seem to undermine the whole architecture.

**Comment by emzero** [comment]
Yes, I think the store should be kept separated from the UI as it is now. Nothing to change there IMHO.

I guess the part that could be improved is how all the different components are organized. And by different components I mean layouts, "page views", containers, reusable component and all the feature-specific components.
Instead of having a unique `components` folder where everything is thrown there, we could have some root folders for common components like layouts, top-level components and reusable components.
Then, under a `routes` or `features` or whatever folder we could have feature-specific components and styles whose parent folder match a specific route for example.

I personally like how [this starter kit](https://github.com/davezuko/react-redux-starter-kit#application-structure) has organized the project. Except that they also have some redux specific files along with the component which I don't like.

The problem is that in order to include "local" styles for a component, the template should include some kind of inline or local styling solution like Radium, PostCSS, CSS Modules, etc. And this is where the React community haven't really come into consensus. 
I like the idea of CSS Modules, giving you the ability to include styles that are only local to a specific component and so you store the style next to the component.

A potential structure for the `ClientApp` folder could be:

```
ClientApp
├── components              # Presentational Components
|   └── NavMenu.tsx         # Reusable presentational component
├── containers              # Top Level Container Components
|   └── AppContainer.tsx    # We could extract the JSX that generates the top level <Provider> container here from the boot files. Although not sure if it's easy to make it work with both client and server side bootstrap.
├── layouts                 # Components that dictate major page structure
|   └── Layout.tsx          # Main layout 
├── stores                  # Redux related code (same as now)
├── styles                  # Global styles
└── routes                  # This is where the fractal structure starts
    ├── Home
    |   ├── assets          # Local assets used in the Home component
    |   └── Home.css        # Local styles for the Home component
    |   └── Home.tsx        # Home component
    ├── Counter             # Idem Home
    └── FetchData           # Idem Home
```

I'm just suggesting a simple re-structure of the templates so they can be used for projects that are know they're going to be big without the need of doing refactoring in the middle of the dev process.

**Comment by SteveSandersonMS** [comment]
This is cool, and I appreciate that large projects are likely to proceed along these lines.

My reservation is that Redux is already exceptionally intimidating and unfamiliar for most web devs, and the only way that people will even look at it is if all additional complexity is minimised or removed. I would favour slimming down the existing React+Redux template rather than expanding it with more subtleties that will raise more questions (e.g., "what's a route versus a container or a component or a layout?").

Having specific distinctions between item types (components, containers, layouts) doesn't help with your wish to group by feature area. In fact it's the opposite, as a feature area is likely to include items from each of these categories.

So, while I appreciate that developers who go deep into React+Redux will want to come up with some more detailed arrangement for their projects, I don't think it's the ReactReduxSpa template's role to define one true arrangement, and I'm really keen to avoid expanding the concept count as it's too much for many devs already.

Would you be OK if we kept it as-is? Please reopen if you think it's important we should change something here.
