### ISSUE TITLE
dotnet react template & office fabric UI - Invariant Violation: addComponentAsRefTo(...)

### ISSUE THREAD

**Issue by vaalgrind** [aspnet/JavaScriptServices#1530]
Hello everyone, 
when I try use office fabric ui in my project and import component for example panel I have this error https://i.stack.imgur.com/YofNd.png. I also recorded this behavior https://giphy.com/gifs/3ohjV6gZTxE8TiqVfa 

Steps:
1. I created project by *dotnet new react*
2. I install office by *npm --save install office-ui-fabric-react*
3. I import Fabric component to boot.tsx and I use it.
4. I import Panel component to Layout.tsx and I use it.
When I clicked button to activate, in console appear error Exception in *Layer.componentDidUpdate(): Invariant Violation: addComponentAsRefTo(...): Only a ReactOwner can have refs. You might be adding a ref to a component that was not created inside a component's `render` method, or you have multiple copies of React loaded*

I put my code on repo https://bitbucket.org/vaalgrindalone/dotnet-react-template-office-fabric-ui-issue/src
I try make alias react in webpack by resolve.alias but nothing happen. I also try put react to external and import it from cdn in html file, bo this is not good solution. I think that my configuration is incorrect. 
Cheers.

**Comment by MikeMatejko** [comment]
+1 same issue here

**Comment by SteveSandersonMS** [comment]
Since this is a client-side problem about the usage of a package not in this repo, it's not something we can control. It sound like you're not using those React components correctly, but that's outside the scope of this repo and this issue tracker. Can you please report your issue to whoever provides the specific React components you're having trouble with?

Note that, if it is a matter of Webpack config, you'll probably find things easier with our newer create-react-app-based template, because that pretty much eliminates any possibility of a custom webpack config interfering with anything: https://docs.microsoft.com/en-us/aspnet/core/spa/react?tabs=visual-studio
