### ISSUE TITLE
Angular-CLI (RC2) Template - Websocket connection failed

### ISSUE THREAD

**Issue by Shamshiel** [aspnet/JavaScriptServices#1531]
I get the following error in the browser using the new Angular-CLI template:

![grafik](https://user-images.githubusercontent.com/13088318/36107427-4817e95c-101a-11e8-83c4-40c43d5c23cd.png)

The only thing that I changed was deleting the content of the ClientApp folder and replacing it with a standard angular cli template. (I'm getting the same error if I use the default template.)

**Comment by SteveSandersonMS** [comment]
Can you provide more info on how to reproduce this? It doesn't happen by default (at least not for me or the vast majority of people, otherwise there would be a huge number of reports of this). I can only guess there's something unusual about your dev machine setup.

If you can provide repro steps that reproduce the issue on a clean dev machine, please let us know.

It's *possible* your issue might be related to #1543 if you're running on `net461`, though that surfaces as a 500 response error, rather than the 400 response error in your screenshot. If it is related to this it will be fixed in the next update, but I still don't know why you'd be getting a 400 instead of a 500.

I'll close this until we have repro steps. Hope that's OK.
