### ISSUE TITLE
ConditionalProxyMiddleware throws when publicPath is absolute

### ISSUE THREAD

**Issue by tobiasr** [aspnet/JavaScriptServices#156]
When setting the { output:  { publicPath: 'http://localhost:5000" }} in webpack.config it results in:

`
System.ArgumentException: The path in 'value' must start with '/'.
Parameter name: value
   at Microsoft.AspNetCore.Http.PathString..ctor(String value)
   at Microsoft.AspNetCore.Http.PathString.op_Implicit(String s)
   at Microsoft.AspNetCore.SpaServices.Webpack.ConditionalProxyMiddleware.<Invoke>d__5.MoveNext()
`

This is needed as a workaround to gets custom fonts working in dev-environment. See: http://stackoverflow.com/questions/34133808/webpack-ots-parsing-error-loading-fonts/34133809#34133809

**Comment by SteveSandersonMS** [comment]
It seems pretty dubious to hard-code `localhost:5000` into your `webpack.config.js`, but I understand this is to workaround an issue in `file-loader`.

I'd be happy to take a pull request that implements this. I'd recommend you modify `WebpackDevMiddleware.ts` so that, when it passes the `PublicPath` value to .NET (after the comment `// Tell the ASP.NET app what addresses we're listening on, so that it can proxy requests here`), it first converts the URL to a root-relative one (if it was an absolute one).

I'll close this so you can submit a separate pull request if you want to.
