### ISSUE TITLE
npm package management features in VS 2017 w/ Angular project template

### ISSUE THREAD

**Issue by jitterbox** [aspnet/JavaScriptServices#1576]
The newly released Angular project template (2.0) doesn't seem to support the built-in npm package management features within Visual Studio (like manually restoring all packages) - there's no **npm** node under Dependencies as there is for Analyzers, NuGet and SDK.  Is this because it's actually a .NET Core C# project type, or is it due to another reason?  Is there any way to enable the built-in npm package management features for a project created with this template?

**Comment by SteveSandersonMS** [comment]
It's because `node_modules` is within the `ClientApp` directory instead of being at the project root. This is necessary to make Angular CLI work correctly (it's hard-coded to expect `node_modules` to be peer-level with your `.angular-cli.json`, etc.).

We've discussed with the VS team adding support for `node_modules` in subdirectories, so hopefully that will be added in a future VS update.
