### ISSUE TITLE
How do Angular create templates using the I command?

### ISSUE THREAD

**Issue by Eilon** [aspnet/JavaScriptServices#1582]
_From @laoshangwei on January 11, 2018 9:54_

PS E:\Project\NiceAdmin\CoreAdmin\clientapp> ng g c User
Unable to find any apps in `.angular-cli.json`.

_Copied from original issue: dotnet/core#1210_

**Comment by Eilon** [comment]
_From @Petermarcu on January 14, 2018 20:41_

This one needs to get moved to aspnet/home. I will likely make a pass a copy things over there unless the issue opener wants to move it themselves.

**Comment by Eilon** [comment]
_From @Petermarcu on March 16, 2018 4:24_

@Eilon

**Comment by SteveSandersonMS** [comment]
I'm not sure what's going on in the original report, because `.angular-cli.json` certainly *does* contain apps in the default project template output, and `ng g` does work with it.

The fact that the casing has changed in the directory name (from `ClientApp` to `clientapp`) also makes me suspicious that the structure has been modified in nontypical ways.

If someone is able to post a repro case I'd definitely be happy to take a look, but until then there isn't much we can do with this report. @laoshangwei, do you have repro steps?

I'll close this until we have repro steps, at which point it could be reopened. Hope that's OK!
