### ISSUE TITLE
Bootstrap repeted

### ISSUE THREAD

**Issue by huggoAF** [aspnet/JavaScriptServices#1589]
I don´t understand why bootstrap is repeted into imports in boot.browser.ts and webpack.config.vendor into secction nonTreeShakableModules. what´s the difference? All this in Angular Template . Thanks for you help

**Comment by SteveSandersonMS** [comment]
It has to be included in `boot.browser.ts` to cause it to get loaded when the page starts. It also gets mentioned in `webpack.config.vendor.js` so that it's compiled into the vendor bundle rather than the regular "main" bundle. It doesn't mean you're shipping two copies of it to the browser - it's only included in the vendor bundle.
