### ISSUE TITLE
With debugger attached WaitForAngularCliServerToAcceptRequests never returns

### ISSUE THREAD

**Issue by martinstenhoff** [aspnet/JavaScriptServices#1611]
When launching an angular spa project, created from the aspnet core 2.1.0 preview2 templates, from Visual Studio 2017 15.7.p3 using F5 (either using iisExpress or Kestrel) the `await client.SendAsync` call below consistently takes longer than the allowed 1 second on my machine (Dell XPS 9550 i7) causing this method to never return.
https://github.com/aspnet/JavaScriptServices/blob/7f550fb4698eba34fc234b4ece7630d8efde73cb/src/Microsoft.AspNetCore.SpaServices.Extensions/AngularCli/AngularCliMiddleware.cs#L110-L123

I've put a System.Diagnostics.Stopwatch around it (after increasing the timeout to 10s) and I never saw it take less than 1.3s (usually it was between 2 - 3.5 seconds).

Perhaps this is also related to #1588 where we're slowed down by having to resolve localhost.
I don't see this with VS 15.6 and AspNet Core 2.0 (I haven't yet tested VS 15.7.p3 with AspNetCore 2.0)

**Comment by SteveSandersonMS** [comment]
Thanks @martinstenhoff for reporting this, and for the detailed information about the underlying cause!

I've applied a fix which should ship in 2.1.

BTW I *don't* think this is the same as #1588 (which BTW is also separately resolved now), because #1588 deals with requests from .NET code to Node via NodeServices. The issue you've encountered here is to do with requests from .NET code to Angular CLI via direct HTTP, so the fix for #1588 would not have any influence on this. The underlying cause might be related, but fix would have to be different.
