### ISSUE TITLE
Question: Older template with webpack vs newer template with angular-cli

### ISSUE THREAD

**Issue by Vx2gas** [aspnet/JavaScriptServices#1633]
@SteveSandersonMS I would love some direction and feedback on the templating.  It was first here and the one published currently that used the webpack middleware, and has a webpack.config.js and the webpack vendor files.

However, it seems there is a newer one [https://github.com/aspnet/templating/tree/dev/src/Microsoft.DotNet.Web.Spa.ProjectTemplates/content/Angular-CSharp](url) that uses the angular-cli.

Going forward, what are the pros and cons of using the angular-cli middleware template vs the webpack middleware template?

Thanks!  and btw.. looking good on Blazor!

**Comment by SteveSandersonMS** [comment]
The newer SPA templates (based on Angular CLI and create-react-app) entirely replace the older ones. We've moved to the new structure because of so many customer requests saying it's preferable to work within the de-facto standard project structure and build system for their chosen client-side SPA framework.

We continue to support the underlying .NET packages used by the earlier templates, so anyone who's already working on an app created from that template should have no reason to change. They are not deprecated - they are still part of the shipping product. But if creating a new project we recommend using the new templates because it produces a structure that most developers prefer.
