### ISSUE TITLE
Question: How do I pass dynamic data to the Create React App-based template?

### ISSUE THREAD

**Issue by robfe** [aspnet/JavaScriptServices#1634]
I'd like to pass a few environment-specific configuration variables to my client code (access keys to 3rd party services like raygun and auth0). 

What's the best way to get these to the client? Ideally they'd be available on load, i'm looking for alternatives to making an AJAX API call to get these from the server.

I'm basically looking for https://github.com/aspnet/Docs/blob/master/aspnetcore/client-side/spa-services.md#the-asp-prerender-data-tag-helper, but working with the index.html file from CRA instead

I am not currently using server-side rendering.

I'm also interested to know if the CRA serviceworker has any implications on the solution here.

I've seen how CRA can make env variables from build available https://github.com/facebook/create-react-app/blob/v0.2.3/template/README.md#adding-custom-environment-variables - but can't tell how to get SPAServices to provide these, or if that's a good idea

**Comment by DanHarman** [comment]
Did you get anywhere on this? Presumably it didn't just work by setting the env variable? I had though the new template just ran node for the ui side so had hoped it would just work.

**Comment by orionstudt** [comment]
Is there a reason you don't just want to use the `asp-prerender-data` tag? I'm React/Redux and I just put my client settings into that tag then have Redux load the store with the settings on client startup.

**Comment by SteveSandersonMS** [comment]
> I've seen how CRA can make env variables from build available

That technique will work fine with an ASP.NET Core project, but I'm not sure it's really what you want, since it will be evaluating the env vars at build time, not at runtime.

In general, CRA produces projects where the client app is truly separate from the server. As such its intended architecture is to have the client make HTTP requests to the server for any runtime data that it needs. I'm not aware of a simple way to have it get dynamic data in the initial `index.html` page.

A complex way to achieve that would be to write custom ASP.NET Core middleware that intercepts the request for the `index.html` page and modifies the response dynamically. However this will be hard to implement robustly and is not something I'd recommend. If you can at all manage it, it's far easier to make the client do an HTTP request to the server for any runtime data it needs.
