### ISSUE TITLE
Angular CLI + .Net Core 2.1 + Service Worker?

### ISSUE THREAD

**Issue by Ro3A** [aspnet/JavaScriptServices#1648]
I'm struggling to configure a service worker in my Angular CLI 1.6 project that is hosted from within a .Net Core 2.1 project. Currently, I hit F5 to run the project, webpack does it's thing, and the site is served up. 

I've tried following various walk-throughs for added a service worker to my project. The process breaks down when I attempt to run ng build --prod. I get the following error:

Error: ENOENT: no such file or directory, scandir '[localPath]\ClientApp\src\app\dist'

Without getting further into the various errors, I'm hoping someone can give me guidance in regards to how I should even be going about this. Should I be following the Angular CLI walkthroughs? Or Should I be using the .Net Core 2.x WebEssentials route as outlined here:

https://madskristensen.net/blog/progressive-web-apps-made-easy-with-aspnet-core/

**Comment by SteveSandersonMS** [comment]
In general, anything that works with Angular CLI should work with the Angular CLI-based template, since inside the `ClientApp` subdirectory, it literally is an Angular CLI application.

Considering your error message, it's possible that the tutorial you're following makes an assumption about where the output files are being put. You might need to update their instructions, or run the scripts they suggest from a different directory. Your dist directory is probably inside `ClientApp`, not `ClientApp\src\app`. In general, the `ng` scripts should be run from the root of `ClientApp`.
