### ISSUE TITLE
InvokeAsync<object> fails for string parameters and result

### ISSUE THREAD

**Issue by samcov** [aspnet/JavaScriptServices#1651]
If I do something simple like:
object[] obj = new object[] { 10, 3 };
var ret = await _nodeServices.InvokeAsync<**object**>("./NodeScripts/Add.js", obj);

Where Add.js simply adds two numbers together, it works without issue, however if I do this,
object[] obj = new object[] { 10+"", 3+"" };
var ret = await _nodeServices.InvokeAsync<**object**>("./NodeScripts/Add.js", obj);

It fails complaining about a non-json string, but if I do this, it works properly
object[] obj = new object[] { 10 + "", 3 + "" };
var ret = await _nodeServices.InvokeAsync<**string**>("./NodeScripts/Add.js", obj);

It works properly. I would assume that using type object would cover anything, but it doesn't appear to work. I'm not sure what's going on, and I don't want to have to figure out types on the fly.

**Comment by SteveSandersonMS** [comment]
The generic parameter specifies what .NET type you want to deserialize the result into. If you specify `object`, that will not produce a useful result because it doesn't hold any data that you can work with. At best you'd get an empty object.

You need to specify a type that matches the return value well enough to JSON-deserialize the response into.

**Comment by samcov** [comment]
I found that specifying a type, which includes the single field of object,  allows me to use type object to return either a string or an int. **I should have posted that, but I got busy**.

It's still a bit confusing that type string, which is of type object fails and int works, but the solution to the problem is a trivial one, and works better for me anyway, so... moving on.
