### ISSUE TITLE
Production Publish with Angular V2 Template - TS errors

### ISSUE THREAD

**Issue by aherrick** [aspnet/JavaScriptServices#1655]
I have a new Angular V2 template project. 

I'm receiving errors when publishing Production. I'm just simply trying to publish to a folder in VS2017.

```
Error	TS2693	(TS) 'Promise' only refers to a type, but is being used as a value here.
Error	TS2304	(TS) Cannot find name 'Map'.
Error	TS2339	(TS) Property 'from' does not exist on type 'ArrayConstructor'.
```
I see people talking about updating `tsconfig.json` however I'm not seeing that make any difference. 

Below is my updated `tsconfig.json`

What do I need to do here?

```
{
  "compileOnSave": false,
  "compilerOptions": {
    "outDir": "./dist/out-tsc",
    "sourceMap": true,
    "declaration": false,
    "moduleResolution": "node",
    "emitDecoratorMetadata": true,
    "experimentalDecorators": true,
    "target": "es5",
    "typeRoots": [
      "node_modules/@types"
    ],
    "lib": [ "es2017", "es5", "es6", "dom" ]
  },
  "exclude": [ "bin", "node_modules" ]
}
```
![2018-05-23_10-25-51](https://user-images.githubusercontent.com/586671/40430695-b2c06660-5e73-11e8-90da-299e00c008bb.png)

**Comment by SteveSandersonMS** [comment]
Can you provide repro steps, specifying which version(s) of `dotnet`, VS, aspnet, etc. you're using?

These kinds of issues are virtually always because TypeScript's type checking has become stricter over time (and/or the type definitions your project is using are newer and more precise than what your version of the TypeScript compiler understands). If you're not on the latest version of everything, there can be inconsistency in the rules that are being applied.

**Comment by aherrick** [comment]
Hi Steve thanks for the follow up.

I no longer am receiving these errors. My updated `tsconfig.json` looks like the following:

```
{
  "compileOnSave": false,
  "compilerOptions": {
    "outDir": "./dist/out-tsc",
    "sourceMap": true,
    "declaration": false,
    "moduleResolution": "node",
    "emitDecoratorMetadata": true,
    "experimentalDecorators": true,
    "target": "es5",
    "typeRoots": [
      "node_modules/@types"
    ],

    "lib": [ "es6", "dom" ]
  },
  "include": [
    "src/**/*"
  ],
  "exclude": [ "node_modules" ]
}
```
