### ISSUE TITLE
Prerender static index.html

### ISSUE THREAD

**Issue by nitro52** [aspnet/JavaScriptServices#171]
Is it possible to use prerender on static .html files? eveything i have seen so far seems to trigger it from an ASP.net view. 

We currently serve up several angular apps that are managed via bower. So they will be mapping asp.net mvc routes to specific index.html files. 

i was thinking that there should be a way to do this through asp.net middle ware?

**Comment by SteveSandersonMS** [comment]
> Is it possible to use prerender on static .html files? eveything i have seen so far seems to trigger it from an ASP.net view. 

Currently all the templates and samples do work by injecting prerendered content into a Razor view's output. I'm guessing you want one of these two alternatives:

 1. At build time, emitting static `.html` files to disk, containing the rendered SPA's HTML output. When loaded into visitors' browsers, it will be entirely static, non-interactive content.
 2. Or, your goal is to use prerendering at runtime to produce entire HTML documents, not involving Razor at all

If your requirement is (2), then that's something that others have requested too (see #182). We may implement something like that soon, or perhaps someone in the community will do so.

If your requirement is (1), then that's pretty unusual and hasn't been requested by anyone else. It would certainly be possible to do it by writing some custom code to invoke the prerendering APIs on your dev machines (e.g., from a command-line tool) and writing the output to disk. We don't have any plans to bake such a feature into the templates because it would be a very unusual use case and nobody else has asked for it. But I'm sure you could figure out a way if it's important to your project.

**Comment by SteveSandersonMS** [comment]
BTW if I'm misinterpreting your requirement, please re-open and clarify what you're looking for that might be different from the two options I've mentioned above :)

**Comment by nitro52** [comment]
@SteveSandersonMS its more along the lines of number 2. We have static html files for our angular apps that we serve up with asp.net but not via razor. we would use ASP.net more for a backend web api and server site routing. 

so i would imagine you would have some sort of middle ware for the routes that would use prerender on the way out.
