### ISSUE TITLE
Cool concept

### ISSUE THREAD

**Issue by fastboxster** [aspnet/JavaScriptServices#173]
I think a gallery would be cool where anyone could post both startup templates and full working reference or blueprint applications. We could vote on them and there could be an indicator of moderator or officially "supported" versions (which would mean some level of testing has happened as a post build step of the various frameworks).

**Comment by wangkanai** [comment]
+1

**Comment by SteveSandersonMS** [comment]
That's a very cool idea. If you or anyone else is interested in building such a gallery then I can definitely talk to people inside MS about ways we could promote and feature it.

We are in the process of working out ways that community-published templates can be integrated into our existing tooling (VS and command line) but I don't think anything definite has been decided and confirmed yet.

For tidiness, I'll mark this issue as closed because it's not something we're going to be able to dedicate resources to any time soon, but if community members choose to produce a site like this, I'd be very interested to hear. Thanks!
