### ISSUE TITLE
Webpack's publicPath isn't used

### ISSUE THREAD

**Issue by Tragetaschen** [aspnet/JavaScriptServices#176]
I'm using the html-loader for my angular 2 templates and that replaces for example `<img src>` paths with their server path. When I'm running my app in the browser, the publicPath is correctly used as expected. When running on the server, there is no publicPath at all (`__webpack_require__.p` seems to be the empty string / null / undefined).
That means, my browser renders `<img src="/dist/9a08c41631a395a808e4d9d7b7b68d63.jpg"/>`, the server just renders `<img src="9a08c41631a395a808e4d9d7b7b68d63.jpg"/>`.

**Comment by SteveSandersonMS** [comment]
Thanks for reporting this. The issue was that the `aspnet-webpack` module overrode the `output` section of your config when performing in-memory compilation, which meant it didn't pass through your `path` or `publicPath` values into the compiler.

I've just published an updated `aspnet-webpack` NPM module - the new version number is 1.0.6. If you update to this version, hopefully you'll find things start working as expected.

**Comment by Tragetaschen** [comment]
Indeed, they do. Thanks!
