### ISSUE TITLE
Hot Module Replacement Not Working...

### ISSUE THREAD

**Issue by lmaslanka** [aspnet/JavaScriptServices#178]
When I build and run the out of the box app and make a change the console window prints "Node will restart because file changed: C:\Projects\test\ClientApp\components\counter\counter.component.html". That is it nothing else happens and the application is not updated. The strange issue is that if I refresh the browser the change will pop in and revert back to the original state like webpack did its job but dotnet is stuck with the original result. Even when I stop the server and start it again and refresh the page it does the same thing.

This issue might be specific to my machine but I am posting it here to make sure I am the only one experiencing it.

I am using the Angular2 template. But I confirmed the same behaviour for the React template as well.

**Comment by pehu71** [comment]
@lmaslanka : I can just confirm, behaves pretty same on my box, even though I do not use webpack - I use SystemJS and I don't even have the `module.hot()` lines in my cleint boot code. It happens when I have the ASP NET CORE server running in console and I change any file in my editor. It reports that it is restarting, but in fact it is not. So I guess it has nothing to do with webpack, because I don't use use it in my  app.

**Comment by anwalkers** [comment]
I found it to work from with the VS code debugger but not from the command line. I think it has to do with the ASPNETCORE_ENVIRONMENT not being set... I am running on Windows 10

**Comment by anwalkers** [comment]
That was it... In PowerShell you can do this and everyone is happy.

`$env:ASPNETCORE_ENVIRONMENT = "Development"`

**Comment by lmaslanka** [comment]
@anwalkers That fixes the issue, I just tested it and it works great. Thank you!
