### ISSUE TITLE
Use of cluster module in Node? 

### ISSUE THREAD

**Issue by andersekdahl** [aspnet/JavaScriptServices#19]
Hi! 
I'm  curious about the strategy to keep performance high.  Will you be using the cluster module in Node, or will you be creating multiple Node processes in C#?

**Comment by SteveSandersonMS** [comment]
Good question. I'll be interested to see what requirements people say they have, or at least what the mainstream use cases are.

As it stands, there are as many Node processes as there are .NET processes. At scale where you deploy your ASP.NET app across many servers, you'll automatically be spreading your Node load over as many processes.

You would want > 1 Node process per .NET process if there's some nontrivial blocking work going on when you call from .NET to Node. Arguably this is a bad situation to get into (either rework your Node code to be less blocking, or call it less often, e.g., using ASP.NET output caching).

However I recognise there may be some cases where you have extreme load on a single .NET process, and the .NET side of your app handles that fine, but the sheer number of calls into a single Node process adds up to something expensive, even though individual calls are nonblocking. In this case there would be an argument for distributing load over multiple Node processes.

Your idea of using the cluster module sounds promising.

**Comment by andersekdahl** [comment]
Sure, there will be one Node process per .NET process, but using more than one .NET process (Web Garden in IIS speak) is quite uncommon and it's even something many advice against using.

If you plan on using Edge.js to talk to Node.js you won't be able to use the cluster module. The only way to scale with Edge.js is to add more processes or machines.

But if it's fast enough to communicate between processes (real Node.js process and .NET process) the cluster modules is a good fit.

**Comment by SteveSandersonMS** [comment]
Since we've changed to the `boot-server.ts` pattern in all the templates (as opposed to the earlier system where the server-side boot logic was hard-coded in the NuGet packages), developers can now control this manually if they want.

As for making it a built-in feature, we probably don't need that any time soon, based on the fact that nobody else has requested it in the last 6 months. If someone does want it, and it becomes a common request, it would be great if they first prototyped it by implementing whatever's needed in their `boot-server.ts`, and then we could consider whether to make it a default.
