### ISSUE TITLE
Roadmap

### ISSUE THREAD

**Issue by doczoidberg** [aspnet/JavaScriptServices#192]
Is there any plan or roadmap?

I would like to know when Angular RC4 and Router Beta 2 will be supported?

**Comment by SteveSandersonMS** [comment]
Hi there! There isn't a predetermined roadmap with known dates for implementing specific things, but the specific items you mention are likely to be done in the next few weeks. If you're keen to have it in sooner, we'd definitely take a pull request for that feature, since it's definitely something that has to happen at some point.
