### ISSUE TITLE
[Question] Prerendered page is re-rendering on client

### ISSUE THREAD

**Issue by leocosta** [aspnet/JavaScriptServices#212]
Hi!

I just started a project using the Angular2Spa template.

I have been having some trouble when the prerenderer module is enabled.
In the first hit, when a page is prerendered on server and displayed on browser, shortly thereafter  the page is rendered again on client (and jumps to the top of the page each first time a route is loaded). 

One thing I noticed is that when the script file "~/dist/main.js" is removed of Index.cshtml, the problem does not happen anymore.

Any idea what it is?

Thanks!

**Comment by SteveSandersonMS** [comment]
This is a limitation of Angular 2's server-side rendering support. As far as I'm aware, you'll see the same phenomenon with every other Angular 2 server-side rendering starter kit, because it doesn't have a way to attach to an existing rendered DOM structure - it can only replace it.

It is possible that the Angular 2 folks have managed to improve on this recently (though I haven't heard of it). You might want to get in touch with [the angular2-universal project](https://github.com/angular/universal) and see if their libraries have any way of attaching to an existing rendered DOM structure.

Note that the React server-side rendering doesn't work this way - it attaches to the existing DOM elements without replacing them.

**Comment by SteveSandersonMS** [comment]
> One thing I noticed is that when the script file "~/dist/main.js" is removed of Index.cshtml, the problem does not happen anymore.

I expect that, by doing that, you're just disabling the client-side app completely, so all you're left with is server-side rendering.

**Comment by leocosta** [comment]
Thank you :)

**Comment by MarkPieszak** [comment]
@leocosta This is how Universal and SSR rendering have to work. The gist of what's happening behind the scenes is that we're turning the Angular2 application into a DOM like structure (using parse5), handling any XHR you're doing etc, and passing this entire String (essentially) to the client. After that there is a Gap period of time, where preboot is recording events (clicks typing etc) to be able to replay them in the event the user does something and they need to be fired off again once the Client officially bootstraps . ( This is that second bootstrap you're noticing) it needs to occur otherwise it wouldn't be able to be a SPA like normal :)

Hope that helps explain things!
