### ISSUE TITLE
Could thoses feature have support for Angular ~1.5 ?

### ISSUE THREAD

**Issue by alexsandro-xpt** [aspnet/JavaScriptServices#213]
With Typescript or not, could `JavaScriptServices`, `Microsoft.AspNetCore.SpaServices`, `Microsoft.AspNetCore.AngularServices` and cia have support for Angular 1.5 with Webpack?

**Comment by SteveSandersonMS** [comment]
Certainly. The only thing that's specific to Angular 2 is server-side rendering.

If you set up an Angular 1.5 project that builds via Webpack, you could definitely use the Webpack facilities from the JavaScriptServices packages with it.

**Comment by asadsahi** [comment]
@SteveSanderson, trying to get the HMR working in Angular 1.5 project, but it isn't doing full reload or HMR.

Also, saw some [comments](https://github.com/angular/angular.js/issues/11904) from Pete (Angular 1 team lead) that angular 1 cannot fully work with webpack HMR because of its architecture.

So to what level we can get Angular 1.5 working with webpack/HMR features. I have this repo [here ](https://github.com/asadsahi/AspNetCoreAngularWebpack)which tries to do the HMR, but fails with error that app cannot be bootstrapped twice.

**Comment by SteveSandersonMS** [comment]
OK, thanks for letting us know!
