### ISSUE TITLE
Passing session data (or any data) from Node.js to .NET Core in prerender

### ISSUE THREAD

**Issue by mgroger** [aspnet/JavaScriptServices#221]
I see that in the prerender the JS script returns html and globals in JSON to .NET Core, which then adds that content to the appropriate spots in the HTML template. 

I'm trying to understand if there's any way to use any of that returned data in .NET Core directly instead of just outputting to HTML.

My specific example: I'd like to use some of the returned data to set a client cookie with session data. I want to call a different backend in my SPA that currently uses sessions for authentication. If I set a cookie with the session ID for this different backend, then if the user reloads the prerender can use the cookie to pass the same session ID on to the other server for requests.

Perhaps this will make more sense with an example:

1. First Request - Render on server, call login or whatever other page is requested. Return session token(s) as part of each response from server, represents current session.
  * Session token is saved in prerendered globals for use by client, goes to Redux store to be used in subsequent requests.
  * ALSO set session information in cookie, sent back to client. How would this session information get from Node.js to .NET Core to be set as cookie on prerender server? This is where I'm getting stuck.
2. Client side can then pass the same session ID when calling backend.
3. When rendering on server again, check for session ID saved in cookie, pass if exists.

Thanks!

**Comment by SteveSandersonMS** [comment]
Hi there. This is certainly possible, but since the existing `asp-prerender-module` tag helper doesn't give you any way to specify some .NET code that should be called with the prerender output (it just adds it to the Razor output directly), you'll at least need to drop down one level in the abstraction chain and call the underlying `Prerender` APIs directly.

If you have a look at the `PrerenderResult` sample ([implementation here](https://github.com/aspnet/JavaScriptServices/tree/dev/samples/misc/Webpack/ActionResults) and [usage here](https://github.com/aspnet/JavaScriptServices/blob/dev/samples/misc/Webpack/Controllers/FullPagePrerenderingController.cs)), you'll see an example of how your .NET code can directly invoke the prerendering code and get back the result.

You could use this approach directly in one of your action methods to get back the [`RenderToStringResult`](https://github.com/aspnet/JavaScriptServices/blob/dev/src/Microsoft.AspNetCore.SpaServices/Prerendering/RenderToStringResult.cs), which includes both the `Html` string plus an arbitrary `JObject` property called `Globals` in which you could embed whatever information you want to feed back into .NET. You don't have to emit the contents of `Globals` to the client like the default prerendering tag helper does (or you could just emit a subset, or whatever you need). If you wanted, you could even encapsulate your code that does this as either an ActionResult or tag helper.

If you needs are even more customised than this (or, for example, you don't want just `Html` and `Globals`, but rather want some other combination of properties to come back from your Node code), then you could go deeper still and use the underlying `InvokeAsync` API directly ([docs here](https://github.com/aspnet/JavaScriptServices/tree/dev/src/Microsoft.AspNetCore.NodeServices#simple-usage-example)).

Do you think one of these options would meet your needs?

Closing because I hope this covers it, but please reopen with details if you think we should add or change anything in JavaScriptServices!

**Comment by mgroger** [comment]
Great, thank you! 

I'm new to .NET but I was able to copy PrerenderTagHelper and customize it to give special treatment to some of the properties coming back in `Globals`. 

Initially, I tried to change RenderToStringResult, etc to return another property in addition to Html and Globals for some reason the new property was always null even though there were no errors. However, returning the properties as part of the Globals works fine and I actually think this method is cleaner for me since PrerenderTagHelper can still use the rest of the built-in Prerendering components.

Again, thanks for your help.
