### ISSUE TITLE
[Question] Does node_modules need to be in publish folder?

### ISSUE THREAD

**Issue by cbuffevant** [aspnet/JavaScriptServices#233]
I'm starting to play with Angular2 template... and after a dotnet publish, I see a node_modules folder under netcoreapp1.0/publish.

Shouldn't all those modules be in the bundle created by webpack?

**Comment by baseless** [comment]
Havent thought of that but it would be interesting to know why node_modules are included in publishOptions.

**Comment by MarkPieszak** [comment]
Good point, they should simply be `npm install`'d on the production environment.

**Comment by baseless** [comment]
As to why the libs in node_module are needed it seems to be required for the aspnet-prerender functionality as i can see. Mark, if possible (for example can this be scripted in azure?) i agree with that, at the current time it is enforced during prebublish (in project.json).

**Comment by MarkPieszak** [comment]
When looking at this (https://azure.microsoft.com/en-us/documentation/articles/nodejs-use-node-modules-azure-apps/) it looks like `node_modules` "can" be part of the deployment script, or it can be removed and you can do an `npm install` in Azure.

I believe Azure should run it automatically, and you can manually run it again somewhere (it's been a while)

> The package.json file is a way to specify the top level dependencies your application requires so that the hosting platform can install the dependencies, rather than requiring you to include the node_packages folder as part of the deployment. After the application has been deployed, the npm install command is used to parse the package.json file and install all the dependencies listed.

**Comment by baseless** [comment]
Nice will check that out! As far as azure running npm install automatically i just got an exception when i published demoapp based on aspnetcore-spa template / seed before to azure with node_modules excluded.

**Comment by SteveSandersonMS** [comment]
@baseless `node_modules` is needed for many things, not only prerendering. If you're running any code inside Node (which essentially everything in this repo does), then you will pretty much certainly have NPM dependencies that are needed at runtime.

As for whether you need to include `node_modules` in your deployed package, that depends on your deployment mechanism:

 * If you deploy using a mechanism that automatically restores NPM dependencies (such as Azure's Kudu mechanism, a.k.a., deploy from a Git repo), then everything's great. `node_modules` is not committed into your Git repo so you are of course not shipping it to the production server yourself, but that's fine because you don't need to - the server will auto-restore your NPM dependencies. You did mention that you're targeting Azure, so I'd definitely recommend this deployment approach.
 * If you deploy using an approach that just sends directories directly from your local disk (e.g., the Visual Studio 'Publish' feature (aka VSTS), or even FTP), then of course you do need to include `node_modules`, because that's the only way the server is going to get those files (it's not going to fetch them by itself, like Kudu does). As you rightly point out, this sort of deployment mechanism is massively slower, which is another reason to prefer Kudu.

Hope that makes sense!

**Comment by baseless** [comment]
@SteveSandersonMS what i meant was for development and server side functionality (pre-rendering, dependencies required / imported in boot-server.ts and so forth). I cannot see why one should publish the entire node_modules for a strictly client-side run app (where all external dependencies where already built and in-place in the vendor.js file **as asked in the original question by @cbuffevant** )? Then again javascriptservices / nodeservices would not be needed in that case either except for perhaps hmr?
