### ISSUE TITLE
Any reason why the yeoman templates deploy so many files to production?

### ISSUE THREAD

**Issue by shawnwildermuth** [aspnet/JavaScriptServices#238]
In the templates for ASP.NET Core (e.g. generator-aspnetcore-spa), the project.json is publishing a *lot* of files:

```
  "publishOptions": {
    "include": [
      "appsettings.json",
      "ClientApp",
      "node_modules",
      "typings",
      "Views",
      "tsconfig.json",
      "tsd.json",
      "web.config",
      "webpack.*.js",
      "wwwroot"
    ]
  },

```

Any reason the webpack files, the tsd.json, the node_modules, typings, and ClientApp are all needed since you're using webpack to package up the files? It seems unnecessary.

**Comment by MarkPieszak** [comment]
Similar issue here as well #233

**Comment by SteveSandersonMS** [comment]
Yes, it's because the server-side rendering works by executing your code directly from the original TypeScript, not from the .js bundle (hence it needs your TypeScript sources and build config).

This is to keep things simpler for the developer. You don't have to worry about the fact that, to run in Node, your TS code has to be compiled with some different compiler settings (the prerendering helper takes care of that), or have to deal with two different build artifacts representing different runtime targets. You just point us to your .ts files and your webpack.config.js and we take care of the rest.

If you really want your server-side rendering to execute pre-built .js (and not .ts), so that you only have to deploy pre-built .js, then you can totally do that. For example, you could add an extra webpack config file (e.g., called `webpack.config.prerendering.js`) which overrides your regular config in all the ways needed to make it run in Node (see the sources for the `aspnet-webpack` NPM package to figure out what), and change the nominated entry point from `boot-client.ts` to `boot-server.ts`). Then you can change your prerendering tag helper to point to the resulting .js file, and don't specify any `asp-prerender-webpack-config` value at all.

I suspect that for most devs, it's going to be a lot more straightforwards as-is, hence the current design. But as mentioned, if you do prefer to prebuild this aspect of it then you can do.

Hope that makes sense!
