### ISSUE TITLE
Add typings/ to .gitignore generated by yo aspnetcore-spa 

### ISSUE THREAD

**Issue by aidansteele** [aspnet/JavaScriptServices#242]
There's not much more to the the issue beyond the title! I'm new to Typescript and it wasn't immediately obvious whether I should gitignore the `typings` directory in a new project. I might have guessed it *shouldn't* be ignored on account of not being in the template .gitignore, but googling suggests it *should* be ignored.

**Comment by SteveSandersonMS** [comment]
You could argue either way:

* It *could* be gitignored, since whenever someone sets up their own working copy, or whenever it gets deployed to a server, you could re-run `tsd install` (e.g., from a script) to re-acquire the `.d.ts` files.
* On the other hand, these files are tiny and there aren't many of them, so there's very little drawback to including them in your repo. Doing so removes one possible point of failure or inconsistency. It's one fewer thing that a developer might get tripped over by when they try to build or run the application.

I tend to prefer having the typings files in the repo (hence not gitignored) because there are definite benefits and no drawbacks that I've experienced.

If anyone has strong reasons for why they should not be in the repo, please speak up! Otherwise I think we're good as-is. Thanks for raising the question @aidansteele!

**Comment by MarkPieszak** [comment]
Both cases are right, technically we don't need them and they could be ignored, but like you said Steve they're small and there's not many so technically there's no foul there either.

All the same to me :)
