### ISSUE TITLE
Hot swap stops working when you enable HTTPS

### ISSUE THREAD

**Issue by glangdonvt** [aspnet/JavaScriptServices#271]
Troubleshooting development mode
Your project worked like a dream.  then I try to modify it to run in HTTPS--first editing the product properties to be HTTPS in Visual Studio, using the recommended https: port number.

Eventually I found this https://github.com/aspnet/Home/issues/1486, added the right extra references into the Startup.cs file, and now I can run https: at whatever port I want, but the hot swap recompilation stopped working.  

I recreated the project from scratch.  As soon as I uncomment the two commented lines below (Startup.cs), web site works fine, but hot module swap stops functioning. 
                .UseKestrel(options =>
                {
                    var serverCertificate = LoadCertificate();
                    //options.UseHttps(serverCertificate);
                })

```
            //.UseUrls("https://localhost:5001")
```

**Comment by MarkPieszak** [comment]
HotModuleReplacement is being ran in http, and you have .net on https. You need to run webpack-Dev-server with --https, but I'm not sure if aspnet-webpack is setup to currently handle that situation. Steve would know best!

**Comment by glangdonvt** [comment]
Thanks, Mark.  This code is using the AspNetCore's UseWebpackDevMiddleware.  When you look at the source code for it, line 17 hard-codes that to http.  Seems like that may be my issue.  Please let me know if you think I should look elsewhere.  Otherwise, I'll submit this issue to that team.

13 namespace Microsoft.AspNetCore.Builder 
14 { 
15     public static class WebpackDevMiddleware 
16     { 
17         private const string WebpackDevMiddlewareScheme = "http"; 
18         private const string WebpackHotMiddlewareEndpoint = "/__webpack_hmr"; 
19         private const string DefaultConfigFile = "webpack.config.js";

**Comment by MarkPieszak** [comment]
Ahh nice catch, didn't have a chance to look last night.
Yes it looks like we need to add a new option to `WebpackDevMiddlewareOptions` for https. Let me give it a test run and see if I can get it all working before putting in a fix.

**Comment by MarkPieszak** [comment]
Should be all set with PR #272

**Comment by glangdonvt** [comment]
Thanks, Mark, I’ll try it out over the weekend.
George

**Comment by SteveSandersonMS** [comment]
This is now fixed. Now, the HMR integration handles `/__webpack_hmr` requests by reverse-proxying them, instead of 302-redirecting, to the underlying Node service. That means it's independent of what scheme/hostname/etc the browser is connecting on, because the browser never sees the Node HMR service directly any more.

To get this fix, upgrade to a newer version of `Microsoft.AspNetCore.SpaServices`. However I haven't yet published this update to NuGet - will do so shortly.

**Comment by SteveSandersonMS** [comment]
Update: The newer Microsoft.AspNetCore.SpaServices (and related packages) is now published to NuGet

**Comment by glangdonvt** [comment]
Thanks!  NOW I'll try it over the weekend.

**Comment by SteveSandersonMS** [comment]
Unfortunately I've had to revert the change that fixed this, because of issues with long-running requests triggering `ECANCELED`/`EPIPE broken` pipe errors.

I've [submitted a repro to the Kestrel repo](https://github.com/aspnet/KestrelHttpServer/issues/1103) and will hopefully put in a better event-stream proxying implementation here once they let me know what (if anything) is the supported way to do this.

**Comment by glangdonvt** [comment]
Thanks for the heads up.

**Comment by boban984** [comment]
Any progress considering this issue?

**Comment by MarkPieszak** [comment]
It looks like core 1.1 will have part of the fix in it when it comes out (if I understood the kestrel thread right). @boban984
