### ISSUE TITLE
OutOfProcessNodeInstance IDispose should WaitForExit

### ISSUE THREAD

**Issue by pauldotknopf** [aspnet/JavaScriptServices#28]
When killing the out of process node instance, we should wait for the process to exit (see [here](https://github.com/aspnet/NodeServices/blob/39f7f16/Microsoft.AspNet.NodeServices/HostingModels/OutOfProcessNodeInstance.cs#L141)).

Otherwise, if you create your own INodeService (`Configuration.CreateNodeServices(NodeHostingModel.Http, _scriptsDirectory.TempDirectory)`), and then call `Dispose()` on the service, there is no telling when I can appropriately delete my temporary directory.

Here is my `Dispose` method in my class that users `INodeServices`

``` c#
public void Dispose()
{
    if (_nodeServices != null)
    {
        _nodeServices.Dispose();
        _nodeServices = null;
        // the node services doesn't "WaitForExit". it should though.
        // this should be enough time for the process to fully exit.
        Thread.Sleep(TimeSpan.FromSeconds(2));
    }

    if(_scriptsDirectory != null)
    {
        _scriptsDirectory.Dispose();
        _scriptsDirectory = null;
    }
}
```

**Comment by SteveSandersonMS** [comment]
If we `WaitForExit`, we probably also need some logic that makes this time out if Node doesn't actually exit after some period. Otherwise it could hang forever.

**Comment by thunder7553** [comment]
I read somewhere (https://github.com/dotnet/roslyn/issues/114) that Dispose should handle long background processes in a separate thread, that's why there is no async and cancellable Disposable. Instead, there should be a an async Close function, that can be awaited (and cancelled). So I propose an "await _nodeService.CloseAsync()" instead of _nodeServices.Dispose(); The async close would kill the node process gracefully. When calling dispose, it would call CloseAsync without waiting for it (e.g.,dispose would "promise" that the resources will be given back to the system).

**Comment by SteveSandersonMS** [comment]
This hasn't been a widely-requested feature, so I'm cautious about implementing anything nontrivial around something as critical as process shutdown management. Adding a `CloseAsync` function is not trivial, because you can actually have multiple `INodeInstance` instances surfaced through a single `INodeServices` instance, and we'd have to deal with dispatching the shutdown request to multiple instances and handling them producing different results. Also we'd need some handling for the case where you call `CloseAsync` and then don't proceed to call `Dispose`.

In your original solution, you just added a `Thread.Sleep(TimeSpan.FromSeconds(2));`, which seems like a reasonable way of covering the requirement. If you need to cope more robustly with a situation where it takes longer to shutdown and is holding locks on files, you could have a retry mechanism that keeps trying every second or so to delete the temporary directory.

Since this doesn't appear to be a widespread requirement, and you already have a solution in your particular case, I'll close this and see whether we can get away without complicating the shutdown process. If more people request this, we can certainly reconsider. Hope that's OK!
