### ISSUE TITLE
Relative path for css files? 

### ISSUE THREAD

**Issue by AndrewKralovec** [aspnet/JavaScriptServices#295]
Sorry to be bugging you guys again, but i was trying to get the path of a local css file, but i cant figure out where the relative paths are located for css files. 

For example 
in folder **_ClientApp/components/app/app.ts_**
`    styleUrls:['./app.css'], `
Erorr 404 can not be found. I tried many different paths but could not get the file to load.  
Thanks !!!

**Comment by SteveSandersonMS** [comment]
If you want to use `styleUrls` so that the client-side code does an HTTP request to fetch the `.css` file, then you'll have to put the `.css` file somewhere that it will get served to the client. If you've put it in your `ClientApp` folder, then it won't get served (the server is not exposing the contents of that directory to the world).

Your options:
 * Put your `.css` file in `wwwroot` and reference it there (e.g., if it's at `wwwroot/mycss/somefile.css`, then you'd want `styleUrls: ['/mycss/somefile.css']`)
 * Or, don't use `styleUrls` at all, but instead use Angular's ability to read inlined style info. See the docs about "scoping styles in Angular 2 components" under [here](get_competitors_for_global_multiplayer_league). Although these docs are about how to do it with LESS, you could remove the LESS compilation step from your webpack setup and do it with plain `.css` files instead.
