### ISSUE TITLE
style-loader as vendor dependency?

### ISSUE THREAD

**Issue by asadsahi** [aspnet/JavaScriptServices#320]
Lack of knowledge perhaps, but anyone knows why we have style-loader in vendor manifest file to create DLL bundle? Shouldn't this file only have 3rd party libraries?

![image](https://cloud.githubusercontent.com/assets/3470892/18629304/a15f23e6-7e5c-11e6-8127-e3e1e3445b08.png)

**Comment by SteveSandersonMS** [comment]
`style-loader` *is* a 3rd-party library, so I'm not sure I understand the question.

If you still think something is wrong, please reopen this issue with details :)

**Comment by asadsahi** [comment]
@SteveSandersonMS As I understand `style-loader` is like any other loader which handles a specific file type. Why we have only specified `style-loader` in vendor manifest?

I have excluded it from vendor to try if it breaks anything, surprisingly it doesn't :)

However removing `style-loader` has also reduce my bundle size:
With style-loader:
                           vendor.js  2.18 MB       0  [emitted]  vendor                                                                                               

Without style-loader:
                           vendor.js  1.77 MB       0  [emitted]  vendor                                                                                               


And application still works. So, I am not sure if we need it, unless I am missing anything.

**Comment by SteveSandersonMS** [comment]
> As I understand style-loader is like any other loader which handles a specific file type.

The difference is that `style-loader` has a runtime portion, so you have to make a choice about where that runtime code should go: in your vendor bundle, or your main bundle.

In the Angular2Spa template right now, `style-loader` is not actually used at all (because of its incompatibility with server-side prerendering), so it can be removed altogether. Thanks for drawing my attention to this! I'm removing it from the default Angular2Spa template now.

However, it is used in the React and Knockout templates, so it will remain referenced from their vendor bundle configs.

**Comment by asadsahi** [comment]
Okay interesting information about style-loader, didn't know there is some element in loader which is used in vendor bundles.

Thanks
