### ISSUE TITLE
[QUESTION] Angular2 template migration to per-component styles

### ISSUE THREAD

**Issue by rbasniak** [aspnet/JavaScriptServices#326]
I saw the last update on Angular2 changed to per-component scoped styles, and completely removed the global styles. 

Doesn't it make sense to have a application wide style like it was before, and also some per-component styles just to exemplify how to do it?

Please correct if I'm wrong, but as it is now, I understand that if I create a global stylesheet it won't be included in the bundle anymore. This way if I have some styles that are used in more than one component, I'll have to duplicate the code...

**Comment by SteveSandersonMS** [comment]
If you do want a global stylesheet, there are various ways to add one, e.g., as documented at https://github.com/aspnet/JavaScriptServices/tree/dev/src/Microsoft.AspNetCore.SpaServices#example-a-simple-webpack-setup-that-builds-less

Or even just by adding a `.css` file to `wwwroot/dist` and then referencing it using a `<link rel=stylesheet>` tag in your layout :)

So yes, you're right, it does make sense. For the template we're just trying to minimise concept count (with additional concepts covered by docs or at least standard practices) rather than putting all features in the out-of-the-box set of files. Hope that makes sense!
