### ISSUE TITLE
Publishing prod

### ISSUE THREAD

**Issue by zigzag95** [aspnet/JavaScriptServices#337]
How to publish my app?

**Comment by SteveSandersonMS** [comment]
It's a regular ASP.NET Core app, so you can use any technique that you'd normally use. If you use a technique like [Kudu to deploy to Azure](https://azure.microsoft.com/en-gb/documentation/articles/web-sites-deploy/), then it will automatically build the client-side resources as part of deployment, because of the `prepublish` scripts in `project.json`.

**Comment by boban984** [comment]
set ASPNETCORE_ENVIRONMENT=Production

webpack --config webpack.config.vendor.js

webpack

Then :  dotnet publish
