### ISSUE TITLE
Question about the new main-server file

### ISSUE THREAD

**Issue by rbasniak** [aspnet/JavaScriptServices#340]
Hi, I just sync with the latest commits and I didn't understand one thing: now the webpack script is publishing main-server.js to the ClientApp folder. 

Now when you publish your application you have all ASP files and folders and in the middle of them you have a ClientApp folder which actually contains server code.

This seems very strange to me. Isn't wwwroot folder more suitable for the compiled TypeScript files?

**Comment by SteveSandersonMS** [comment]
> Now when you publish your application you have all ASP files and folders and in the middle of them you have a ClientApp folder which actually contains server code.

That's a very good point! The naming does now seem a little strange.

I'm wondering if we should therefore rename `ClientApp` to `AngularApp`/`KnockoutApp`/`ReactApp`/etc., since that's literally what it is, and it runs on both server and client.

> Isn't wwwroot folder more suitable for the compiled TypeScript files?

In this case, not really, since `wwwroot` files are served publicly to the whole world, and you wouldn't want to serve your `main-server.js` file to browsers (partly because there's no point, and partly because you probably have source maps enabled, so you'd be exposing your TS source code which not everyone wants to do).

**Comment by SteveSandersonMS** [comment]
I'll close this because, after reflection, it seems like we're already in the right place with this. But it's only a project template and we can always change it in the future if the need becomes clear.
