### ISSUE TITLE
Proxy requests to an external API

### ISSUE THREAD

**Issue by korneel** [aspnet/JavaScriptServices#361]
The webpack dev server can be configured to proxy requests to an external API: https://webpack.github.io/docs/webpack-dev-server.html#proxy

How do I configure a proxy using the webpack dev middleware?

**Comment by SteveSandersonMS** [comment]
I'm afraid that's not a feature of the Webpack dev middleware integration we've shipped. If you really want to do this using Webpack dev server, you'll need to install and run it manually (e.g., as [documented here](https://github.com/webpack/webpack-dev-server)).

However, could you clarify why you'd want to do this using Webpack dev middleware rather than using [the native ASP.NET Core proxying feature](http://josephwoodward.co.uk/2016/07/proxying-http-requests-asp-net-core-using-kestrel/)?

If you think there's some reason why people will really need to do this using Webpack dev middleware rather than ASP.NET's built-in proxying library, could you please reopen this issue with further details?

**Comment by korneel** [comment]
@SteveSandersonMS Thanks for the link to the article. That's a perfect solution for this.
