### ISSUE TITLE
Deploy Angular2Spa small application

### ISSUE THREAD

**Issue by denimaaark** [aspnet/JavaScriptServices#364]
Hello,

i am testing Angular2Spa template based application with webpack, and it is working ok.
I want to deploy simple small application and i have some questions about...

In project.json there is configuration
  "publishOptions": {
    "include": [
      "appsettings.json",
      "ClientApp",
      "node_modules",
      "typings",
      "Views",
      "tsconfig.json",
      "tsd.json",
      "web.config",
      "webpack.*.js",
      "wwwroot"
    ]
  },

I have published local app and it is working too...

But, do we realy need to deploy node_modules with 15.000 files, tsd.json etc ...?
Please suggest what is right way to deploy small working application.

Thank You

**Comment by SteveSandersonMS** [comment]
You do need to deploy `node_modules` if you want server-side execution, because that's where Angular 2 (etc) will be. If you're deploying from source control, then this doesn't actually involve transferring the 15000 files - the server will fetch its own copy of `node_nodules` during deployment. But if you are deploying via VSTS or FTP or similar, then yes you do need to include those files in the transfer.

For `tsd.json` and all your TypeScript source code, that used to be necessary to include in the deployment. But more recently we changed the default template so those no longer have to go to your production server (now, we precompile a server-rendering bundle during publishing, and exclude the TypeScript sources from the published output).

If you're not using server-side prerendering, then you don't need any of this.

**Comment by denimaaark** [comment]
Steve, thank You for answer, i understand now ....

But I have one more question.

I am trying to delpoy test application to azure with git method and there was error deploying, because there are to meny node_modules depth dependencies....

How to resolve this situation ?

Thanks

**Comment by denimaaark** [comment]
And if i set in .gitignore to not upload node_modules, and upload package.json, there is error 
 syscall rename\r\n\r\nnpm ERR! EINVAL: invalid argument, rename 'D:\home\site\wwwroot\node_modules\webpack\node_modules\watchpack\node_modules\chokidar\node_modules\anymatch\node_modules\micromatch\node_modules\braces\node_modules\expand-range\node_modules\fill-range\node_modules\isobject\node_modules\isarray\package.json.3297916379' -> 'D:\home\site\wwwroot\node_modules\webpack\node_modules\watchpack\node_modules\chokidar\node_modules\anymatch\node_modules\micromatch\node_modules\braces\node_modules\expand-range\node_modules\fill-range\node_modules\isobject\node_modules\isarray\package.json'\r\nnpm ERR! \r\nnpm ERR! If you need help, you may report this error at:\r\nnpm ERR!     <https://github.com/npm/npm/issues>\r\n\r\nnpm ERR! Please include the following file with any support request:\r\nnpm ERR!     D:\home\site\wwwroot\npm-debug.log\r\nD:\Program Files (x86)\SiteExtensions\Kudu\58.51006.2456\bin\Scripts\starter.cmd "D:\home\site\deployments\tools\deploy.cmd"

deploy failed ...

**Comment by SteveSandersonMS** [comment]
If you're deploying to Azure, you need to configure Azure to use a recent version of Node. Otherwise, by default, it uses an old version that can't restore dependencies properly. See the info about specifying a Node version here: http://blog.stevensanderson.com/2016/10/04/angular2-template-for-visual-studio/#now-lets-deploy

I'm looking into whether we can make the template control the Node version automatically, but for now you'll need to configure it in the Azure portal manually.

**Comment by MarkPieszak** [comment]
I wonder if/when they'll update the default version of Node in Azure, it seems like npm3+ is more-so the default now a days!

**Comment by denimaaark** [comment]
Steve, thank You for answer, I have set now node version in azure.
Please what You suggest, is it better to delpoy node_modules folder with all files 
or only package.json ?

**Comment by SteveSandersonMS** [comment]
If you are deploying from source control (via a `git push`), then don't include your `node_modules` because Azure will restore them for you anyway during deployment.

If you are deploying by some other method (e.g., FTP, or from Visual Studio's "publish" feature), then you do need to include `node_modules`, as they have no other way to get onto your production server.

**Comment by denimaaark** [comment]
Thank You ...
