### ISSUE TITLE
Add EventSource polyfill so that webpack HMR can work on IE/Edge

### ISSUE THREAD

**Issue by SteveSandersonMS** [aspnet/JavaScriptServices#365]
Currently, HMR fails on IE/Edge because http://caniuse.com/#feat=eventsource

**Comment by MarkPieszak** [comment]
Is this something new they implemented? Thought it always worked with IE!

**Comment by jongalloway** [comment]
EventSource doesn't work in IE, and is [still just in "Under Consideration" status for Edge](https://developer.microsoft.com/en-us/microsoft-edge/platform/status/serversenteventseventsource/?q=eventsource).

I've looked at this a bit before, I think [this](https://github.com/Yaffle/EventSource) might be the most popular one - it's been maintained for 4+ years and supports a lot of browsers.

**Comment by SteveSandersonMS** [comment]
Thanks @jongalloway - have added that one and it works.

**Comment by JohnGalt1717** [comment]
I'm confused.  I just downloaded the template pack and started it up in IE and Edge and neither have the event-source polyfill added by default. I added it to the webpack.config.vendor.js manually and there's no difference.

**Comment by antmdvs** [comment]
> and neither have the event-source polyfill

How do you know this? Are you seeing this message in the browser's console when you refresh your page?

> webpack-hot-middleware's client requires EventSource to work. You should include a polyfill if you want to support this browser: https://developer.mozilla.org/en-US/docs/Web/API/Server-sent_events#Tools

**Comment by JohnGalt1717** [comment]
Yes I'm seeing the message in the browser console in both Edge and IE.

Yes I should include a polyfill. Actually a Microsoft development effort should include the polyfill by default because you know YOUR browsers don't work without it and telling people to use GOOGLE'S browser in a Microsoft development environment is STUPID on Microsoft's part because it ensures that developers don't need your tools at all and thus have no reason to develop on Windows or use Visual Studio. But I digress...

As I noted I added the npm for eventsource-polyfill from the page you noted and then put it in the webpack.vendor.config.js file in the vendors section. It doesn't complain but after rebuilding the webpack file and running it again, there is no difference at all and the error message still shows up in the console for both IE and Edge.

So yes, your templates should have this and any other polyfills for IE 11+ development installed automatically. (or at the very least give a options box when you create the template)  Further if you're going to instruct someone to "include a polyfill" it might be helpful to tell them HOW to do so given the complexity of how this project is setup versus instructional materials on webpack's site, and even MVC.net etc.

**Comment by SteveSandersonMS** [comment]
The latest template does include the `event-source` polyfill - it's just not published to the VS gallery yet. If you want to run the latest template, please use the Yeoman generator (`npm install -g yo generator-aspnetcore-spa` then run `yo aspnetcore-spa`).

**Comment by dkent600** [comment]
@SteveSandersonMS  I am using the latest template (for Aurelia) and it does not include a dependency on the eventsource-polyfill.


.
