### ISSUE TITLE
outdated readme.md

### ISSUE THREAD

**Issue by lucamorelli** [aspnet/JavaScriptServices#366]
if I run the angular 2 generator of aspnetcore spa yo generator and I open the readme.md I find

# Welcome to ASP.NET 5

**Comment by SteveSandersonMS** [comment]
Well spotted!

As it happens, this was already fixed (https://github.com/aspnet/JavaScriptServices/commit/53889c0fc1563a1cfee6f7b11c9f7e459678bca7). We haven't yet published updates to the templates, but when we do, you'll be able to get them by running `npm install -g generator-aspnetcore-spa` again, so it will apply to any future projects you create.

**Comment by MarkPieszak** [comment]
@SteveSandersonMS By any chance, could we update the ReadMe's a little further as well, to point out the things each one has (the framework, maybe how prerendering works, helpful links, etc)?

I can start typing up some basic stuff if you'd like as well. Just an idea!

**Comment by SteveSandersonMS** [comment]
There are already docs (e.g., https://github.com/aspnet/JavaScriptServices/blob/dev/README.md and https://github.com/aspnet/JavaScriptServices/blob/dev/src/Microsoft.AspNetCore.SpaServices/README.md).

We could link to those, but let's avoid duplicating the content. Also, since the `README.md` content is currently shared with the other ASP.NET templates (the non-SPA ones), we should avoid diverging from their content and format much, because then it would be an extra thing to maintain.

**Comment by MarkPieszak** [comment]
Sounds good to me! We link to the template as a Universal starter, I'll just make sure we have some notes there explaining what it is & how to use it. Thanks
