### ISSUE TITLE
unable to debug typescript sources

### ISSUE THREAD

**Issue by lucamorelli** [aspnet/JavaScriptServices#367]
Hi, I don't know if I'm missing something about webpack, but I would like to know if is there any way to debug the running application using chrome and typescript.
Normally, using angular 2 and system.js when I can debug the application setting breakpoints in the typescript source inside the chrome dev tools: normally I add just the inlineSourceMap and inlineSources to the tsconfig file, but I don't know if it's necessary.
I tried this with the project generator via yo: I look in the web tools, and in the webpack:// section I find the .ts files, but I see the compiled js file and I can set breakpoint, but I think it's very difficult to work this way in a real application.
Is there any way to do this?

**Comment by SteveSandersonMS** [comment]
Sorry, I'm not certain what aspect of debugging you're having trouble with. You say you can set breakpoints, so what's not working adequately?

I find the easiest way of using the Chrome debugger to find the file/line I want to set breakpoints on is to press ctrl+o (or cmd+o on Mac) and then begin typing the name of the file I want to debug. It will autocomplete on filenames. You can then see your original TypeScript source code, set breakpoints on it, inspect variables, etc.

<img width="1020" alt="screen shot 2016-10-10 at 09 33 38" src="https://cloud.githubusercontent.com/assets/1101362/19230355/02089842-8ecc-11e6-903b-3487c87c0c51.png">

I'll close this because, as far as I'm aware, this already works well. But if you think something is wrong, please reopen with details!
