### ISSUE TITLE
[question] Different providers on client and server

### ISSUE THREAD

**Issue by piotrek-k** [aspnet/JavaScriptServices#371]
Sorry that I'm creating issue to ask this question, but I don't know where else could I ask about it.
I've generated Angular app using your Yeoman generator. I want to use localStorage in my app, but it's inaccessible during server pre-rendering (there is nothing like localStorage in node or whatever renders this page).

I've found possible solution: http://stackoverflow.com/a/39098748/1804027 but it requires specifying different provider for client and different provider on server. How can I do that in your template, when I have one `app.module.ts` file for both client and server?

**Comment by MarkPieszak** [comment]
@piotrek-k In this case you'll need to split up the module file into a client & server one.

just create an `app.server.module.ts`, next to that file, dependency injecting what you need for each scenario. Make sure you update your boot-server to import that file instead of the normal `app.module.ts` one.

**Comment by SteveSandersonMS** [comment]
Or if you prefer to have a single `app.model.ts` file, change the line that imports `angular2-universal` to:

    import { UniversalModule, isBrowser, isNode } from 'angular2-universal';

... and then you can use logic like `if (isBrowser) { ... }` or `if (isNode) { ... }` elsewhere in your module when configuring the imports.
