### ISSUE TITLE
[Proposal] Adding TS2 custom "paths []" to projects to enable easier imports

### ISSUE THREAD

**Issue by MarkPieszak** [aspnet/JavaScriptServices#390]
Just an idea, I wanted to see how everyone felt about it. @SteveSandersonMS 

Instead of "directory" relative situations like:

```
import { NavBarComponent } from '../../components/nav-bar.component';
import { SomeOtherService } from '../../shared/some-other.service';
```

I always recommend people use TS2's new feature that allow directory "from" Paths[] instead. This allows you to rearrange files easily without losing their dependencies. 

```
import { NavBarComponent } from 'myapp-components';
import { SomeOtherService } from 'myapp-services';
```

**Tsconfig** would look like this: 

```
paths : {
    "myapp-components" : [ "./components" ],
    "myapp-services"   : [ "./services" ]
}
```
     

This is assuming you have an `index.ts` *barrel* at the root of each directory you're making Paths from. This allows you to access everything directly from just the path.

     // example barrel index.ts in /components
     export * from './nav-bar/nav-bar.component';
     export * from './home/home.component';
     // etc

> Note: For all of this to work, the projects will also need Webpack2 upgrades, as well as *TsConfigPathsPlugin* from awesome-typescript-loader. But it's not much to setup within each webpack.config file. I haven't had any problems setting this up in other projects, but we might need to look into aspnet-webpack to see if it's able to understand TsConfigPathsPlugin etc.

**Comment by SteveSandersonMS** [comment]
Thanks for the suggestion @MarkPieszak.

I think this would make a great addition to docs as a possible alternative way to arrange the files.

I'd prefer not to put it in the templates out-of-the-box because it's another abstraction that people totally new to TypeScript might trip up on (if they don't know this feature exists, they won't know how the compiler is locating the files, or they might not realise that they need to add new entries to `paths` in `tsconfig.json` when adding the components, and then not understand why it can't find their files).

Is that OK?

**Comment by MarkPieszak** [comment]
Very true it can confuse those unfamiliar with both TS2 features and Webpack2s setup required to also be able to compile them! Yes you're right, files need to be added either to the index barrel or paths array. That could trip some developers up.

Sounds good to me, docs it is :+1:
