### ISSUE TITLE
Cannot resolve module 'es6-promise'

### ISSUE THREAD

**Issue by beckmx** [aspnet/JavaScriptServices#393]
Hello guys, I found this issue when trying to generate an angular2 template:

ERROR in dll vendor
Module not found: Error: Cannot resolve module 'es6-promise' in /Users/andressantos/mynewthing
 @ dll vendor

**Comment by SteveSandersonMS** [comment]
Can you please provide repro steps?

**Comment by SteveSandersonMS** [comment]
I'm afraid I haven't been able to reproduce this issue. At least with the current `generator-aspnetcore-spa`, Angular 2 projects don't produce any compiler errors when created.

Since we don't have any repro details, I'll mark this as closed. But if anyone knows how to reproduce this problem, please open a new issue with details!

**Comment by HassanHashemi** [comment]
@beckmx did you found any solution to this?

**Comment by HassanHashemi** [comment]
during publish aspnet is looking for es6-promise in a different folder, after installing it the issue seems to be fixed.
