### ISSUE TITLE
Angular 2 template are production ready ?

### ISSUE THREAD

**Issue by JanickRoss** [aspnet/JavaScriptServices#405]
If I start a new enterprise project with the "yo spa generator for angular 2", it's a good idea for a production ready product ? 

Do you have plan to add support for aot compilation, etc..

**Comment by SteveSandersonMS** [comment]
I don't see any reason why you shouldn't regard it as production ready, since the underlying technologies (Angular 2, ASP.NET Core, Webpack, etc.) are themselves production versions.

> Do you have plan to add support for aot compilation, etc..

Yes, we'll do it as soon as there's a supported way to integrate it with a webpack build. Right now I hear it's too early for that.
