### ISSUE TITLE
Update aspnet-webpack dependency on Webpack

### ISSUE THREAD

**Issue by JohnCampionJr** [aspnet/JavaScriptServices#409]
Using webpack 2.1.0.beta.25 I get this error from NPM.

npm WARN aspnet-webpack@1.0.21 requires a peer of webpack@^1.13.2 but none was installed.

Still works fine, just causes an unnecessary warning.

**Comment by SteveSandersonMS** [comment]
Webpack 2 hasn't been released yet, which is why `aspnet-webpack` remains dependent on Webpack 1. The dependency is declared as a peerDependency so that it's not strictly an error to use Webpack 2, but you will get this warning.

So I'm not sure there's anything we can do to help with this until Webpack 2 ships. If you think there is, please reopen with details!

**Comment by SteveSandersonMS** [comment]
Update: there is a clean way to do this - we can declare the peerDependency as:

    "peerDependencies": {
      "webpack": "^1.13.2 || ^2.1.0-beta"
    }

This is now published in aspnet-webpack 1.0.24, so you should find the warning goes away :)
