### ISSUE TITLE
webpack2 compatibility

### ISSUE THREAD

**Issue by ronnyek** [aspnet/JavaScriptServices#414]
I realize webpack2 is in betas at the moment, wondering if we could expect compatibility, or if the way aspnet-webpack communicates is hugely different.

**Comment by MarkPieszak** [comment]
I'm pretty sure you could upgrade your project to Webpack2 if you wanted, and it should work, you'll just have to change a few things in the webpack.config (since a few things changed in v2).

I believe Steve wanted to wait until it stabilizes and gets out of beta before officially rolling it out in the project templates.

**Comment by SteveSandersonMS** [comment]
It's already pretty much webpack2 compatible. When I tried upgrading, the only thing I had to change was this:

    resolve: { extensions: [ '', '.js', '.ts' ] },

... to this:

    resolve: { extensions: [ '.js', '.ts' ] },

(i.e., remove the empty-string entry in that list, because Webpack 2 rejects it, and it turns out it wasn't needed anyway).

We'll change `package.json` to point to Webpack 2 as soon as it's released.
