### ISSUE TITLE
Templat does not show up

### ISSUE THREAD

**Issue by jimpevans** [aspnet/JavaScriptServices#418]
Hi -

I have all the prereq's but after the install the template does not show up. No errors during the install. VS was closed during install then started after. This looks wonderful and I would love to explore it - thanks.

**Comment by MarkPieszak** [comment]
What do you mean by the template doesn't show up? Did you install through yeoman to get the specific template you need?

**Comment by jimpevans** [comment]
I was following an article that had a link to get a project template for Visual Studio 2015 for a Angular 2 + .Net Core project. In that article was a link to post issues which brought me here - here is the link to the article   http://blog.stevensanderson.com/2016/10/04/angular2-template-for-visual-studio/

**Comment by MarkPieszak** [comment]
Have you restarted or anything, not sure why the templates wouldn't be showing up in VStudio after all that.

**Comment by jimpevans** [comment]
VS was not running during the install but yes - I started VS after the install. I also then tried rebooting the machine. Then tried uninstalling the extension and re-installing it but nothing seems to resolve the issue.

**Comment by SteveSandersonMS** [comment]
I'm afraid I don't know why it wouldn't appear in the list in VS. It certainly does when I've installed it, and on other machines I've seen it on. Perhaps there is something unusual about your installation of VS. Do the other templates from the ASP.NET Core Template Pack appear (e.g., Vue.js with Webpack)?

Since this is an issue specifically about getting the ASP.NET Core Template Pack templates to show up in VS, would you mind reporting it at https://github.com/ligershark/CoreTemplatePack/issues instead of here? Thanks!

**Comment by jimpevans** [comment]
No problem - I will report it at the link you provided. The only reason I reported it here is that is the link the article proided to report issues.
