### ISSUE TITLE
Angular 2 server side Prerender in asp.net Core

### ISSUE THREAD

**Issue by satyabratasenapati** [aspnet/JavaScriptServices#420]
I have an issue with Angular2 server side prerendering with asp.net core .I got localStorage issue while it is finely running in angular 2 application.Please suggest.

**Comment by SteveSandersonMS** [comment]
Hi there. `localStorage` is a browser API which doesn't exist on the server. Even if the API existed in Node, it wouldn't have access to the same data that's stored in the browser.

So, you have two main options:

 * You can modify your application code so that, when it's running on the server, it either doesn't attempt to touch `localStorage`, or you have some abstraction around `localStorage` so that server-side code reads and writes data from some other place.
 * Or, you could decide that server-side prerendering isn't applicable for your app (if you absolutely must use browser-side `localStorage` for everything your app does), and therefore disable server-side prerendering
