### ISSUE TITLE
integrate with webpack dev server to speedup rebuilding time

### ISSUE THREAD

**Issue by tutok** [aspnet/JavaScriptServices#424]
I am trying to understand what I need to do to introduce webpack-dev-server to speed up my development process .  
I see that prerendering uses webpack.config to rebuild app, but in my project it is taking to much time. Sometimes it takes more than 1 min. It looks like it is full rebuild, and I think doing it incrementally could be a reasonable step

What is the best approach to use webpack-dev-server? Have any of you similar issue?

**Comment by SteveSandersonMS** [comment]
> I see that prerendering uses webpack.config to rebuild app

If you're seeing `asp-prerender-webpack-config` in your code then your app was generated with an older version of the generator. The newer generator produces projects where the prerendering bundle is produced at build-time rather than at runtime, so is faster to start in production. You might want to try the newer generator.

I'll close this because the change you want is already implemented :)

**Comment by tutok** [comment]
Still one thing is not clear for me. 
I would like to use [webpack-dev-server](https://webpack.github.io/docs/webpack-dev-server.html) incremental build feature. Is it avaliable out of the box in latest version of JavaScriptServices? Or should I run such a server myself and integrate it with 'server side prerendering' by providing url to it instead of static file `asp-prerender-module="http://localhost:8080/ClientApp/dist/main-server"` ?
