### ISSUE TITLE
Can't get data from server when publish to IIS

### ISSUE THREAD

**Issue by Tisha28** [aspnet/JavaScriptServices#425]
Hi,
I've faced with the folllowing problem. I created application in accordance with the following guide http://blog.stevensanderson.com/2016/10/04/angular2-template-for-visual-studio/
I don't do any modifications, just work with template. When application is run from Visual Studio all pages are opened successfully. But when application is published on IIS, then "Fetch data" page is loaded with error in console that the route localhost/api/fetchdata/WeatherForecast can't be found.
I have published application from Visual Studio with File System publish method.
Does anyone know how to solve this problem?

**Comment by SteveSandersonMS** [comment]
I'm afraid I don't know why it wouldn't match your ASP.NET route.

What steps did you follow to publish on IIS?

**Comment by Arbixal** [comment]
To me it looks like it is looking for data from:
http://localhost/api/SampleData/WeatherForecasts

Which doesn't help if your application is at:
http://localhost/**TestApp**

Is it making an assumption that the /api route is at the root of whichever server it is being hosted from?

**Comment by Tisha28** [comment]
Hi,
I published with the following steps:
1. In Visual Studio in publish menu selected option File System and defined path - C:\inetpub\wwwroot\testPublish
2. Other options in Publish menu was left without changes. Pressed Publish button
3. When publish operation completed i went to IIS and refreshed Default Web Site application. Folder  testPublish appeared.
4. I right clicked on testPublish and selected option Convert to Application. In opened menu change AppPool to those one that runs No managed code
![1](https://cloud.githubusercontent.com/assets/23385175/20206285/49dc1b66-a7f0-11e6-8113-464f16f11b03.png)
5. Then I browsed this test publish application. I see that route of this application for some reason doesn't contain "testPublish" part
![2](https://cloud.githubusercontent.com/assets/23385175/20206284/49da5dbc-a7f0-11e6-83b2-d32deb2ef88e.png)
6. In case I refresh page in browser I got HTTP  404 Not Found error.
Perhaps I'm doing something wrong. In previuos versions of Visual Studio I always published with Web Deploy Package. Result of publish was deploy script and .zip file. With this deploy script I installed application to IIS. But in new version only .zip file is generated, so I tried to publish with File System method.

**Comment by MrCrimp** [comment]
There is another, similar issue in these templates. Webpack related.
>publicPath: '/dist/' // Webpack dev middleware, if enabled, handles requests for this URL prefix
This should be 'dist/' so that paths become relative. 
I got burned by this when using dynamic requires with bundle-loader (require.ensure) that sets the 
```__webpack_require__.p``` to absolute '/dist/' and all requests went for root dir and got 404

**Comment by SteveSandersonMS** [comment]
@Tisha28 If you deploy to a non-root directory, there are a few more things you need to do. In general, your client-side code doesn't know that IIS virtual directories or application directories even exist; it continues to regard `/` as the root of your URL space unless you tell it otherwise.

For an Angular 2 application, you need to add a `<base>` element to your page's `<head>` to describe the root URL that the router should regard its config as being relative to. For example, in your `<head>` element, change the `<base>` element to be: `<base href="/testPublish/" />`. Now your client-side routing config should resolve paths against that root. To make the same thing work with server-side execution, just put the same info into the `baseUrl` property in `boot-server.ts`.

Secondly, if you make HTTP requests back to your server, you will also need to supply the correct full path, because again, the client-side code doesn't know anything about IIS hosting otherwise, For example, in your fetch-data code, change the URL it requests to `/testPublish/api/WeatherForecast`. Angular doesn't automatically prefix your base URL onto the URLs it makes requests to, because it doesn't know that's what you want it to do (maybe you actually want to request something from a WebAPI hosted in a different application directory). Or if you prefer, look into ways of configuring `http` to auto-prefix the URLs in some way, e.g.: http://stackoverflow.com/questions/34516651/set-base-url-for-angular-2-http-requests

I know that's a bunch of extra work, and doesn't make your app automatically portable to differently-named application directories, but client-side code just doesn't know about IIS concepts like that. The vast majority of apps are deployed to root URLs (i.e., baseUrl = `/`) and so don't face this inconvenience.

@MrCrimp I'd be happy to fix that but it sounds like a separate matter (as in, maybe it's actually a bug, whereas @Tisha28's report is as designed). Would you be able to post a new issue with repro steps? I'm not even sure how you've set up a development environment where `/` isn't the base URL.

**Comment by SteveSandersonMS** [comment]
@Tisha28: An update: I realise we could make it a bit easier to handle non-root base URLs:

 * In the templates' `_Layout.cshtml` files, we could set the base URL as `<base href="~/" />`. I haven't tested this in detail, but I'd expect this to correctly resolve to whatever application directory you're deployed to.
 * To populate `baseUrl` in `boot-server.ts` automatically, we could pass that information through from the .NET code to the Node code. Most of this is [now implemented](https://github.com/aspnet/JavaScriptServices/commit/0a116ba2a16c51ac7156189e2a7aa5f12826b3bd). In principle (though again, not yet tested), it should be possible for `boot-server.ts` now to specify `baseUrl` like this:

    baseUrl: params.baseUrl

I'll look at updating the templates along these lines. The other point about having to specify complete URLs when making ajax requests remains unchanged though.
