### ISSUE TITLE
SpaServices Webpack Dev Middleware - optional storing files to disk

### ISSUE THREAD

**Issue by kukjevov** [aspnet/JavaScriptServices#431]
Currently when you use Webpack Dev Middleware, you use both in memory compilation of typescript and also stores copy of generated files to disk. 

It would be great to have this configurable via options. 

My reason is simple, if you don`t debug your application during development, it is just spamming your disk with many files for each change. 

Thank you

**Comment by SteveSandersonMS** [comment]
> it is just spamming your disk with many files for each change

It's not creating any extra files, is it? It should only be overwriting the previously-built files. If you find some scenario where it does write extra files to disk, please let me know how to reproduce that situation.

Writing the files to disk is necessary for the server-side prerender to be updated correctly, because that's produced by a running Node instance that wouldn't know anything's changed unless it could observe the file on disk being written.

Writing the files to disk is less essential to as far as client-side rendering is concerned (because we're serving the compiled files out of memory anyway), but there is a situation where it is necessary: IDE-based debugging. If you're trying to use VS/VSCode to debug, then it will only work properly if your `.js` files on disk match up with what has been served to the browser.

Since things will go wrong if the files aren't written to disk, I'm not sure it's a good idea to even have an option to disable it. It would create the possibility of subtle, unexpected problems, that wouldn't be easy for people to debug/fix.

If you can describe any situation where writing the files to disk actually causes a problem (e.g., creating extra unnecessary files), please reopen with details! Otherwise I think we should leave this behaviour as-is.
