### ISSUE TITLE
Issue with domain tasks while doing server prerendering

### ISSUE THREAD

**Issue by LovedByTheLord** [aspnet/JavaScriptServices#433]
Hi,

I have a component that calls three action creators in componentWillMount.  Each of these makes a call to an API to get data.

    componentWillMount() {
        this.props.requestCompanyProducts();
        this.props.requestCompanies();
        this.props.requestProducts();
    }

I want all of these calls to be completed on the server when the page is first loaded.  However, it seems that the prerendering is completing before requestCompanies is completed.

The action creator for requestCompanies looks like this:

    requestCompanies: (): ActionCreator => (dispatch, getState) => {
        if (getState().companies.companies.length === 0) {
            let fetchTask = fetch('/api/Companies/', {
                headers: {
                    'Accept': 'application/json'
                }
            })
            .then(response => {
                if (response.ok) {
                    response.json().then((companies: Company[]) => dispatch(new ReceiveCompanies(companies)));
                }
                else {
                    response.json().then(body => dispatch(new ReceiveCompanies(undefined, body.Message)));
                }
            })
            .catch(error => {
                dispatch(new ReceiveCompanies(undefined, error));
            });
            
            addTask(fetchTask); // Ensure server-side prerendering waits for this to complete
            dispatch(new RequestCompanies());
        }
    }

The reducers:

    export const reducer: Reducer<CompaniesState> = (state, action) => {
        if (isActionType(action, RequestCompanies)) {
            return { isLoading: true, error: '', companies: state.companies };
        }
        else if (isActionType(action, ReceiveCompanies)) {
            return { error: '', companies: action.companies, isLoading: false };
        }

        // For unrecognized actions (or in cases where actions have no effect), must return the existing state
        // (or default initial state if none was supplied)
        return state || unloadedState;
    };

The problem is that "window.initialReduxState" does not have the final result of the API call.  It has the "is loading" state that exists while the app is waiting on the server call to complete.

window.initialReduxState = {"companyProducts":{"error":"","companyProducts":[{"companyProductUrlInt":4,"companyInt":30,"productInt":1,"url":"http://blah/"},{"companyProductUrlInt":1,"companyInt":30,"productInt":3,"url":"http://blah2/"},{"companyProductUrlInt":5,"companyInt":2409,"productInt":1,"url":"blah3/?q=Thisisatest"}],"isLoading":false},**"companies":{"isLoading":true,"error":"","companies":[]}**,"products":{"error":"","products":[{"productInt":1,"name":"Product 1","code":"wot"},{"productInt":3,"name":"Product 2","code":"won"}],"isLoading":false},"routing":{"locationBeforeTransitions":null}};

This causes the API to be called again from the browser.  I set a breakpoint in the API endpoint and it does get hit during the prerendering.  Twice, in fact, and I can't figure out why it gets called twice.  Once in a blue moon, the initial state will contain the companies list as expected.  The company list is quite large (2000+ records).  I'm wondering if there is a timing thing going on.  

I added a Task.Delay to the API endpoint that gets called by `this.props.requestProducts()`.  In that case the companies list was properly added to the initial state.  

I'm at a loss as to how to test this further because I don't know how to debug the javascript that gets called by node during prerendering.

Any ideas what might be happening or how I can debug the node process to see what it's doing?

**Comment by MrCrimp** [comment]
I've seen the same thing in my code from time to time, but have not set aside time yet to investigate. 
What node.js version are you on?

**Comment by LovedByTheLord** [comment]
@MrCrimp  I'm running node 3.10.8.

**Comment by MarkPieszak** [comment]
You need to make sure you have npm > 3.* installed & Node > 4.*
Give it a try with the latest Node 7.*+

**Comment by LovedByTheLord** [comment]
@MrCrimp @MarkPieszak 
I'm sorry.  I gave the npm version before.

node 4.4.1
npm 3.10.8

I'll try upgrading to the latest version of node and post back my results.

**Comment by MrCrimp** [comment]
Yeah, try node 6+ or 7 because I also had those errors when I was on V4.x. I checked and they are gone after upgrading to 6.x





On Wed, Nov 16, 2016 at 5:03 PM +0100, "LovedByTheLord" <notifications@github.com> wrote:












@MrCrimp @MarkPieszak 

I'm sorry.  I gave the npm version before.



node 4.4.1

npm 3.10.8



I'll try upgrading to the latest version of node and post back my results.

**Comment by LovedByTheLord** [comment]
I upgraded to node v7.1.0 and restarting my machine.  Unfortunately, the problem still exists.  The first time I loaded the page, it was actually worse because it made AJAX calls for all three of my endpoints.

![image](https://cloud.githubusercontent.com/assets/17475836/20356090/1f83422a-abe9-11e6-9ac3-f66a6d12e215.png)

`window.initialReduxState = {"companyProducts":{"isLoading":true,"error":"","companyProducts":[]},"companies":{"isLoading":true,"error":"","companies":[]},"products":{"isLoading":true,"error":"","products":[]},"routing":{"locationBeforeTransitions":null}};`

After refreshing the page, it is back to just hitting the Companies endpoint like it was previously.

**Comment by MrCrimp** [comment]
I'd suggest create a new project using the yeoman generator and see if the same problem happen there as well?





On Wed, Nov 16, 2016 at 5:43 PM +0100, "LovedByTheLord" <notifications@github.com> wrote:












I upgraded to node v7.1.0 and restarting my machine.  Unfortunately, the problem still exists.  The first time I loaded the page, it was actually worse because it made AJAX calls for all three of my endpoints.







window.initialReduxState = {"companyProducts":{"isLoading":true,"error":"","companyProducts":[]},"companies":{"isLoading":true,"error":"","companies":[]},"products":{"isLoading":true,"error":"","products":[]},"routing":{"locationBeforeTransitions":null}};



After refreshing the page, it is back to just hitting the Companies endpoint like it was previously.

**Comment by SteveSandersonMS** [comment]
Your promises aren't chained correctly. Your code is like this:

    let promise1 = doSomething1().then(result1 => {
        result1.doSomething2().then(result2 => {
            // Now do something with result 2
        });
    });

When expressed like that, `promise1` **only** waits for `doSomething1`'s operation to complete. It does **not** wait for `doSomething2`, because you haven't asked it to do so. You've just started `doSomething2`, but without chaining `promise1` onto it.

What you want instead is this:

    let promise1 = doSomething1().then(result1 => {
        return result1.doSomething2().then(result2 => {
            // Now do something with result 2
        });
    });

Notice the `return` statement :) By returning a promise from the `then` handler of another promise, you're chaining them together. Now, `promise1` won't resolve until the `doSomething2` operation has completed and its `then` handler has executed.

This would explain the issue you've described, so I'll mark this as closed. But if the problem still occurs even after you fix your promise chaining, please let us know!

BTW I know promises are easy to make mistakes with. Everybody does this. This is why the `async`/`await` APIs are so much better. I'm not certain whether TypeScript 2.1's implementation of `async`/`await` works on all the browsers you need to support, but if it does, you might want to consider using that.

**Comment by LovedByTheLord** [comment]
@SteveSandersonMS, once again you have saved the day!  I'm new to Promises so this information was very helpful and thorough.  Adding the "return" seems to have fixed my issue.  Thank you so much for taking the time to help.  I'm very used to async/await in C#, so I look forward to being able to use it in TS soon.
