### ISSUE TITLE
ag-Grid: HTMLElement is not defined

### ISSUE THREAD

**Issue by bperry77** [aspnet/JavaScriptServices#439]
I am trying to add [ag-Grid](https://www.npmjs.com/package/ag-grid-ng2) to my Angular 2 project but I get the following error:

> Exception: Call to Node module failed with error: ReferenceError: HTMLElement is not defined

As I understand, this is because I have prerendering enabled 

`<app asp-prerender-module="ClientApp/dist/main-server">Loading...</app>`

which is not executed in the context of a DOM.

Disabling prerendering fixes the issue but now I have lost the benefit of prerendering.  Is there a way I can exclude ag-Grid code in server-side prerendering?

Thanks!

**Comment by MarkPieszak** [comment]
In this case you're using a directive/component library, so even if you excluded the library from rendering on the server, Angulars template parser would error out since it doesn't know how to handle an unknown element unfortunately :(

Do you need to use that one, or could you use a more well known one that should be able to be rendered on the server as well? Check out: https://github.com/valor-software/ng2-table

**Comment by SteveSandersonMS** [comment]
@bperry77 Since this is a compatibility issue with Angular Universal, I'll leave this with @MarkPieszak to discuss with you. I'll close it here, but if you want to follow up on the Angular Universal issues list you could do so (or possibly on the ag-Grid issues list, since perhaps they could fix this by removing the DOM dependency). Hope that's OK!
