### ISSUE TITLE
ASP.NET Identity Core integration with Angular2Spa Template

### ISSUE THREAD

**Issue by ASADeveloper** [aspnet/JavaScriptServices#445]
Hi,

How can we use ASP.NET Core Identity with the Angular2Spa template the proper way?

**Comment by MarkPieszak** [comment]
You can look at a sample from the Identity repo that should get you going in the right direction: https://github.com/aspnet/Identity/tree/dev/samples/IdentitySample.Mvc

Notice the services added in the ConfigureServices part of the StartUp.cs
https://github.com/aspnet/Identity/blob/dev/samples/IdentitySample.Mvc/Startup.cs#L49

Aside from that you can see the AccountController (which you would use as your REST calls you're making from the Client-side. https://github.com/aspnet/Identity/blob/dev/samples/IdentitySample.Mvc/Controllers/AccountController.cs#L19
You can ignore the ones that return Views, since your Client-side would be providing the actual "login" page itself, but notice the `[HttpPost]` Login. 

Instead of returning a `View()` you want to turn this into a Rest API endpoint, so just like you normally would, add the Routing attributes on top of the Controller itself `[Route("api/[controller]")]`
e providing the actual "login" page itself, but notice the `[HttpPost]` Login. 

Instead of returning a `View()` you want to turn this into a Rest API endpoint, so just like you normally would, add the Routing attributes on top of the Controller itself `[Route("api/[controller]")]`, add the `[HttpPost("[action]")]` on top of the Login method itself. Of course you'll have to change up & tweak a few other things, but this is the jist of what you'd need to do, to get it all started! Hope that helps!

**Comment by SteveSandersonMS** [comment]
Thanks for posting the info @MarkPieszak
