### ISSUE TITLE
problems with Net Core 1.0.1

### ISSUE THREAD

**Issue by doczoidberg** [aspnet/JavaScriptServices#451]
I setup a new angular2 project.

When running `dotnet run` in cossole:
```
The specified framework 'Microsoft.NETCore.App', version '1.0.1' was not found.
  - Check application dependencies and target a framework version installed at:
      C:\Program Files\dotnet\shared\Microsoft.NETCore.App
  - Alternatively, install the framework version '1.0.1'.
```

When opening the project in VS2015/VS2017RC:

`...The specified framework Microsoft.NETCore.App version 1.0.1 was not found...`

I have installed the latest .NET core

**Comment by MarkPieszak** [comment]
Did you install 2017rc? I believe it installs 1.1 with it, so now you can't run older version projects since your system has 1.1 overriding it. You'll have to change the current running version to get it to work. 

http://www.hanselman.com/blog/WheresDNVMSafelyRunningMultipleVersionsOfTheNETCoreSDKAndToolingWithGlobaljson.aspx

Dnvm is gone, but with a global.json file you can pinpoint what version you want running for a specific project. You can also see it change when you do dotnet --version 

http://www.hanselman.com/blog/content/binary/Windows-Live-Writer/S_13648/image_d92d8331-82f2-403f-8955-928b0f00851c.png

**Comment by doczoidberg** [comment]
I had also to install the .net core runtime.
