### ISSUE TITLE
how to cache a nodejs method in nodeservices

### ISSUE THREAD

**Issue by AnyListen** [aspnet/JavaScriptServices#462]
consider this : i have a jsvascript file (cmd5.js), it is a little bigger
when i call the method in this file using below code; 
I am doubtful about that the mothod will reload cmd5.js everytime, so this is less efficient;
how to be more efficient
```
_nodeServices.InvokeExportAsync<string>("./Node/cmd5", "qymd5", input).Result;
```

**Comment by SteveSandersonMS** [comment]
It doesn't reload your file every time :) We keep the same Node instance alive (unless it has to restart because a `.js` file on disk changed), and Node itself keeps the modules' compiled code in memory for reuse every time that module is referenced.

So, in effect, it's already cached in the way you want.
