### ISSUE TITLE
WebApplicationBasic READMD.md out of sync with code

### ISSUE THREAD

**Issue by WrathZA** [aspnet/JavaScriptServices#463]
IN: https://github.com/aspnet/JavaScriptServices/blob/dev/templates/WebApplicationBasic/README.md

The README mentions gulp and bower while the application itself uses webpack and npm for dependencies. It created some confusion.

**Comment by SteveSandersonMS** [comment]
Thanks for the reminder about this.

For now, I've removed the `README.md` files from the templates, because like you point out, they are misleading in parts, and outdated in other parts. I think we've gone past the point where ASP.NET Core would surprise anyone by being different from classic ASP.NET.
