### ISSUE TITLE
Out of the Box - Problems on IIS 8

### ISSUE THREAD

**Issue by imukai** [aspnet/JavaScriptServices#490]
Edit:  Got the main problem of the post, and two additional things below it.  If they warrant their own post let me know.

I first tried the VS Template and it worked fine local - started having problems when I published it to my IIS server.  So I started fresh with Yeoman and still can't get this thing to work remotely.  It still works fine on my local machine.

Note:  The main ASP Core MVC App template runs just fine on my server - but I wanted to get my hands dirty with what you have going here.

This relates to IIS 8 on Server 2012, and the Angular2 version of the SPA package.

Here's what I've done after downloaded a fresh copy using yeoman.

Out of the box:
1. Compiles / Runs locally through VS with zero problems (and I love it)
2. Added a static file in wwwroot.
3. Published to IIS via Web Deploy.

Results on IIS:
1. Serves static file fine.
2. 500 otherwise - not the app's Home/Error.  The body of the response contains the Home/Error markup but browser is showing a generic 500 page.  Server logs show 500 0 as the error.
3. Stdout:
	fail: Microsoft.AspNetCore.Diagnostics.ExceptionHandlerMiddleware[0]
		An unhandled exception has occurred: The system cannot find the file specified
4. Run directly from Kestrel, blows up:
	Unhandled Exception: System.AggregateException: One or more errors occurred. (Call to Node module failed with error: Webpack dev middleware failed because of an error while loading 'aspnet-webpack'. Error was: Error: Cannot find module 'aspnet-webpack'

Returned to VS:
1. Added "node_modules" to project.json under publishOptions/include.
2. Published to IIS via Web Deploy.

Results on IIS:
1. Serves static file fine.
2. 500 otherwise.  Same as before.
3. Stdout:
	fail: Microsoft.AspNetCore.Diagnostics.ExceptionHandlerMiddleware[0]
		An unhandled exception has occurred: The system cannot find the file specified
4. Run directly from Kestrel, blows up:
	Unhandled Exception: System.AggregateException: One or more errors occurred. (Call to Node module failed with error: Error: Cannot find module '************\webpack.config.js'
    at Function.Module._resolveFilename (module.js:469:15)

Returned to VS:
1. Added "webpack*.js" to project.json under publishOptions/include
2. Published to IIS via Web Deploy

Results on IIS:
1. Serves static file fine.
2. 500 otherwise.  Same as before.
3. Stdout:
	fail: Microsoft.AspNetCore.Diagnostics.ExceptionHandlerMiddleware[0]
      An unhandled exception has occurred: The system cannot find the file specified
4. Run directly from Kestrel:
	a. some webpack stuff happens
	b. error: 	
     ERROR in multi main-client
     Module not found: Error: Cannot resolve 'file' or 'directory' ./ClientApp/boot-client.ts in C:\***\****
	c. doesn't blow up.
	
Access site via localhost:5000:
1. Serves static file fine.
2. Mostly loads otherwise - the underlying page is there, but has an overlay with the above Error message about the multi main-client.
 
I spent over 10 hours trying to resolve it thinking the problem was an IIS sub-app issue still, but I guess that's no longer a thing.  A couple hours ago I moved it to a top level site and still have issues as outlined above.  

Please save me from myself.

--------------------

Edit:  While I am here and waiting to see how to make this work, I noticed the console errors on Local pointing out the extra **html** and **body** tags that are being rendered after the **app** tag.  Is this something that needs to be fixed still?  It complains about the extra tags.

------------------

Edit 2:  Also noticed 100s of these per second in Fiddler while this is running locally.  Tell me this won't be server calls between client and server in production:

http: localhost:49155/vshub/f1b1ea0776194961a5b01f0fd8d67d8f/DataWarehouseModule/dataWarehouse/getResult/

**Comment by SteveSandersonMS** [comment]
Sorry to hear you've had a tough time with this.

From the errors you've described, I'm wondering if you're using quite an old version of the template. You mention that you had to add `node_modules` to `publishOptions`/`include`, but it's already there by default in the current template.

There are a couple of options for updating:

 * If you get the latest VS template pack from https://marketplace.visualstudio.com/items?itemName=MadsKristensen.ASPNETCoreTemplatePack then hopefully a large portion of the deployment issues should be covered.
 * If you want an even newer template, the `generator-aspnetcore-spa` Yeoman generator (https://www.npmjs.com/package/generator-aspnetcore-spa) is the most up-to-date one.  This version simplifies deployment significantly, because it eliminates the need to deploy `node_modules` entirely.

Could you let me know if either of these approaches are viable for you? If you need any help with migrating the code you've already written, please describe any questions you have.

> Edit 2: Also noticed 100s of these per second in Fiddler while this is running locally. 

I have absolutely no idea what `DataWarehouseModule/dataWarehouse/getResult/` is - it's definitely not in these project templates. Perhaps it was something unrelated that happened to be running in another browser tab :) If you do think something in the project template was involved in making those requests, please let us know!

**Comment by SteveSandersonMS** [comment]
Update: The `DataWarehouseModule` spam seems to be an issue with Visual Studio itself, and you can disable it in options: https://github.com/aspnet/Mvc/issues/3655

**Comment by SteveSandersonMS** [comment]
> I noticed the console errors on Local pointing out the extra html and body tags that are being rendered after the app tag. Is this something that needs to be fixed still?

It was an issue in Angular Universal, but has since been fixed in the latest `generator-aspnetcore-spa` template for Yeoman.

**Comment by SteveSandersonMS** [comment]
BTW I'll close this now because hopefully the issues you've reported will be handled by the updated template. Please let me know if not.
