### ISSUE TITLE
How to get Aurelia Version to rebuild dist folder after initial Typescript Transpilation

### ISSUE THREAD

**Issue by ajdisalvo72** [aspnet/JavaScriptServices#491]
I ran the Aurelia version and it initially ran great on all browsers once I added support for fetch and Promise for internet explorer.. My problem came when I made a change to the code in one of the Typescript files to see how to get the project to refresh. I know that HMR is currently unsupported, but I am puzzled as to how to get a refresh to happen.. I shut down dotnet run and reran dotnet run and it said that it had already been compiled. So I removed the bin and the obj folders and reran it and it rebuilt the dlls, but did not republish the JavaScript and html files to the dist folder. I removed the dist folder and the bin and obj folders and it rebuilt the bin and obj folders, but did not repopulate the dist folder. How would I get this to rerun a transformation of my Typescript files so that it repopulates the dist folder?

**Comment by SteveSandersonMS** [comment]
You can either:

 * Make sure you're running in development mode (set the environment variable `ASPNETCORE_ENVIRONMENT` to `Development`). Then you'll have Webpack dev middleware enabled by default, so that you only need to refresh the page in your browser to see code TS/HTML/etc changes take effect.
 * Or, run `webpack` on the command line from your project root directory. This manually rebuilds the `wwwroot/dist` files.
