### ISSUE TITLE
Error while installing through aspnetcore-spa generator

### ISSUE THREAD

**Issue by Krishna-teja** [aspnet/JavaScriptServices#492]
![image](https://cloud.githubusercontent.com/assets/6452602/20934232/12818340-bba0-11e6-9a18-90d23c4479fb.png)
I am getting an error while I am doing a fresh install through the aspnetcore-spa genrator. The missing file that it was throwing an error does not exist in the .NET Core SDK 1.0 Preview 3 build 004056 binary too [https://go.microsoft.com/fwlink/?LinkID=835127](url)

**Comment by SteveSandersonMS** [comment]
Are you possibly using an older version of `generator-aspnetcore-spa`? The current version of the template emits a `global.json` files that fixes this. Could you try upgrading (run `npm install -g generator-aspnetcore-spa` before running `yo aspnetcore-spa` again) and see if the problem goes away?

Please let us know if that doesn't fix it.

In case you're interested in what was going wrong, the issue is (unfortunately) caused by having installed .NET Core Tools Preview 3 (or VS2017RC, which includes the Preview 3 tools), and not having a `global.json` file to tell `dotnet` which SDK version you want it to build with. It then defaults to Preview 3, even though it's looking for Preview 2 files.

**Comment by Krishna-teja** [comment]
@SteveSanderson Thanks for your reply. The combination of two things fixed my issue. Needed to get the latest generator and make sure I had latest [.net core 1.1 SDK](https://go.microsoft.com/fwlink/?LinkID=835014) installed. Noticed that I was on .net core 1.0.1. Works great now..
