### ISSUE TITLE
Integration Testing

### ISSUE THREAD

**Issue by nicwillemse** [aspnet/JavaScriptServices#493]
I think it would be good if there was example showing an integration test against the controllers. At the moment its not clear how would go about doing this as the standard approaches would not work.

**Comment by SteveSandersonMS** [comment]
Have you seen the Karma tests that the Angular 2 template creates? That's the standard approach.

Please reopen with details if you think this doesn't cover the requirements!

**Comment by nicwillemse** [comment]
@SteveSandersonMS thanks for your prompt response, the Karma tests are only going to be good enough for testing the SPA layer of the application. 

I think it would be good to be able to test the controllers in the .net core part of the application. 

If you are looking for an example, step one at the link below would give you an indication of what Im after.

http://www.stefanhendriks.com/2016/04/29/integration-testing-your-dot-net-core-app-with-an-in-memory-database/

**Comment by nicwillemse** [comment]
@SteveSandersonMS im not able to reopen the project.

**Comment by SteveSandersonMS** [comment]
> im not able to reopen the issue.

Oh, sorry - I thought the original poster had that option.

> I think it would be good to be able to test the controllers in the .net core part of the application

Aha, now I understand! Thanks for the clarification.

I do agree with you in principle that people will want to do integration tests on things like API endpoints. However it's somewhat separate from the goals of this template. If this template had integration tests for MVC controllers (etc.), then by that logic *all* the built-in ASP.NET templates should do so too, as it's equally relevant for them. But we strive to keep the templates relatively focused on one subject, and unopinionated about other subjects. There are lots of possible ways of integration-testing controllers, and there are lots of business scenarios where you wouldn't want to at all. So I don't think we'll bake that into the default SPA templates in the immediate future - something like blog posts are a preferable solution to guide people to setting up their choice of integration testing mechanism if they want one. Otherwise, if we add examples of doing many different things by default, the template becomes overwhelming to people trying to make sense of it all. Hope that's OK!

**Comment by nicwillemse** [comment]
Thanks @SteveSandersonMS I agree with your finding and happy to support that. 

> I'm not certain why standard approaches wouldn't work. Your API endpoints in a SPA are exactly the same as API endpoints in any other application.

Im currently not able to test as it fails to start the application up for testing because of the dependency on the node modules. 

I have created a test file if you would like to have a look for yourself - Its entirely possible that Im doing something wrong here. 


```
namespace Tests
{
    public class ControllerTest 
    {
        public TestServer server { get; }
        public HttpClient client { get; }

        public ControllerTest() {
            var builder = new WebHostBuilder().UseStartup<Startup>();
            server = new TestServer(builder);
            // client = server.CreateClient();    
        }

        [Fact]
        public async void TestVisitRoot() {
            // var response = await client.GetAsync("/api/Invoice/RetrieveInvoices");
            // response.EnsureSuccessStatusCode();
        }
    }
}
```

**Comment by SteveSandersonMS** [comment]
I'm not certain what aspect of your testing framework has trouble with hosting the application (it is just a .NET Core application, even if it starts a Node.js process) - if you're able to track that down and think it's a bug in NodeServices please let me know!

In the meantime, if you're only trying to invoke `/api` endpoints and hence don't need the Node aspect of your application during these tests, you could just use something like an environment variable to make it skip running `UseWebpackDevMiddleware` or whatever is triggering the problem while running integration tests.

**Comment by nicwillemse** [comment]
@SteveSandersonMS im really only going to need it for the endpoints for the time being, so will simply skip `UseWebpackDevMiddleware`

Thanks for your assistance and good work!
