### ISSUE TITLE
Why put dist inside ClientApps?

### ISSUE THREAD

**Issue by ManuelDeLeon** [aspnet/JavaScriptServices#510]
Sorry for the question but I don't know how else to contact you guys.

What's the rationale for putting the dist folder inside ClientApp?

I'm modeling our folder structure based on yours and it seems like the right place to put dist is at the root of the project (`/dist` or maybe `/ClientDist`), not inside ClientApp. That leaves `ClientApp` as the equivalent of `src` (with the source files).

**Comment by SteveSandersonMS** [comment]
I agree that aspect of the naming is a bit weird.

The typical top-level `src`/`dist`/`test`-type split is great for pure front-end apps, but doesn't really work for ASP.NET projects because ASP.NET has such strongly reinforced conventions about "source" being a top-level thing, "dist" going into `wwwroot`, and "test" being in some completely separate place (e.g., a different .NET class library project).

Having `/dist/` or `/ClientDist/` as top-level items would both be a bit weird too (`/dist/` implies it's the built output of the whole project, when it isn't - it's only the SPA code, and `/ClientDist/` implies it's code to be distributed to the client, but it isn't - that code only runs on the server).

The most convincing suggestion I've heard so far would be just renaming `ClientApp` to `AngularApp`/`ReactApp`/etc., because it totally makes sense to publish `/AngularApp/dist` to your production server. We might do that if more people call for it (and of course, you can just rename it in your project if it's what you want now).

Anyway, I hope that answers your question!
