### ISSUE TITLE
Error deploying to Windows Server

### ISSUE THREAD

**Issue by NeilIrvingMacc** [aspnet/JavaScriptServices#523]
Hi Guys

I have followed the excellent Angular2 tutorial and converted my Angular2 project from SystemJS to the Angular2 .net core template.

I have done a publish and deployed the files, on going to the website root I get the following, I have also deployed the node_modules folder too and its 6k+ files!

Win32Exception: The specified executable is not a valid application for this OS platform.
StartCore
Start
Start
LaunchNodeProcess

Any help would be appreciated

Thanks

Neil

**Comment by hheexx** [comment]
You start it with "dotnet <path to s.dll>" ?

**Comment by NeilIrvingMacc** [comment]
I simply browsed to the website over the internet as its on a hosted machine, do I need to run the above command first on the web server?

**Comment by NeilIrvingMacc** [comment]
If I run the above command on my laptop in the bin/release/publishoutput directory it works fine I can then browse to http://localhost:5000/Home and the website comes up fine

**Comment by LovedByTheLord** [comment]
The error is occurring when it is trying to start the node.exe process (for prerendering).  Have you rebooted the machine since you installed Node?  I had a similar error after I installed Node the first time and tried to browse to my web site.  The Path environment variable had been modified by the node installation but wasn't being picked up by IIS until I rebooted (you could probably do a "iisreset" also).

**Comment by hheexx** [comment]
And on server it's behind IIS?
Then it's probably something wrong with IIS integration or IIS configuration.
I don't have experiance with that so I can't help you..

**Comment by NeilIrvingMacc** [comment]
@LovedByTheLord I traced this through and it was because I did not reboot after installing Node.  Cheers for everyone's help
