### ISSUE TITLE
Any consideration for VueJs template?

### ISSUE THREAD

**Issue by waynebrantley** [aspnet/JavaScriptServices#524]

**Comment by holmescn** [comment]
I think the community could do it. Just fork and modify the ReactJS template.

**Comment by MarkPieszak** [comment]
Here's one: https://github.com/MarkPieszak/AspNETCore-Vue-starter

I just made one public that utilizes Core, webpack, server side rendering, etc with Vue.
Steve has said they can't add anymore templates to this repo, as it's even more to maintain. See here: #412 

It's basic at the moment, but it has some of the key parts, and more will come soon! 

Hope that helps :)
@waynebrantley @omar-ballerani

**Comment by waynebrantley** [comment]
@holmescn I agree the community can definitely do this...and starting with ReactJS is a good start.  So based on #412 the question is would they accept a pull request of this template?

**Comment by MarkPieszak** [comment]
I can talk to Steve, but either way my goal was to just get it up to par with the identical ones in this repo, that way it's less for him and the aspnet team to worry about. Whatever works for you guys.

**Comment by waynebrantley** [comment]
@MarkPieszak Either way...glad you are building!

**Comment by holmescn** [comment]
I thought we can create a new repo and generator named `aspnetcore-spa-plus` that separated from this repo, and add whatever we want. Since the team already do such a good job, we should not force them to do more. I will check the license about the template. Hopefully, they are under MIT license. Then I will copy all template and create a new yeoman generator that contains original templates and try to add VueJS support.

**Comment by SteveSandersonMS** [comment]
Thanks everyone here!

The `aspnetcore-spa-plus` generator sounds great. Looking forward to seeing that.

By now we've had so many requests for a VueJS template that I think we could consider including it in `generator-aspnetcorespa` if there was still demand for that and if it turns out to work cleanly, but I personally won't be focused on that until February at the earliest.

**Comment by amivit** [comment]
Perhaps remove/stop updating one of the lesser popular frameworks, in favor of Vuejs? Support for it would really be lovely. Right now for my own project, I'm just avoiding .cshtml and just using asp.net core for my REST-apis & data models because I don't know how to properly integrate npm+webpack+vue (bower package is old version). 

I realize it's inspired from Angular and Microsoft seem pretty invested in that, however it's just so much simpler & lightweight in comparison https://news.ycombinator.com/item?id=12757946

**Comment by MarkPieszak** [comment]
If you're not integrating it with .NET at all then it wouldn't be like these templates then.
 You could just have a front-end only project in your solution that is a normal vue webpack (or whatever you want) project. All of its Http calls would point to the port of your web API. Wouldn't that be what you're looking for? @amivit

**Comment by amivit** [comment]
Well I would love to integrate razor + controllers + view models, etc, into my vue-enhanced views. I could do that, and I appreciate the suggestion, but I'm still relying on ASP.NET MVC 6 for creating my Api's, so I simply jquery load my static html with vue into a view page for now.

**Comment by alexsandro-xpt** [comment]
#389 #412

**Comment by vip32** [comment]
+1 for a vue.js 2 (webpack/typescript/ssr/hmr/router)
vue is such a nice low entry app framework (like knockout), it's also very popular so it could make sense to add this to the core templates.

**Comment by MarkPieszak** [comment]
I have most of that here https://github.com/MarkPieszak/aspnetcore-Vue-starter
Very minimal starter for now.

TypeScript isn't very popular with Vue. @vip32

**Comment by vip32** [comment]
Hi @MarkPieszak,
TS is indeed not very popular with vue, however mentioned on the official page. but yeah all docs/trainings are using es6. will you then stick with es6 in your vue-starter? 

would also be nice if this vue-starter can be added to 'dotnet new'. not sure how to do that and what still needs to be done.
will you accept PRs to get this more up to par with the other starters?

**Comment by MarkPieszak** [comment]
Yes it would be great to have some collaborators it's tough tackling multiple projects at once. Help would be most appreciated! @vip32 

I wasn't sure, I didn't know how the community felt about TS with it (although me personally, I have no idea why anyone *wouldn't* use TS 😜 , it's incredible).

I definitely wanted to get that one in `dotnet new` once it's more polished! As well as the .NET Angular Universal I have, want to update styling and clean up a few things there.

**Comment by vip32** [comment]
Hi @MarkPieszak, here are some updates
https://github.com/MarkPieszak/aspnetcore-Vue-starter/issues/11

**Comment by anderly** [comment]
@SteveSandersonMS we've got @MarkPieszak's [AspNetCore Vue2 starter project](https://github.com/MarkPieszak/aspnetcore-Vue-starter) to a pretty good point now using ES6 at this point and pretty much on par with the core templates. We're looking at a separate template with typescript.

**Comment by SteveSandersonMS** [comment]
Anyone who's watching this issue and is particularly keen that we add a Vue template, please look at PR #753 and comment there about whether this is what you're looking for. Thanks!

**Comment by SteveSandersonMS** [comment]
Also I'll close this now since it's superseded by #753.
