### ISSUE TITLE
How do I use angular2-jwt library ?

### ISSUE THREAD

**Issue by sergeu90** [aspnet/JavaScriptServices#525]
I added angular2-jwt and I want to use but I am getting error  localStorage is not defined

**Comment by etimesg** [comment]
@sergeu90 AFAIK this is because angular2-jwt still don't support Angular Universal. You can follow the details here: https://github.com/auth0/angular2-jwt/issues/30

In any event, I'm using angular2-jwt with JavaScriptServices by postponing the JWT validation until the client-side kicks in. The way I achieve this is by skipping the `isLoggedIn` _(my canActivate method)_ validation when localStorage is undefined.

My particular use case allows me to return true (logged) from the server-side and wait for the client-side to perform the JWT validation and retrieve the data from the API. The problem with this solution - _whether you are returning true or false for server-side isLoggedIn calls_ - is the same from the alternative mentioned at the angular2-jwt issue page.

> What I don't like about this though is when the app loads and they are logged in the app will show the not logged in state until the client side kicks in

I understand this is not the ideal solution, and it's not even related with JavaScriptServices, but I'm sharing it here in case you want to give it a try before this issue is closed.

**Comment by sergeu90** [comment]
thanks,issue can be close
