### ISSUE TITLE
Roadmap for this Project

### ISSUE THREAD

**Issue by sebald** [aspnet/JavaScriptServices#537]
Hi,

This is not an issue with the project, but rather a meta question. Hope this is the right place to ask.

I was wondering what the ASP.NET team wants this project to be. Is/should this grow into a go to boilerplate when starting a SPA app with a .Net backend? Or should this show best practices for the community when working with JavaScript framework x and .Net core? Should this grow into a community standard like the `ember-cli`?

I am asking because currently it seems like @SteveSandersonMS is the only one maintaining this project and keeping up with all the supported frameworks seems to be a lot for one person. I am not saying he isn't the right person to do this (on the contrary)! It's just a ton of work and keeping up with the progressions of all the frameworks. E.g. I  noticed that some frameworks already have support for testing (Angular) but some don't (React).

So the *tl;dr;* is: Is this an official supported MS project that may gain additional resources in the future? Will this be promoted a lot by the ASP.NET team?

**Comment by MarkPieszak** [comment]
I contribute whenever I can, but it seems to me that this repo is more about getting someone up and running, and showcasing a few important things, like some of the really tough things, such as the newer build systems, typescript setup, server-side rendering, etc. 

This way someone really has their foot in the door, and if they want to add X or Y from whatever framework it's just as easy to do themselves.

But that's just what I've gathered, curious what the aspnet team thinks!

**Comment by SteveSandersonMS** [comment]
The ASP.NET team's plan is for the core NuGet packages (NodeServices, SpaServices) to ship as fully-supported parts of ASP.NET Core very soon. This gives ASP.NET Core the ability, in general, to take advantage of any Node-based functionality that developers want, and works with any third-party SPA framework.

As for the project templates, we have not committed to any particular shipping plan, mainly because:

1. The JS ecosystem moves so fast, with frameworks coming into and out of fashion on a monthly basis, that it risks disappointing customers if we put too many of them into Visual Studio and they quickly cease to be relevant or modern, and...

2. Since they are *templates*, the whole concept of "support" is totally different (you only need us to support it at the point you first create your new project, as beyond that it's your own thing and Microsoft can't change how your project works), so there's much less of a reason for customers to need us to officially "ship" templates. Just having them on GitHub/yeoman/etc is mostly enough.

Now, it might be that we do officially put some specially-chosen template inside VS itself at some point (and the obvious candidate is the Angular 2 template), but we're not promising that right now, and really it shouldn't matter all that much to you for the reasons given in point 2 above.

> I am asking because currently it seems like @SteveSandersonMS is the only one maintaining this project and keeping up with all the supported frameworks seems to be a lot for one person
> So the tl;dr; is: Is this an official supported MS project that may gain additional resources in the future? Will this be promoted a lot by the ASP.NET team?

You're correct: I am currently the primary maintainer inside the ASP.NET team for this project, but nonetheless it is owned by the ASP.NET team and we may put other devs to work on it as the need arises. It depends on how much customer demand there is for this (relative to other parts of ASP.NET).

As for "Will this be promoted a lot by the ASP.NET team", I hope so, but TBH right now most of the ASP.NET team is so focused on building an amazing server-side stack that they don't have time to be experts in Angular/React/Webpack/etc at the same time. Keep talking about it whenever you interact with the ASP.NET team, and it will climb up the priority ladder.

At the same time, this really is a regular open source project where we can take contributions and even long-term strategy from anyone with great skills and ideas. @MarkPieszak has made some great contributions, as have others. So in a large part, the community here can control its own destiny :)
