### ISSUE TITLE
Updating to Angular 2.4

### ISSUE THREAD

**Issue by beckmx** [aspnet/JavaScriptServices#539]
Hello, I created a project with the generator and angular 2, and now I need to update the angular framework, I already did this by updating the packages in the project.json but at runtime a very strange error says angular.version is not a function, any idea on how to update angular correctly?

**Comment by MarkPieszak** [comment]
Unfortunately right now Universal (the server side solution for Angular) can't go above 2.1.0. There are some workarounds but they only get you to 2.2. 

We will be moving the core of Universal into AngularCore sometime early 2017, which will be a good thing, because they will always be aligned, and even more performant! 

Apologies for any delays!

**Comment by hheexx** [comment]
Thanks for some feedback Mark!

I started to get really scared when I look at commit list at angular-universal. Just a few commits per month.
Can you give us some link where we can follow the process?

Can we except a lot of breaking changes?


I have an almost ready application that I have to ship in next month based on this template.
And Angular i18n tool that I need does not work here.

I need to make a decision soon to implement custom i18n solution or wait.

**Comment by MarkPieszak** [comment]
Yes, we've slowed down with commits as we've been waiting for the merge over to Core for the inner bits of Universal. (There will be plenty of other things that stay in the Universal repo, express-engine, etc etc). Nothing to worry about a lot of people are on holiday right now (from Core etc), so after the holidays things will start ramping up slowly when we figure everything out.

The biggest goal is to maintain the same/similar function signature, so that really only the internal aspects change for better performance & integration into Core itself.  I hope the biggest change will be importing from `@angular/universal`. :)

Here is where we have the official issue for the big merge: https://github.com/angular/angular/issues/12495

For i18n I'd suggest ng2-translate, that can work Universal-y on the server-side as well. (https://github.com/ocombe/ng2-translate)

**Comment by dguisinger** [comment]
Mark, will the merge over to Core happen as part of 4.0 or will it still happen for 2.x?  Is there going to be a solution for Universal on 2.x beyond 2.2.0?   I spent hours this weekend trying to get it to work, but kept getting a "Uncaught TypeError: _angular_core.Version is not a constructor" error and all of my event bindings weren't firing, moving back to 2.2 fixed it and I've just assumed it is a conflict between 2.4.1 and the current Universal builds...

**Comment by MarkPieszak** [comment]
@dguisinger The Universal merge will be part of 4, I don't believe there will be anymore 2.minor releases.

I'm on vacation but I'll try and take a look sometime and see if I can get 2.4 to work properly. I don't think it works with my workaround I have [here](https://github.com/MarkPieszak/aspnetcore-angular2-universal/blob/master/Client/__2.1.1.workaround.ts), tried real quick, but didn't have enough time to dig into the specifics just yet. I have heard that it works with the original (node-based) universal-starter, so I'm hoping it's possible!

**Comment by hheexx** [comment]
@MarkPieszak 
As per your advice I tried ng-translate but I hit this bug as soon as I imported it:
https://github.com/angular/universal-starter/issues/167

Doesn't look it works with universal.

**Comment by beckmx** [comment]
Yeah, that's why I wanted to change to 2.4, now I am writing my own
translate service, which at the end is even better because it doesnt need
dependencies.

2016-12-29 12:02 GMT-06:00 Boris Prpic <notifications@github.com>:

**Comment by MarkPieszak** [comment]
Did it work when UniversalModule was imported last? @hheexx 
I put the comment to have it first, because (usually) you want it there, but some situations it needs to go after certain modules, if they themselves override HttpModule or a few others. Let me know so I can try and help out!

**Comment by MarkPieszak** [comment]
More info on ng2-translate support here: https://github.com/angular/universal-starter/issues/263 @beckmx @hheexx

**Comment by SteveSandersonMS** [comment]
Thanks @MarkPieszak for the info here.

Closing as the original question has been answered (for now at least).
