### ISSUE TITLE
Cannot resolve module 'redux-auth/default-theme'

### ISSUE THREAD

**Issue by Tonvengo** [aspnet/JavaScriptServices#544]
Hi. I used aspnetcore-spa generator with react-redux. 
Iinstalled npm package redux-auth.
After it I updated Home. tsx file:

```
import * as React from 'react';
import { EmailSignUpForm } from "redux-auth/default-theme";
export default class Home extends React.Component<any, void> {
    public render() {
        return <div>
            <EmailSignUpForm />;
        </div>;
    }
}
```

But now I am getting error when trying to run webpack:
Cannot find module 'redux-auth/default-theme'.
Is there anything I forgot to do?
Thank you in advance.

**Comment by SteveSandersonMS** [comment]
Since you're using TypeScript, you must also provide type information, e.g., `.d.ts` files or a `@types` package.

Based on a quick search of npmjs.org, I don't see any `@types` package for redux-auth, but people are talking about it here: https://github.com/mjrussell/redux-auth-wrapper/issues/50

Closing as not an issue in this repo.
