### ISSUE TITLE
Angular2 Wallaby config for testing

### ISSUE THREAD

**Issue by bperry77** [aspnet/JavaScriptServices#553]
Has anybody successfully configured [wallaby.js](https://wallabyjs.com/) in VS code or Visual Studio using the Angular2 SPA?

I think I am close but still getting some errors.  Here is my wallaby.js config file:

var webpack = require('webpack');
var wallabyWebpack = require('wallaby-webpack');

var webpackConfig = require('./webpack.config.js')[0];

// Adjust the config as required
// webpackConfig.plugins.push(...);

var normalModuleRepPlugin = new webpack.NormalModuleReplacementPlugin(/\.(gif|png|scss|css|html)$/, 'node-noop');

webpackConfig.plugins.push(normalModuleRepPlugin);

var wallabyPostprocessor = wallabyWebpack(webpackConfig);

module.exports = function (wallaby) {
    return {
        files: [
             { pattern: 'wwwroot/dist/vendor.js', load: false, instrument: false},
             { pattern: 'ClientApp/app/**/*.ts', load: false, instrument: true},
             '!ClientApp/app/**/*.spec.ts'

        ],

        tests: [
            { pattern: 'ClientApp/app/**/*.spec.ts', load: false, instrument: true}
        ],

        postprocessor: wallabyPostprocessor,

        env: {
            type: 'browser'

        },

        setup: function () {
            // required to trigger test loading
            window.__moduleBundler.loadTests();
        }

    };
};

I get several runtime errors in the Wallaby.js console:

`[Error] Runtime error: ReferenceError: Can't find variable: vendor_d74cddb63548c1c3ebc4​​`

Any help would be greatly appreciated.

**Comment by parys** [comment]
Full rebuild getting away this error for me. I think asp.net create hash for vendor.js files. And after installing new packages hashes are not equal.

**Comment by SteveSandersonMS** [comment]
I don't know about Wallaby.js specifically, but if you get this error (or similar):

    Can't find variable: vendor_d74cddb63548c1c3ebc4​​

... it means your `.js` files don't match up with the vendor `.js` bundles (e.g., you are serving a `main.js` files that's dependent on a different version of `vendor.js` than you are serving).

To fix this, all you need to do is rebuild both the vendor and non-vendor bundles, e.g., run

    webpack --config webpack.config.vendor.js
    webpack

I'll close this since it doesn't appear to be any bug in any JavaScriptServices code, but any discussion about using wallaby.js can of course continue here if desired!
