### ISSUE TITLE
Node Services Error When Load First Time

### ISSUE THREAD

**Issue by hendrathings** [aspnet/JavaScriptServices#556]
Hi, I got throw error "Microsoft.AspNetCore.NodeServices[0] EXCEPTION: Cannot read property 'querySelector' of undefined" and so on.

My project use Asp Net Core + Angular JS. this throw error on library D3 query selector. I had struggle to find out this and eventually  I realize the web load on the first time throw this error.

Ex:
1. I create 'A' component chart base on NVD3.
2. then I load on 'A' component at home
3. run localhost:5000/home
4. I got this error.

I have try using lazy load, async component, dynamic component that always throw error. This is doesn't  make sense because I have try on angular 2 with webpack-server-dev working component and also put component on different page and working as well.

I thought was d3 lib or types issue, but it wasn't. because it was working without asp.net core.

Please help or suggest.

Thanks.

**Comment by SteveSandersonMS** [comment]
D3 is a browser-only library - it doesn't support running in Node.js. So you need to either:

 * Disable server-side prerendering entirely (remove the `asp-prerender-module` attribute from your `Index.cshtm`)
 * Or, keep server-side prerendering, but amend your TypeScript/JavaScript code so that D3 APIs are not invoked when the code is running on the server (for example, like in this comment: https://github.com/aspnet/JavaScriptServices/issues/303#issuecomment-246620724)
