### ISSUE TITLE
Do I need to include my vendor libs in webpack or just in package.json?

### ISSUE THREAD

**Issue by beckmx** [aspnet/JavaScriptServices#560]
Hello guys, I came across a misunderstanding in my current development, I setup a project to use the webpack features, however when I try to use a component that implements some JS libraries, the component crashes, I then went to the package.json and realized my packages were there but not in the webpack.config.vendor.js, I was wondering, if I must include the packages also there? and is there any cli or command that does it?

**Comment by MarkPieszak** [comment]
With the current setup, you need to put them in there, yes.
There are other ways of creating vendor bundles, such as adding a specific entry file (vendor.ts lets say), and having all your `import` polyfills/vendor things there. But that's a different setup all together. Just a fyi!

**Comment by SteveSandersonMS** [comment]
I'd say it's optional whether you put them in the vendor package list or not:

 * If you do, then when you rebuild the vendor bundle (`webpack --config webpack.config.vendor.js`), the package will go into that bundle, and will no longer be included in your own app code's bundle
 * If you don't, then when you rebuild your app code bundle (`webpack`), the third-party library will be included in that bundle

Generally if it really is third-party code, it makes sense to have it in the vendor bundle rather than your app code bundle, as it reduces build times and deployed code churn.

> I setup a project to use the webpack features, however when I try to use a component that implements some JS libraries, the component crashes

If it crashes, that suggests there is some other problem besides which bundle the code is being built into.

Closing as I think the original question is answered, but please let us know if not.

**Comment by rosieks** [comment]
@SteveSandersonMS What do you think about removing array with vendor libraries in webpack.config.vendor.js and replacing it with distinguish dependencies and devdependencies. In such case dependencies would be all vendor libraries and devDependencies would be all other libraries that are required only to build application.

**Comment by SteveSandersonMS** [comment]
@rosieks I suspect a lot of people would not like that, because `dependencies` and `devDependencies` already have specific meanings - it's not the same distinction as "vendor vs non-vendor".
