### ISSUE TITLE
Global styles with this template

### ISSUE THREAD

**Issue by Sampath-Lokuge** [aspnet/JavaScriptServices#564]
Hi,

Can you tell me how to add Global styles with this template ? I have tried like below.But it's not working.

I have added `style.css` file in this path `components/app/style.css`.After that inside the `app.component.ts` file where I have done this :

`  styles: [require('./style.css')], `

After that I have tried to use that styles on my child component and it doesn't work.Can you tell me how to do that ? Thanks.

**Comment by etimesg** [comment]
Hi @Sampath-Lokuge. I'm assuming this question is about the Angular template, otherwise, please disregard my comment.

You can modify how the application interprets styles by changing the [encapsulation](https://angular.io/docs/ts/latest/guide/component-styles.html#!#view-encapsulation) property of a component. In this particular example, you can add `encapsulation: ViewEncapsulation.None` to your app component and the styles of `./style.css` will be available to its children.

A couple of unsolicited considerations:
1. To avoid conflicts and other issues, I wouldn't have more than one component propagating its styles globally. Also, note that styles with same class inside a children component will override existing styling. There are a [couple](https://toddmotto.com/emulated-native-shadow-dom-angular-2-view-encapsulation) of [articles](http://blog.thoughtram.io/angular/2015/06/29/shadow-dom-strategies-in-angular2.html) explaining ViewEncapsulation in detail.
2. If you want to follow Angular [style guide](https://angular.io/docs/ts/latest/guide/style-guide.html), it's recommended to rename your style to `app.component.css`. 

Best,
E

**Comment by SteveSandersonMS** [comment]
Thanks for the answer, @etimesg!
