### ISSUE TITLE
Guidance for Integrating Application Insights

### ISSUE THREAD

**Issue by johnkattenhorn** [aspnet/JavaScriptServices#565]
I've found this template super-useful for getting a 1st class development experience using Angular 2.

Has anyone done a nice integration with Application Insights using Angular 2 ? I was wondering if that's something that would be useful to bring into the feature set since it's a Microsoft Service and I believe there's a typescript library now for the SDK.

I'm no Angular 2 expert but if someone could suggest an approach or has a working solution I wouldn't mind doing the spade work / PR.

**Comment by SteveSandersonMS** [comment]
I'd hope there's no unusual difficulty with adding Application Insights, though it's not something I have personal experience with. Assuming you just need to invoke their JavaScript APIs, then hopefully it's enough just to wrap them in `if (isBrowser) { ... }` blocks so that it doesn't get confused by running inside Node (where it wouldn't have access to usual browser APIs that it probably uses for reporting data, such as `navigator.userAgent`).

Example, assuming you've already installed the `applicationinsights` NPM module:

    import { isBrowser } from 'angular2-universal';
    import * as appInsights from 'applicationinsights';

    ....

    if (isBrowser) {
        appInsights.doSomething(...);
    }

Hope that gets you started. If it turns out that merely having the `import` statement for `applicationinsights` causes trouble during server-side rendering (e.g., because their code does something with browser APIs even before you invoke any of their methods), then you'd need a slightly more elaborate solution using dependency injection, e.g., like in this answer: https://github.com/aspnet/JavaScriptServices/issues/567#issuecomment-271314498

**Comment by johnkattenhorn** [comment]
Awesome, thanks for the @SteveSandersonMS - gives me something to go at.
