### ISSUE TITLE
Odd "isLoading" behaviour in Redux app 

### ISSUE THREAD

**Issue by huwjeffries** [aspnet/JavaScriptServices#569]
Hi There, 
I've been trying out ASP.NET core spa with React + Redux and I'm seeing some odd behaviour with server-side data loading. I can re-create the issue in the vanilla project template generated by yoman. Whilst not necessarily a bug, it is difficult to explain what's going on and wonder if you can shed some light?

To re-create the issue: 
npm install -g yo generator-aspnetcore-spa (gives me version 0.7.2)
yo aspnetcore-spa (and choose React with Redux)

Edit the ClientApp\store\WeatherForecast.ts and change Line 47 from:
if (startDateIndex !== getState().weatherForecasts.startDateIndex) {
to:
if (!getState().weatherForecasts.isLoading) {

i.e. Only load data if the data isn't already loading. (A sensible pattern for API calls that don't need parameters). Also comment out the "If" check on line 76, 82 & 83 in the same file. 

Edit ClientApp\components\FetchData.tsx. Delete the whole componentWillReceiveProps method (otherwise you get an infinite refresh cycle). 

Launch the site and click around - you can see the WeatherForecast data fine. Hit F5 on the WeatherForecast page and now you get a Javascript (React) error. Debugging shows that the "this.props.isLoading" property is now permanently set to True (but the weather forecast data has been loaded). It must be an oddity of server-side pre-rendering, but I can't see any code path that would result in the IsLoading flag getting stuck on True. Doubtless something going on that I'm not aware of. Any help you can give would be much appreciated. Thanks!

**Comment by SteveSandersonMS** [comment]
Thanks for the clear problem description and repro steps!

I think the issue here is that, with your updated logic, the client-side code will *always* try to fetch data when it starts up, even if the data was already fetched during server-side execution. The previous logic didn't have that issue, because if `startDateIndex` already matched the URL, it wouldn't try to load anything.

If this was an Angular app, that wouldn't be a problem, because Angular isn't strict about that. But React is strict. The initial client-rendered document *must* match the server-generated DOM exactly, otherwise you get the error (`React attempted to reuse markup in a container but the checksum was invalid`) and everything breaks down after that. So, if the server has already fetched and rendered the data, then the client has to continue from that state and can't return a "loading" UI on the first render.

If you don't need any parameters for your WeatherForecast request, and you only want to load the data once (i.e., there's no "Refresh" button in the UI), then the logic you want is something more like this (in `WeatherForecast.ts` from line 47):

        // Only load data if we haven't already got any
        if (getState().weatherForecasts.forecasts.length === 0) {

If you did want a "Refresh" button in the UI, you could add a new action (`REFRESH_WEATHER_FORECAST`) whose action creator always dispatches the action even if the data is already loaded. This would never occur during server-side rendering so wouldn't cause the same problem.

Hope that makes sense!

**Comment by huwjeffries** [comment]
Thank you - that's very helpful!
