### ISSUE TITLE
Add ResponseCompression Middleware to templates for Static Files

### ISSUE THREAD

**Issue by spboyer** [aspnet/JavaScriptServices#570]
* Enables gzip on html, css, js files.

```
        public void ConfigureServices(IServiceCollection services)
        {
            // Add response compression middleware.
            services.AddResponseCompression();

            // Add framework services.
            services.AddMvc();
        }
```

In the `Configure()` method use the middleware. Order matters, ResponseCompression must be called prior to StaticFiles or they will not be compressed.
```
         app.UseResponseCompression();
         app.UseStaticFiles();
```

Reduces default template html by ~50% in Debug mode.

**Comment by SteveSandersonMS** [comment]
I agree that a lot of people will want to do this. Though not everyone, as (for example) IIS layers on its own response compression so you don't need it in the .NET layer. So it depends on how you plan to deploy your application.

With these templates, we're trying to be consistent with the default `mvc` template in all cases where we don't specifically need to be different. The default `mvc` templates don't use `UseResponseCompression` (presumably because its relevance depends on your eventual deployment plans). So for now at least I'd prefer not to add this and retain as much consistency with the `mvc` template as possible.

Hope that seems reasonable! If you think I'm missing something important, please let me know. We can reconsider this at any time.
