### ISSUE TITLE
Prerendering failed because of error: Error: Cannot find module 

### ISSUE THREAD

**Issue by rallycar176** [aspnet/JavaScriptServices#577]
Hi,

I am relatively new to front end development and I using this as a starting template. I am trying to use the google maps ng directive - [ng2-map](https://github.com/ng2-ui/ng2-map). 

I am getting the following error:` Exception: Call to Node module failed with error: Prerendering failed because of error: Error: Cannot find module "ng2-map"`. I imported the 'ng2-module' into my app.module.ts and my ng2map-component.ts but the html template doesn't see the directive. 

Typically I would import the component into the html webpage and it would bootstrap the component but with this template the spa html page is rendered dynamically. What am I doing wrong?

**Comment by MarkPieszak** [comment]
Did you add *ng2-map* to your package.json dependencies and `npm install` it correctly?

**Comment by rallycar176** [comment]
I did. Here's the directory structure.
http://i.imgur.com/uVbpB8D.png

**Comment by KraigWalker** [comment]
Can you paste the content of `app.module.ts` & `ng2map-component.ts`?

Also, are you using Visual Studio to build your solution, or the dotnet command line/msbuild etc. ?

**Comment by rallycar176** [comment]
Here's a screenshot of app.module.ts
http://i.imgur.com/rYXvLzt.png
Here's a screenshot of galapagosmap.component.ts(ng2-map)
http://i.imgur.com/wVpoi48.png
and package.json
http://i.imgur.com/dy8reLl.png

**Comment by MarkPieszak** [comment]
https://github.com/ng2-ui/ng2-map#usage

Check out their useage guide, you should be setting that apiUrl within the constructor. Also there is no `directives` property anymore. 


```
import { Component } from '@angular/core';
import { Ng2MapComponent } from 'ng2-map';

@Component({ ... })
export class AppComponent {

  constructor() {
    Ng2MapComponent['apiUrl'] = 'https://maps.google.com/maps/api/js?key=XXXXXXXXXXXXXXXXXXXXXXXXXX';
  }
}

```

You just need to include the Ng2MapModule in your app.module.ts file:

```
import { Ng2MapModule} from 'ng2-map';

@NgModule({
  imports: [
     /* others */ 
    Ng2MapModule
  ]
 /* etc etc */
})
export class AppModule { }
```

**Comment by KraigWalker** [comment]
If that doesn't fix things. You may have an issue with typescript/babel. Try changing the value of the `"target"` key in your `tsconfig.json` file to `"es5"` instead of `"es6"` - webpack 1.x only understands es5. Webpack 2.x can handle es6 if the installed version of node supports it.

**Comment by rallycar176** [comment]
I found out that my issue was that I left it out of the declarations -
```
@NgModule({
    bootstrap: [ AppComponent ],
    declarations: [
        AppComponent,
        NavMenuComponent,
        CounterComponent,
        FetchDataComponent,
        **GalapagosMapComponent**,
        HomeComponent
```

**Comment by SteveSandersonMS** [comment]
Glad you sorted it out!

**Comment by ibrahim978976** [comment]
An unhandled exception occurred while processing the request.
Exception: Call to Node module failed with error: Prerendering failed because of error: ReferenceError: HTMLElement is not defined
at Object. (G:\RTS 3.3\RTS3.20\RTS3.17\RTS\RTS\node_modules\ag-grid\dist\lib\filter\baseFilter.js:174:31)
at Module._compile (module.js:571:32)
at Object.Module._extensions..js (module.js:580:10)
at Module.load (module.js:488:32)
at tryModuleLoad (module.js:447:12)
at Function.Module._load (module.js:439:3)
at Module.require (module.js:498:17)
at require (internal/module.js:20:19)
at Object. (G:\RTS 3.3\RTS3.20\RTS3.17\RTS\RTS\node_modules\ag-grid\dist\lib\filter\textFilter.js:29:20)
at Module._compile (module.js:571:32)
Current directory is: G:\RTS 3.3\RTS3.20\RTS3.17\RTS\RTS
