### ISSUE TITLE
[Question] Isomorphic cookies in React

### ISSUE THREAD

**Issue by baseless** [aspnet/JavaScriptServices#581]
Hi!
Im looking into some patterns for sharing local state in a React app. The library react-cookie seems to fit the bill in regards to this except for that it only seems to support express for isomorphic access.

Do you know of any function (cookie or whatever) or way which can be used to gain isomorphic state concistency in a React application hosted on net core / javascriptservices?

**Comment by SteveSandersonMS** [comment]
You can use `react-cookie` if you want. The extra work needed is to transfer the cookies from .NET into Node, and then back out of Node to .NET (or alternatively, to client-side JS).

I've posted an example here: https://github.com/aspnet/JavaScriptServices/commit/9c9892ab18e65a9aeda5e2d18266f081e495ab19 This modifies the 'counter' code so that the state is preserved in a cookie across requests, and makes the state shared across server and client.

Mostly it's pretty trivial to wire up the cookies from .NET to Node:

 * In `Index.cshtml`, use `asp-prerender-data` to pass .NET's `ViewContext.HttpContext.Request.Cookies` value into `boot-server.ts`
 * In `boot-server.ts`, populate `react-cookie` with that data.

Now any time you use `cookie.load`, you'll read the same data on both server and client.

The slightly trickier bit is handling *writes* to that data that occur during server-side rendering. If you don't need to modify that state during prerendering, you can ignore the rest of this. But if you do need that, then you could take either of these approaches:

 * In `boot-server.ts`, use `plugInCookiesFromDotNet` to catch any writes to the cookie store, and then use the `globals` part of the result to pass those written values to client-side code, that can in turn update the `react-cookie` state with them.
 * Or, instead of using `globals`, stop using the `asp-prerender-module` tag helper altogether, and instead write your own .NET code that calls `Microsoft.AspNetCore.SpaServices.Prerendering.Prerender` to get the prerendered HTML. From there, set any modified cookies on the .NET HTTP response.

The latter option is more secure if you're working with sensitive cookies (such as authentication tokens). But the first option is quicker to implement.

**Comment by baseless** [comment]
Thanks, will check it during the weekend. Im in a learning phase in regards to oauth2 and have been uncertain wether handling tokens this way would actually violate security percs, atleast of some of the flows. But i appreciate your input very much and if you had some other ways of handling this that you would recommend over for example cookie i would be very interested to know it.

**Comment by shiroganee** [comment]
@SteveSandersonMS I tried what you did (sorry for digging out this thread but it is like mirror of the thing that I wanted to ask). I've a cookie now on the node side, but my fetch call won't be having it (there is no document thing over there, and fetch takes it from there).

So right now I have a cookie, but it won't be sent in a Request - as a result the call on SSR to a Controller will differ, and when browser will recall it (as ComponentWillMount is called like 3 times) will be providing a differnet view (in the end there will be that "blink" result going on).

How I can actually attach to fetch cookies that I got through the prerender data?

**Comment by njaal** [comment]
Is the example from your [commit](https://github.com/aspnet/JavaScriptServices/commit/9c9892ab18e65a9aeda5e2d18266f081e495ab19) still working? I'm having some problems with react-cookie in boot-server.tsx

**Comment by SteveSandersonMS** [comment]
@njaal I don't know specifically, but if you track down a problem please let us know.

**Comment by njaal** [comment]
I guess it might work if I force version 1.0.4 of the react-cookie, but when I use the latest 2.something - it seems to be completely changed https://github.com/reactivestack/cookies/tree/master/packages/react-cookie/src
