### ISSUE TITLE
An error occurred while processing your request in AWS Elastic Beanstalk 

### ISSUE THREAD

**Issue by raberana** [aspnet/JavaScriptServices#584]
I deployed the default example template of Angular2 to an AWS Elastic Beanstalk server. However, loading the site only shows an error without no further details.
![untitled](https://cloud.githubusercontent.com/assets/3053739/21954128/e70dd382-da83-11e6-8d1a-48800ad2874c.png)

Where can I look for further logs (AWS gave no error logs, event viewer does not show error logs)?
Should I install something else in the EC2 instance to make this run?

**Comment by AndrewKralovec** [comment]
@raberana Hey buddy, i managed to run my app on my AWS. 
Ill just explain how i got my app on my EC2 instance and hopefully it will help you out.<br>
   
Since asp.net core is cross platform, go ahead and set up a Linux, I recommend the ubuntu server, EC2 instance. You can find lots of stuff online on how to do this if you are unfamiliar with how to do this( this video on youtube is basically what we will be doing but using asp.net core instead of node.js [Node.js on AWS](https://www.youtube.com/watch?v=WxhFq64FQzA&t=7s)) . 
Once you have your instance running, go ahead and install all the packages that you need to run an asp.net core app, Angular2 and whatever you are going to use to push your project to the server (git, ssh, ftp, etc).
- npm
- webpack
- mono
- dotnet 

Finally once your instance is now able to run your project, push your project to the instance, build it and run it. Your last steps are now optimizing the instance to run on your project.  Things like rerouteing the IP tables, running your project in the background, ect. If you have any questions or problems, let me know. 


I had an issue similar to this and @SteveSanderson  helped me fix it. 
[#299](https://github.com/aspnet/JavaScriptServices/issues/299)

**Comment by raberana** [comment]
@AndrewKralovec thanks man. i appreciate your reply :) however, for now, i dont have the luxury of time to learn and setup a Linux environment. I need to have a running application as soon as possible so I decided to deploy it first in Windows. But I will follow your advice as soon as i get it running.

Fortunately, I solved the issue. I forgot my EC2 instance doesn't have a node.js installed. After installing that, everything worked fine :)
