### ISSUE TITLE
Issue with react and special characters

### ISSUE THREAD

**Issue by jordanDruart** [aspnet/JavaScriptServices#585]
Hello, I have an issue with rendering Chinese characters or event simple french accent with React.
Instead the page is rendering ����.

I don't know were this issue come from. However by using simple react projet characters are properly rendering...

Thanks.

**Comment by MarkPieszak** [comment]
This sounds like something the Redux SSR is doing, might be worth asking here for advice on it? https://github.com/reactjs/redux/issues

**Comment by SteveSandersonMS** [comment]
Also check that when you save your source files, you're doing so in UTF-8 encoding rather than anything less universal such as Windows-1252.

Closing as it doesn't appear to be a bug in this repo. But if you think there is something wrong with the libraries or templates in this repo, could you please repost with repro steps? Thanks!

**Comment by jordanDruart** [comment]
@SteveSandersonMS  . 
Thanks a lot. Actually the initial file in the project are not correctly saved in UTF-8. I tried creating another new file it work perfectly. Sorry I didn't think about it before asking.
