### ISSUE TITLE
Webpack 2.0

### ISSUE THREAD

**Issue by tutok** [aspnet/JavaScriptServices#596]
Did anyone tried to use webpack 2? any experience with?

there is couple packages like `aspnet-webpack-react` or `aspnet-webpack`, will these work with webpack 2?

**Comment by KraigWalker** [comment]
Right now webpack 2 is released under the `@beta` tag for the next week, so might be something to start looking into next week when it moves to the main release?

**Comment by MarkPieszak** [comment]
Now that it's been officially released it'd definitely be worth adding. I believe Steve was waiting purposely for the release as the Beta versions kept having breaking changes.

I've managed to setup Webpack2 here in an .NET Core & Angular repo: https://github.com/MarkPieszak/aspnetcore-angular2-universal there are just a few relatively minor changes you have to make to the webpack configs otherwise it's relatively painless. (I need to update mine to the official 2.0 release it's still using a beta one at the moment).

Otherwise everything else (aspnet-webpack) seemed to work great with it!

**Comment by SteveSandersonMS** [comment]
> Now that it's been officially released

Has it? `npmjs.org` still shows 1.14.0 as the latest production release. If I'm missing something, please let me know.

We will update the templates to Webpack 2 when it ships. For anyone who wants to use it earlier, @MarkPieszak's repo will be helpful. Or see the Aurelia template that already depends on Webpack 2.1.0 beta. It's not very difficult to update; mostly your existing configs will just work :)

**Comment by cecilphillip** [comment]
Yea, it released, not sure why it's not showing correctly on NPM https://github.com/webpack/webpack/releases/tag/v2.2.0

Maybe @TheLarkInn knows why ?

**Comment by c1rus** [comment]
https://medium.com/webpack/webpack-2-2-the-final-release-76c3d43bf144#.rqjqmbs8y

**Comment by MarkPieszak** [comment]
When you do `npm show webpack@* version` you'll see 2.2.0 there.
2.0 & 2.1 only had beta releases, leading up to **2.2.0**

Here are the most recent ones:
```
webpack@1.14.0 '1.14.0'
webpack@2.2.0 '2.2.0'
```

As Steve was mentioning I have it set up here in my somewhat add-on repo to this one: https://github.com/MarkPieszak/aspnetcore-angular2-universal/blob/master/package.json#L122

There aren't too many changes you need, mainly that your loaders need `-loader` at the end, they can't just be `json`, but now need to be `json-loader` (as an example).

Also, your `resolve: [ '' <-- ]` can't have an empty string, so change it to `['.js', '.ts']`

Hope that helps explain things!

**Comment by TheLarkInn** [comment]
We likely are actually moving it to latest tag so keep your eyes peeled. 😏

**Comment by MarkPieszak** [comment]
Oh no, what happened Sean 📦  lol @TheLarkInn

**Comment by TheLarkInn** [comment]
Nothing everything is fine. We plan to move webpack 2.2 from @ beta to @ latest today as mentioned in our initial announcement
