### ISSUE TITLE
Issue with creating server render app file and exporting createServerRenderer function

### ISSUE THREAD

**Issue by peterlazzarino** [aspnet/JavaScriptServices#611]
Hey, I am trying to get server rendering set up on my existing react web app and ran into an issue I'm not sure how to get around. I set up my server js file very similarly to the boot-server here https://github.com/aspnet/JavaScriptServices/tree/dev/templates/ReactReduxSpa/ClientApp

I'll paste code below. When I run this with a div that it should render in -> 
    <div id="react-app" asp-prerender-module="./wwwroot/app-server"></div> I get the following message.  **The module at ./wwwroot/app-server does not export a default function, and you have not specified which export to invoke.** I know it sees the file since it has given me other errors for references inside the file but I need some help to see if this is a bug or something on my end. 

```import * as React from 'react';
import { Provider } from 'react-redux';
import { renderToString } from 'react-dom/server';
import { match, RouterContext } from 'react-router';
import { createServerRenderer } from 'aspnet-prerendering';
import { store } from './store';
import routes from './routes'

export default createServerRenderer(params => {
    return new Promise((resolve, reject) => {
        // Match the incoming request against the list of client-side routes
        match({ routes, location: params.location }, (error, redirectLocation, renderProps: any) => {
            if (error) {
                throw error;
            }

            // If there's a redirection, just send this information back to the host application
            if (redirectLocation) {
                resolve({ redirectUrl: redirectLocation.pathname });
                return;
            }

            // If it didn't match any route, renderProps will be undefined
            if (!renderProps) {
                throw new Error(`The location '${ params.url }' doesn't match any route configured in react-router.`);
            }

            // Build an instance of the application
            const app = ( 
                <Provider store={store}>     
                    <RouterContext {...renderProps} />
                </Provider>
            );

            // Perform an initial render that will cause any async tasks (e.g., data access) to begin
            renderToString(app);

            // Once the tasks are done, we can perform the final render
            // We also send the redux store state, so the client can continue execution where the server left off
            params.domainTasks.then(() => {
                resolve({
                    html: renderToString(app),
                    globals: { initialReduxState: store.getState() }
                });
            }, reject); // Also propagate any errors back into the host application
        });
    });
});





 `

**Comment by peterlazzarino** [comment]
I have verified that my bundled file has an this function being assigned by exports.default

**Comment by SteveSandersonMS** [comment]
How are you compiling that TypeScript source code? Since you want this to run in Node (for server-side prerendering), you need to build it as a Node-style CommonJS module.

For example, if you're building it with TypeScript and `ts-loader`, then you'd need to include some options like these in your Webpack config:

```
{
    ... your other Webpack config options, plus:
    target: 'node',
    output: { libraryTarget: 'commonjs', path: path.join(__dirname, /* path to your output dir here */) }
}
```

For more details, please see the Webpack build configs in the templates in this project.

You can check you're building and exporting your boot function correctly using Node on the command line:

```
cd yourprojectdir
node -e "console.log(require('./ClientApp/dist/main-server'))"
```

Of course, change the 'require' module path to match the compiled module you're trying to execute. The output should be either:

```
{ default: { [Function: resultFunc] isServerRenderer: true } }
```

... or:

```
{ [Function: resultFunc] isServerRenderer: true }
```

This shows that your module really does export a default server-rendering function in a form that Node can load. If that works, you can go a step further and try executing prerendering on the command line manually with Node:

```
cd yourprojectdir
node -e "require('./ClientApp/dist/main-server').default((err, result) => console.log(result.html), '/', {}, 'http://example.com/', '/')"
```

Hope this helps. I'll close this since it's a support request rather than a bug or feature, but please feel free to post further comments to this issue if you need.

**Comment by peterlazzarino** [comment]
I am actually not using TypeScript, do I need to to use these pre-rendering scripts?

**Comment by SteveSandersonMS** [comment]
No. If you're not using TypeScript, then I guess you must be using Babel. The same advice I posted above applies; just substitute "babel compilation" for "TypeScript compilation".
