### ISSUE TITLE
Remove Typescript

### ISSUE THREAD

**Issue by nicolasdelfino** [aspnet/JavaScriptServices#614]
Hi and thank you for this resource!
I was wondering if there´s an easy-ish way of getting rid of typescript and just use js?

**Comment by SteveSandersonMS** [comment]
There's nothing special built into these templates to enable that, but in general, TypeScript is mostly a type-annotated version of ES2016/17, so you should be able to go through the `.ts` source files in your project (there are only about 10 of them), strip out the TypeScript annotations, and rename the file to `.js`. You'll also need to remove `ts-loader` from the Webpack config, of course, and replace it with something like `babel-loader` since you'll need to transpile your ES2016/17 code to ES5 for typical browsers.
