### ISSUE TITLE
Error: Unexpected value 'TruncateModule' imported by the module 'AppModule'

### ISSUE THREAD

**Issue by Ciejaa** [aspnet/JavaScriptServices#618]
Hi,

I would like to use   \[ng2-truncate](https://www.npmjs.com/package/ng2-truncate) but I'm getting an error: 

> Exception: Call to Node module failed with error: Error: Unexpected value 'TruncateModule' imported by the module 'AppModule'

Here's some part of my code:

_package.json_
`"ng2-truncate": "^1.3.2" -> added in dependencies section`

_app.module.ts_
```
import { TruncateModule } from 'ng2-truncate';
@NgModule({
    bootstrap: [AppComponent],
    //more components
    imports: [
        UniversalModule, // Must be first import. This automatically imports BrowserModule, HttpModule, and JsonpModule too.
        TruncateModule,
       //more modules
    ]
})
```

_webpack.config.vendor.js_
```
...
    entry: {
        vendor: [
            ...
            'ng2-truncate',
           ....
        ]
..
```

Do you know what it's wrong?

**Comment by SteveSandersonMS** [comment]
Yes, it's because `ng2-truncate` declares a dependency on Angular 2.4.3+ (see https://github.com/yellowspot/ng2-truncate/blob/master/package.json#L61), whereas your project is using an older version of Angular. I'm not sure if they have a good reason for doing that, but I just tweaked their source (in my `node_modules` dir) to have a dependency on Angular 2.0.0+ and it seemed to work fine.

Some ways you could deal with this:

 * Update your application to Angular 2.4+. The reason the templates aren't already on 2.4+ is because that's not compatible with server-side prerendering. So now you have two sub-options:
   * Try to persuade the Angular / Angular Universal folks to release an update where server-side prerendering does work with 2.4+
   * Or, disable server-side prerendering (remove the `asp-prerender-module` tag helper from your `Index.cshtml`)
 * Or, try to get the `ng2-truncate` people to change their declared dependency version to 2.0.0+. It's perfectly possible that they have no real need to depend on 2.4+ and have only declared that version dependency arbitrarily. If they could work with 2.0.0+, then they should declare that as the dependency version.

**Comment by consigliory** [comment]
using this workaround it should be possible still have server side rendering enabled https://github.com/MarkPieszak/aspnetcore-angular2-universal/blob/master/Client/__2.1.1.workaround.ts right?

**Comment by SteveSandersonMS** [comment]
@consigliory I don't know whether that only works with 2.1.1 or whether it works with all newer versions (including 2.4.2) - perhaps @MarkPieszak could comment on that.
