### ISSUE TITLE
Error when running in Visual Studio 2015

### ISSUE THREAD

**Issue by garybushey** [aspnet/JavaScriptServices#624]
If I create a new project using aspnetcore-spa it works fine when I use the command line, "dotnet run" to run it but when I run it in VS2015 I get an error:  "Javascript critical error at line 691, column 24 in http://localhost:1261/dist/main-client.js?v=5-LKigqyf5uDFrSFDzUAPlR9CPvPDRagTb0x-mGjM4M\n\nSCRIPT1003: Expected ':'"

No idea what the issue is since I am just running this without any changes

**Comment by SteveSandersonMS** [comment]
This is to do with running it in Internet Explorer, not with whether you launched it from VS or the command line. It's was a bug recently introduced into `webpack-hot-middleware`: https://github.com/glenjamin/webpack-hot-middleware/issues/165

Fortunately, this was just fixed by @glenjamin 5 minutes ago. Thanks @glenjamin! :)

@garybushey Please update to `webpack-hot-middleware` version 2.16.1 to get the fix (or re-fetch all your NPM dependencies and you'll get the latest version automatically).
