### ISSUE TITLE
open graph meta tags is inserted inside of the body.

### ISSUE THREAD

**Issue by consigliory** [aspnet/JavaScriptServices#629]
Hi. When I create meta tags (og:image ect.) but this tags is created inside of <body> but it should be inside of <head>. I see it make sense because it makes root of app and it is already in the body. Could you suggest how can I insert meta open graph tags in the head?
Thanks

**Comment by SteveSandersonMS** [comment]
It's difficult at the moment - you have to do something like the technique shown here: https://github.com/aspnet/JavaScriptServices/issues/384#issuecomment-275359062 That approach lets you run the server-side prerendering in a controller, so that your `boot-server.ts` can return arbitrary extra data values that you can pass to your MVC view.

It will get easier when we implement #607. Until then you'll need to either follow the approach I linked above (which is quite a bit of code unfortunately) or disable server-side prerendering.
