### ISSUE TITLE
Angular 2 docker deployment throw prerendering error

### ISSUE THREAD

**Issue by hendrathings** [aspnet/JavaScriptServices#633]
I got issue when try deploy to docker.
I run  `dotnet publish` which 
```bash
"scripts": {
    "prepublish": [ "npm install", "npm run build:vendor", "npm run build:prod" ],
    "postpublish": [ "dotnet publish-iis --publish-folder %publish:OutputPath% --framework %publish:FullTargetFramework%" ]
  }
```
In my image, I copy publish folder to container. (`FROM microsoft/dotnet`)
When I run container which is `CMD dotnet myapp.dll`, it's throw error prerendering.
I had no idea with this issue. 

any suggest? any advise?

Of course, I have try add node_modules and webpack config to container, but that is not best practice delivery with node_module since we have bundle webpack. Anyway not working, throw another error with need more add source typescript. nonsense.

**Comment by SteveSandersonMS** [comment]
Hi. I'm afraid I don't know what's wrong in this specific case, since I don't know exactly what you've included in your docker image, or what the underlying exception is. You could find out what the underlying exception is by running your application with `UseDeveloperExceptionPage`: https://docs.microsoft.com/en-us/aspnet/core/fundamentals/error-handling#configuring-a-custom-exception-handling-page

A futher thought, though: If you're trying to use docker for production deployment, please note that the templates already contain a working `Dockerfile`. If you build your docker image from this, it already works. I'm not sure what's different about the way you are building your docker image.

I'll close this because it doesn't sound like a bug (it sounds like an issue with your custom docker image). However, if you track this down futher and discover something you think is an issue in any of the code here, please let us know!

**Comment by MarkPieszak** [comment]
@hendrathings Are you using an old build of the template? I've seen this in the past. Does your webpack.vendor contain a client & server bundle? The server bundle should have `vendor: ['aspnet-prerendering']` in there, if not then you may be using an old version of the template.

**Comment by hendrathings** [comment]
@MarkPieszak Ah, right. I found that server.ts need to compile as well then use asp-prerendering with compiled. I realize that old template. Thanks.
