### ISSUE TITLE
Error with new project (0.8.1 - React/Redux - csproj)

### ISSUE THREAD

**Issue by docrinehart** [aspnet/JavaScriptServices#636]
After updating the yo generator, I loaded the project up in VS2017 RC3 and try to run.

I get Visual Studio Error: "The IIS Express settings are missing the App Url property. This is required to configure IIS express to run the site."

![doc_dev](https://cloud.githubusercontent.com/assets/5891405/22495652/1915d8fc-e808-11e6-93ce-d1b6ee2db404.png)

I was able to fix it by adding "launchUrl" with an empty string under Properties/launchSettings.json
```
...
  "profiles": {
      ...
      "IIS Express": {
         "launchUrl": "",
   }...
```

**Comment by docrinehart** [comment]
Taking a closer look, it seems the launchSettings.json gets created by VS 2017 either when I loaded up the project or tried to run it.

**Comment by SteveSandersonMS** [comment]
As per your comment, it's VS's role to create the `launchSettings.json` file if it wants one, since that is a VS artifact and is not needed for other development environments.

If you can repro the scenario where VS fails to create it at the right time, could you please provide repro steps, and preferably report it to the VS folks? You can use the "Send Feedback" button at the upper-right corner of the VS2017 window. This will automatically send other critical information, such as build numbers, logs, etc.
