### ISSUE TITLE
Framework / SDK Version / Tools confusion

### ISSUE THREAD

**Issue by pierslawson** [aspnet/JavaScriptServices#639]
I presume this is all down to the version hell that has descended upon all .Net developers attempting to use core, but I can't get a generated Aurelia project to run. 

I don't have VS2017 installed so picked the "project.json" option. This generated a global.json which pointed to SDK version 1.0.0-preview2-1-003177. On opening the project in VS2015, it complained that version was wrong. I manually changed global.json to point to 1.0.0-preview2-003131 and VS2015 stopped complaining, but the app did not run. 

So I went to [](https://www.microsoft.com/net/download/core) to get the latest VS2015 version of the tools. This did not update my SDK so (after reverting global.json) I still got the same errors.

I see that on this page [](https://github.com/dotnet/core/blob/master/release-notes/download-archive.md) that there is a 1.1 version that sort of matches "1.0.0-preview2-1-003177." So is "**1.1** with SDK Preview 2.1 build 3177" what I should have installed, even though it is 1.1 not 1.0.0? I thought 1.1 was only for VS2017 installs.

I can't run from the command line either as dotnet.exe is picking up the references to 1.1.0 in the "project.json" file and is insisting I install "framework version" 1.1.0 instead of 1.0.1.

Arrrgh!

**Comment by SteveSandersonMS** [comment]
Sorry, you're right. Having different version numbers and release schedules for tooling versus libraries, even though they depend on each other, is such a headache. I will be very glad when this phase is over, which it should be soon since the RTM tooling is almost here.

Anyway, what you need - if you're doing a `project.json`-based project - is:

 * .NET Core 1.1 SDK (yes, that is 1.0.0-preview2-1-003177). To find this download, you have to be on the "Current" tab on [this page](https://www.microsoft.com/net/download/core#/current/sdk). This includes its own correct version of the .NET Core runtime, so you don't need to install that separately.
 * (Optional) If you want to use VS2015 with it, also install Visual Studio 2015 Tools (Preview 2), downloadable from the same page. There's only one version of the VS2015 tools - it's the same download, no matter whether you're using the "LTS" or "Current" SDK.

Theoretically you should not have to uninstall any other versions of .NET Core SDK/runtime, since they should all co-exist happily. But that's only theoretically, so if your machine has by now got into a bad state, you might want to start by wiping them all out.

If, on the other hand, you wanted to use VS2017RC, then you don't need to install any of this stuff, because VS2017RC includes its own correct versions of it all. But be sure to be on the latest version of VS2017RC (currently, that's build 26127).

Hope that helps.

**Comment by pierslawson** [comment]
Lovely! Installing the correct SDK was the only bit I was missing.

Just a comment... a matrix of which features are supported by each framework/skeleton would be really handy. I prefer Aurelia technically, but the perceived higher levels of support and help from projects like yours for Angular 2 might make it seem a more safe/pragmatic choice.
