### ISSUE TITLE
[Question] - nodeservices - holding onto state between invokes.

### ISSUE THREAD

**Issue by dazinator** [aspnet/JavaScriptServices#640]
Hoping someone can point me in the right direction.

I have a `js` file with a module export that I am invoking using NodeServices. The file looks like this: 

```js
var allFiles = {};

module.exports = {
   
    build: function (callback, requestDto) {

        var typescriptFiles = requestDto.files;
        for (var property in typescriptFiles) {
            if (typescriptFiles.hasOwnProperty(property)) {
                allFiles[property] = typescriptFiles[property];
            }
        }

       var result = {};
       result['Echo'] = allFiles;
       callback(null, result);

    }
};

```

I invoke like this:

```csharp

 var nodeScript = _script.Value; // lazy loaded singleton
                    var result = await _nodeServices.InvokeExportAsync<TypeScriptCompileResult>(nodeScript.FileName, "build", requestDto);

// result.Echo now contains JObject.

```

I am trying to persist state in the allFiles object.
However, what I am seeing is that between Invokes, my state is being lost on the node side - i.e `allFIles` doesn't keep the files I sent it previously with the previous invoke.

What am I missing here?

**Comment by SteveSandersonMS** [comment]
How are you getting your `_nodeServices` instance? If you construct a `new` instance every time, then you'll be starting up a new Node instance that has separate state. But if you're getting `_nodeServices` out of ASP.NET's DI system, then it should be the same instance each time and your Node module would maintain its state.

I'll close this because there doesn't appear to be any bug, but if you think there is, please let us know. If you were able to give complete repro steps that would be very helpful. Thanks!

**Comment by dazinator** [comment]
Hmm yeah, I am using DI system to get same instance. I'll try and put together a repro perhaps that will bring something to light. Cheers.

**Comment by dazinator** [comment]
I forgot to mention, one reason this can occur is due to `options.WatchFileExtensions` - it defaults to a set of known extensions, and if you edit any of these files, the node process will restart, losing any global state.
