### ISSUE TITLE
Refused to set unsafe header "connection"

### ISSUE THREAD

**Issue by chris-herring** [aspnet/JavaScriptServices#655]
I've noticed this error in Safari (9.1.2) and found in domain-task the following:

        if (!init.headers['Connection']) {
            init.headers['Connection'] = 'keep-alive';
        }

I see Connection listed here as a forbidden header name in the [fetch spec](https://fetch.spec.whatwg.org/#forbidden-header-name).

Can this be wrapped in a !isBrowser condition?

**Comment by SteveSandersonMS** [comment]
Thanks for reporting this. The `Connection` header was only needed to work around a bug in Kestrel on ASP.NET Core 1.0. Since we now depend on ASP.NET Core 1.1 where Kestrel no longer has that bug, the workaround is no longer needed.

So, I've published `domain-task` 2.0.3 which no longer contains this problematic logic.
