### ISSUE TITLE
Make server side rendering optional

### ISSUE THREAD

**Issue by NickAb** [aspnet/JavaScriptServices#656]
In some cases server side rendering might not be needed. For example if we have in-house web application, that is only accessible from intranet (there is no need for SEO, all users have JS enabled and high speed connection).
My understanding is that I can turn off server side rendering by commenting out following line
```
<app asp-prerender-module="ClientApp/dist/main-server">Loading...</app>
```

Is it enough to just turn it off? Would removal of server-side rendering related code and dependencies speedup webpack build?

**Comment by EduardTheThird** [comment]
All features do work without it and nothing will break when you disable it.
We removed it some time ago for a project we are working on and experienced no issues doing so.

To remove it change your app tag as follows, dont remove it completely:
`<app>Loading...</app>`

**Comment by SteveSandersonMS** [comment]
@EduardTheThird is correct that to disable server-side prerendering, you just need to remove the `asp-prerender-module` attribute.

> Would removal of server-side rendering related code and dependencies speedup webpack build?

Yes, slightly. You can disable building the server-side bundle by editing your `webpack.config.js` and `webpack.config.vendor.js` files. In both files, near the end of the file, change this line:

    return [clientBundleConfig, serverBundleConfig];

... to this:

    return [clientBundleConfig];

... so that Webpack only builds the client-side bundles.

**Comment by NickAb** [comment]
Thank you

**Comment by EduardTheThird** [comment]
Handy tip, thank you.
