### ISSUE TITLE
Add ability to override JsonSerializerSettings in NodeServices using NodeServicesOptions

### ISSUE THREAD

**Issue by sjolund** [aspnet/JavaScriptServices#674]
The JsonSerializerSettings in HttpNodeInstance and SocketNodeInstance should be user configurable through NodeServicesOptions. E.g., if one don't want NodeServices to convert casing on objects to CamelCase.

**Comment by SteveSandersonMS** [comment]
Doing this would be at a performance cost, because we'd have to double-encode the data that gets passed through. That is, it would have to be encoded once using your custom settings, then the resulting string would be re-encoded using the standard settings (it's necessary for the outer layer of encoding to uses known standard settings, otherwise there's no way for the JS code on the receiving end to interpret the message from the .NET side).

If this becomes a common request, we'll certainly consider it. In the meantime, I'd suggest you can manually double-encode the data (i.e., encode your object as a `string` using whatever settings your want, and pass that string to `NodeServices`, then use `JSON.parse` in your JS code to interpret it).
