### ISSUE TITLE
Deploy to IIS

### ISSUE THREAD

**Issue by threenine** [aspnet/JavaScriptServices#676]
Hi,

I have created a small APP using the Angular2 Template. Works great and was very easy to use.  
I published the App to Azure, just as an initial prototype test and it worked great using an Azure App Service deployment.  However, I now need to deploy the app to an IIS Server, but I can seem to work out how to do it.

When I xCopy the after creating a publish using `dotnet publish` 
I place the files in the Application Virutal Directory, if I browse to the url i.e. http://localhost/someapp

I get an error page saying page can't be found

However, when I browse to an api call i.e. http://localhost/someapp/api/controller/action

I get a result.

What is the additional step I need to take to ensure the application is rendered?

when I compared the deployed files i.e. between App Service & Publish 
it appears the same files are included  however, I get the feeling there is an additional configuration step for IIS that I am not aware of ?

I have created the APSNETCORE App pool and set it as UnManaged.

Do I need to set default document to something? 

I have also gone through this guide
http://webmodelling.com/webbits/aspnet/aspnet-deploy-iis.aspx   and ensured all has been set up correctly in IIS

**Comment by SteveSandersonMS** [comment]
A couple of things you might want to try:

 * Temporarily disable server-side prerendering (remove the `asp-prerender-module` tag helper from your `Index.cshtml`) and check that things are fully set up to work as far as client-side rendering is concerned. If they aren't, you'll probably get more easily-debuggable errors, since it's running in your browser rather than remotely.
 * Try setting up the correct base URL - in your `_Layout.cshtml`, change `<base href="/" />` to `<base href="/someapp/" />` or similar
 * Similarly, try updating the `baseUrl` option in your `boot-server.ts`. Unfortunately there's no way for us to infer this automatically at runtime, so you will have to enter it yourself here.

I'll close this because AFAIK there's no bug here, but if you track this down and think there is a problem in the templates/libraries in this repo, please reopen with details! Thanks.
