### ISSUE TITLE
React es6-promise

### ISSUE THREAD

**Issue by waynebrantley** [aspnet/JavaScriptServices#679]
Shouldn't you be using 'es6-promise' for the react template?
You use isomorphic-fetch, which takes care of fetch, but not promises.

**Comment by SteveSandersonMS** [comment]
Issue #484 describes the general matter of IE11 support, so I'll close this as a duplicate.

But yes you're right - it would be great to have out-of-the-box support for IE11 on all the templates, and `es6-promise` would be one of the steps towards that.

**Comment by waynebrantley** [comment]
@SteveSandersonMS Another thing is the big difference between React and React-Redux template with regards to setup.  

-  One uses whatwg-fetch, the other uses isomorphic-fetch.  
-  The way they share config on webpack, 
-  versions of npms each require all different

The only real 'config/webpack' difference between these two should be a couple of extra packages around Redux.

Also, do you accept pull requests for any of these kinds of things?

**Comment by SteveSandersonMS** [comment]
@waynebrantley Yes, we do accept pull requests. It's probably best to check with us about what you're planning to propose, because in a lot of cases there are reasons. For example, ReactReduxSpa uses `isomorphic-fetch` because it's needed to run in Node, whereas ReactSpa doesn't because `whatwg-fetch` is sufficient given that it doesn't do server-side prerendering. There may be some other cases where the differences are for no good reason, but we can certainly discuss!

> The only real 'config/webpack' difference between these two should be a couple of extra packages around Redux.

The presence/absence of server-side prerendering makes quite a big difference to how many things are best structured, so I'd argue you should expect to see more differences than just a few extra packages.
