### ISSUE TITLE
Aurelia SPA cannot be published to Azure in VS2017

### ISSUE THREAD

**Issue by MarkJamesHoward** [aspnet/JavaScriptServices#694]
I've created a project from the Aurelia template and am looking to upload to azure. The only option in VS2017 available though is via a Container app running on Linux. I would think it should allow a standard WebApp publish?

I've uploaded to GitHhub (https://github.com/MarkJamesHoward/aspaurelia3) and tried publishing from there too but get the below error in this case when navigating to the app:

An error occurred while starting the application.

.NET Framework X64 v4.0.30319.42000    |   Microsoft.AspNetCore.Hosting version 1.1.0-rtm-22752    |    Microsoft Windows 6.2.9200

**Comment by SteveSandersonMS** [comment]
VS2017 does this based on whether there's a `Dockerfile` in your project. These templates create one by default, and that makes VS think it can *only* be deployed to Docker (which is incorrect).

To fix this, delete the `Dockerfile` from your project, then restart VS.

In light of this issue, I think it's also time we removed the Docker files from the templates, because most people don't want them by default, and it causes this issue, and it's inconsistent with other ASP.NET Core templates to have them there. So they will be gone in the next update.
