### ISSUE TITLE
SSR async data loading strategy

### ISSUE THREAD

**Issue by JakeGinnivan** [aspnet/JavaScriptServices#70]
Hey Steve

Just checking out the react/redux template and am quite interested in the way you are loading data. Domain-task looks like a nice way to solve the problem and I actually hadn't seen domains before in node land, the problem is that they are being depreciated. See https://github.com/nodejs/node/issues/66

It looks like they won't be removed for quite a while though. 

I have been using https://github.com/Rezonans/redux-async-connect, specifically 1.0.0-rc2 as most of the other builds have issues. This has now been forked to https://github.com/makeomatic/redux-connect which I am yet to try out but looks promising as it fixes a bunch of my issues I had in redux-async-connect.

Just wanted to open a conversation to discuss options. Domain's seem like the wrong road seeing the goal is to remove them.

**Comment by SteveSandersonMS** [comment]
Hey Jake, good to see you here!

As you've probably inferred (but mentioning it for anyone else reading this thread), the benefit of `domain-task` here is that developers can write Redux components and stores that fetch data in the most natural way - just using `fetch` calls and not having to separate out the data access into a special location. This is possible only because Node domains provide an equivalent to .NET's "thread static" context where we can track the outstanding operations for a given request. As of today, there's no other API in Node that can provide a thread-static store like this.

However, you are right that domains are on track to be deprecated eventually. I was aware of that and considered it carefully. Fortunately the Node developers have made clear that they are not going soon, and when they do, it will only be with a reasonable alternative for people to move to. The likely replacement will be AsyncWrap, as described in the thread you linked to. From the docs at https://github.com/nodejs/tracing-wg/tree/master/docs/AsyncWrap, this looks entirely sufficient to achieve the same functionality.

My plan, therefore, is for `domain-task` to act as an abstraction over these approaches to threadstatic storage. When AsyncWrap (or some other theoretical replacement for domains) is viable, `domain-task` can use it, and existing apps will not need to know anything's changed. Arguably, the name `domain-task` is misleading (`threadlocal-task` or something would have been better), but it's a low-level implementation detail so I'm not too worried about the name.

I'm aware of alternative approaches like redux-async-connect and many similar patterns around splitting out data access into separate key-value stores etc. If possible I'd prefer to spare developers the trouble of dealing with yet another abstraction, because threadstatic storage can eliminate that requirement altogether.

What do you think? If thread-local tasks are possible technically (and I think they are), do you agree it's a preferable API? Or do you think that an redux-async-connect-like approach is preferable regardless, and if so why?

**Comment by SteveSandersonMS** [comment]
I'll close this since the discussion seems to have concluded, but please reopen if applicable.
