### ISSUE TITLE
Is it possible to pass arbitrary .NET types including delegates?

### ISSUE THREAD

**Issue by moodmosaic** [aspnet/JavaScriptServices#701]
With [Edge.js](https://github.com/tjanczuk/edge#how-to-marshal-data-between-c-and-nodejs) it's possible to pass arbitrary .NET types, including delegates, and then have the JavaScript code invoke the delegates. Then, from the .NET delegates, you return back to JavaScript, and so on.

Would it be possible to do something similar with this tool?

**Comment by SteveSandersonMS** [comment]
That's not something currently supported natively in `NodeServices`. At some point, we might be able to enable Edge.js as an alternative transport layer that you can use with `NodeServices` (similar to how you can currently choose between HTTP and Socket transports), but that wasn't possible last time I checked because Edge.js didn't support hosting Node within a .NET Core process.

So right now, all types you pass have to be serializable  by Json.NET.

**Comment by moodmosaic** [comment]
Is there some fundamental difference between desktop and CoreCLR that prevents hosting Node within a .NET Core process?

**Comment by SteveSandersonMS** [comment]
Nothing fundamental that I know of. AFAIK, it's just not implemented in Edge.js.
