### ISSUE TITLE
Karma debug shows counter component

### ISSUE THREAD

**Issue by SGRob** [aspnet/JavaScriptServices#710]
Create a new project using the yeoman 

Run "npm test"

Click Debug

Counter component is shown. Expected the karma debugger to show.

Additionally source mapping isn't working as there should be a source for the counter.component.spec.ts file

**Comment by SteveSandersonMS** [comment]
> Counter component is shown. Expected the karma debugger to show

I'm not sure what you mean by "the karma debugger". As far as I understand, the "debug" button is just meant to open the file under test so that you can open your browser's native debug tools (e.g., so you can then set breakpoints in your code that will hit when you refresh to re-run the test). So I think this is working as expected.

I agree about the source mapping, though. The reason this doesn't work by default is that Karma only seems to work with inline source maps. If you want this to work, edit your `webpack.config.js`, changing the `SourceMapDevToolPlugin` options so it looks like this:

```javascript
new webpack.SourceMapDevToolPlugin({
    test: /\.(ts|js)($|\?)/i
})
```

... then the source maps should work OK when you restart Karma.

The reason we don't have it like this by default is that VS's integrated IE debugging only works if you have *external* (not inline) source maps. If this gets fixed in VS, we'd switch over to inline source maps by default.

**Comment by SGRob** [comment]
Thanks for the reply Steve.

In case anybody makes the same mistake i made - I've looked at this again today and realised that the "debug" functionality I was referring to is actually provided by 'karma-jasmine-html-reporter' which isn't included in the SPA template but is included in the Angular quickstart documentation. I was getting confused.

**Comment by jrmcdona** [comment]
@SGRob what steps did you follow to get Karma working?   I seemed to be having issue getting my Tests outside of the client App to load the angular modules.

Are you putting your Tests outside of ClientApp?

Thanks

**Comment by SGRob** [comment]
@jrmcdona Karma tests worked out of the box for me. A simple "npm test" was sufficient to get them to run.
