### ISSUE TITLE
Hot module replacement doesn't work with tsconfig target es5

### ISSUE THREAD

**Issue by t0x1c123** [aspnet/JavaScriptServices#731]
Hello I have a problem. I switched target in tsconfig from es6 to es5. The reason why is that i want to use react-helmet and with target es6 i get error like this: 

 Call to Node module failed with error: Invariant Violation: Element type is invalid: expected a string (for built-in components) or a class/function 

with import like this:  import * as Helmet from 'react-helmet';

So I manage it to work by switching target from es6 to es5 but hot reload is now broken. In console output looks everything fine no errors but nothing changes.

My tsconfig.js
```javascript{
  "compilerOptions": {
    "baseUrl": ".",
    "moduleResolution": "node",
    "target": "es5",
    "jsx": "preserve",
    "experimentalDecorators": true,
    "sourceMap": true,
    "skipDefaultLibCheck": true,
    "lib": ["es6", "dom"],
    "types": [ "webpack-env" ],
    "paths": {
      // Fix "Duplicate identifier" errors caused by multiple dependencies fetching their own copies of type definitions.
      // We tell TypeScript which type definitions module to treat as the canonical one (instead of combining all of them).
      "history": ["./node_modules/@types/history/index"],
      "redux": ["./node_modules/@types/redux/index"],      
      "react": ["./node_modules/@types/react/index"]
    }
  },
  "exclude": [
      "bin",
      "node_modules"
  ]
}
```

**Comment by SteveSandersonMS** [comment]
I wouldn't recommend changing TypeScript to emit ES5 like that (as in, supplying ES5 to babel, which itself is meant to do the ES6->ES5 conversion). Doing that will break HMR, because `react-transform-hmr` relies on information that would be lost during the ES5 conversion. Plus you'd be locking yourself into older technologies.

From a quick web search, it looks like lots of other people have reported the `Element type is invalid` issue with `react-helmet` (on various other project types and technology stacks), and they have discussed various solutions. I'd try to find a solution that doesn't involve downgrading yourself to ES5 limits.

I'll close this since it isn't an issue in the code here (we don't control TypeScript, `react-transform-hmr`, or `react-helmet`) - it's not something that could be fixed by changing any code in this repo. Hope that's OK!
