### ISSUE TITLE
Cant add jquery ui

### ISSUE THREAD

**Issue by TibDev** [aspnet/JavaScriptServices#733]
Hi,
I am trying to add jquery autocomplete to angular 2 template.
I put 'jquery-ui/ui/widgets/autocomplete.js' to the vendor array, run webpack --config webpack.config.vendor.js, and i get this exception :  
"Call to Node module failed with error: Prerendering failed because of error: TypeError: Cannot read property 'prototype' of undefined"

**Comment by SteveSandersonMS** [comment]
jQuery doesn't support running on the server, so you can't do prerendering with it.

You can either disable server-side prerendering entirely (remove the `asp-prerender-module` attribute from `Index.cshtml`), or you can amend your code so that jQuery UI and its dependencies are not referenced when it runs on the server.

**Comment by JihedHalimi** [comment]
If jQuery doesn't support running on the server, then the whole server-side pre-rendering is useless.
