### ISSUE TITLE
QUESTION: How to use with angular/cli?

### ISSUE THREAD

**Issue by MarkDHarris** [aspnet/JavaScriptServices#746]
(Very sorry to open an issue for a simple question but I was not able to find a way to otherwise get my question in front of a group who could answer this question.)  

How does one incorporate angular/cli with a project generated using "dotnet new angular"?  Or, if that does not make sense, how does one use "dotnet <whatever>" to generate new angular components and services within the ClientApp\app project structure?

Thanks!

**Comment by SteveSandersonMS** [comment]
Some features of Angular CLI would be relevant here; others would not.

Angular CLI's ability to generate new components/services/etc is relevant. Currently I'm not sure how you configure Angular CLI to put them in the right locations for these project types, but in theory it should be possible.

However, Angular CLI's ability to serve your web app (i.e., its main feature) would not be relevant or useful, because with these projects you already have ASP.NET doing that, and it supplies all the functionality such as HMR and being ready for production use.

**Comment by MarkDHarris** [comment]
Yes - this is a fantastic way to use VS2017 and combine ASP.NET Core with Angular.  What I was hoping to find and the reason for my question was a method to add a new component or service similar to angular/cli's "ng g c" where it not only consistently created components/services but also wired them into the module declaration and assembled everything correctly to help achieve consistency in large applications as well as make it easier to create.  (even a simple add -> new -> "angular component" or something similar would help achieve that.)  Thanks for the info and the incredible work!
