### ISSUE TITLE
renderToString defined multiple times

### ISSUE THREAD

**Issue by stsrki** [aspnet/JavaScriptServices#752]
In the ReactReduxSpa [template](https://github.com/aspnet/JavaScriptServices/blob/dev/templates/ReactReduxSpa/ClientApp/boot-server.tsx) renderToString function is defined in two places. Is this intentional? Wouldn't be better for the first renderToString to save the result in the variable and then pass it later as html parameter?

for example:

    // Perform an initial render that will cause any async tasks (e.g., data access) to begin
	const html = renderToString(app);

	// Once the tasks are done, we can perform the final render
	// We also send the redux store state, so the client can continue execution where the server left off
	params.domainTasks.then(() => {
		resolve({
			html: html,
			globals: { initialReduxState: store.getState() }
		});
	}, reject); // Also propagate any errors back into the host application

**Comment by SteveSandersonMS** [comment]
`renderToString` is called in two places deliberately, as per the comments around those calls. The first call triggers any initial data loading operations. Then we wait for the data to be loaded. Then we call `renderToString` again to render the final app in its fully-loaded state.

The alternative would be to use a completely different technique to make sure you've loaded all your data before the first `renderToString`, but that's way harder to work with, because then stores/components can't just contain their own encapsulated data access logic. Obviously if you personally prefer some other approach, you can change your own app to do that.

Hope that makes sense!
