### ISSUE TITLE
server-side prerendering and redirectUrl from window.location.origin

### ISSUE THREAD

**Issue by hubert-associates** [aspnet/JavaScriptServices#759]
Hi, I need a complete callback URL for OAuth server-side. I'm setting up authentication  in routes.tsx and the following window.location.origin gives me the error below. I have seen here (https://github.com/aspnet/JavaScriptServices/tree/dev/src/Microsoft.AspNetCore.SpaServices#server-side-prerendering)  that one can pass in params from the MVC View ... but seems a bit convoluted. What is the solution to this?

        // Configure OAuth
        this.logingui = new OAuthLogin(clientId, domain, {
            auth: {
                redirectUrl: `**${window.location.origin}**/login`,
                responseType: 'token'
            }
        }) 

Error:
fail: Microsoft.AspNetCore.Diagnostics.ExceptionHandlerMiddleware[0]
      An unhandled exception has occurred: Call to Node module failed with error: Prerendering failed because of error: ReferenceError: window is not defined
    at new AuthService (C:\_d\cl\ClientApp\dist\main-server.js:24373:30)

**Comment by SteveSandersonMS** [comment]
You'll need to put some logic in both `boot-server.ts` and `boot-client.ts` to make the origin information available elsewhere in your app.

You probably don't need to use `asp-prerender-data`, because you already have the information you need in both cases:

 * In `boot-server.ts`, you already receive the origin (it's `params.origin` or `params.url` if you prefer)
 * In `boot-client.ts`, you can use `window.location.origin` (or `window.location.href` if you prefer)

As for how to get that data from `boot-server.ts`/`boot-client.ts` to the rest of your application, well that's up to you. You didn't mention what SPA framework you're using, but if it's Angular, you could use a technique like `Zone.current` [as described here](https://github.com/aspnet/JavaScriptServices/issues/755#issuecomment-286179944). Other SPA frameworks have different options, so consult their docs. Or you could use the `domain-context` package from NPM.

Hope that helps!

**Comment by hubert-associates** [comment]
Thanks. Using React-Redux. OK, I'll look at the boot-* option. I got around it at the moment by turing of the prerendering. Congratulations on the great services BTW. Anything in store for RGR :-)?
