### ISSUE TITLE
Add 'scss' processor.

### ISSUE THREAD

**Issue by skorunka** [aspnet/JavaScriptServices#766]
How to add a 'scss' processor to both webconfig files?
I'm looking for this http://www.telerik.com/kendo-angular-ui/components/styling/#toc-prerequisites
Thank you.

**Comment by SteveSandersonMS** [comment]
Here's a walkthrough on how to add LESS support: https://github.com/aspnet/JavaScriptServices/blob/dev/src/Microsoft.AspNetCore.SpaServices/README.md#example-a-simple-webpack-setup-that-builds-less

It should be possible to amend the steps there to get SASS/SCSS instead (e.g., use `sass-loader` instead of `less-loader`), etc. Since this is just a generic Webpack setup, rather than being specific to ASP.NET Core, any Webpack+SASS tutorial should contain the relevant steps. Hope that's OK!

**Comment by skorunka** [comment]
Thank you, sorted.
