### ISSUE TITLE
How / Where to find latest version of templates?

### ISSUE THREAD

**Issue by rgamage** [aspnet/JavaScriptServices#776]
This may be a stupid question, but here goes.  The landscape is moving quickly, and I understand all files cannot always be up to date, but I always have trouble knowing where to get the latest template.  Specifically for the Angular25Spa template.  There seem to be at least 3 possible places:
1) ASP .NET Core Template Pack Extension - this doesn't appear to work with VS 2017, so this looks like a dead end at the moment for obtaining the latest template that works with the VS2017 project file.
2) Yeoman generator - at command line, type yo aspnetcore-spa.  I did this today and I got a template that still has project.json file and no csproj file.
3) Clone the GitHub repo.  This seems to be the place to get the very latest, as the templates\Angular25Spa folder has a .csproj file, and no project.json / xproj files.

So I guess I'm trying to understand how/where yeoman pulls its source from, if not from the latest version in the repo?   The readme in the repo suggests to use the generator to get the templates.

And when might the VS2017 extension for templates be ready for the AngularSpa app?

Thanks Steve for all your work on this.  We are using this template on a big project and are very happy with it so far.  Just a little frustrating to keep up with all the moving pieces.

**Comment by hungdluit** [comment]
As my understanding, VS2017 does not need project.json any more.

**Comment by rgamage** [comment]
Yes I realize that, thank you. That was my point.  The template that still has project.json is clearly out of date.

**Comment by flightlevel** [comment]
@rgamage What version are you using, the older version eg. 0.8.2 would you give you a choice of project.json or .csproj
eg.
![Image](https://snag.gy/5vi3fH.jpg)

Whereas the latest version 0.9.0 https://www.npmjs.com/package/generator-aspnetcore-spa just goes straight to .csproj

**Comment by SteveSandersonMS** [comment]
Understood it's not always clear where the latest stuff is.

You're right that the ASP.NET Core Template Pack Extension is well behind. I'm going to try to get the Angular template removed from that extension, because it's not really needed now we have clean `dotnet new` support, and it's never going to be as up-to-date.

The other two options - Yeoman and `dotnet new` - are both continually up-to-date in their underlying package managers. In both cases it's up to you when you upgrade your Yeoman/`dotnet new` packages locally. And as @flightlevel points out, `dotnet new` has supported `csproj` for a while, and in fact that's the only option as of 0.9.0 since `project.json` is deprecated.
