### ISSUE TITLE
TsLint for react templates?

### ISSUE THREAD

**Issue by DanHarman** [aspnet/JavaScriptServices#778]
Any desire to have a tslint config setup for the react templates? We could probably tailor it to not complain about the code as currently formatted, although might have to standardise a few things.

**Comment by SteveSandersonMS** [comment]
How much does it currently complain about the code as it is out-of-the-box? Are there any simple changes we could make to the code so that it's happy even without a tslint config file?

As for putting a tslint config files in the default projects, it would be great if we could avoid that. We're trying to minimise the concept count, since it's already a lot for newcomers to handle, and as much as possible each bit of functionality should be logically separate and composable (e.g., if you want TS linting, you choose to add it; if you want Docker support, you choose to add it, etc.). If there's need to document aspects of this, we're trying to build up the wiki on this repo.

**Comment by SteveSandersonMS** [comment]
Actually I'll mark this as closed since if possible we wouldn't put a tslint config in the templates. But I'm still very open to making code style changes if it would make tslint happier by default (without making the code any less elegant). Hope that's OK!

**Comment by DanHarman** [comment]
Understood - the concept count is already pretty hefty. For reference it wasn't too bad I just have this:

```
{
    "extends": "tslint:recommended",
    "rules": {
        "interface-name": [false],
        "max-classes-per-file": [false],
        "arrow-parens": [true, "ban-single-arg-parens"],
        "max-line-length": [140],
        "quotemark": [true, "single", "jsx-double", "avoid-escape"]
    }
}
```
