### ISSUE TITLE
Memory History on React Redux Template

### ISSUE THREAD

**Issue by DanHarman** [aspnet/JavaScriptServices#787]
Hi,

I'm adding `routerMiddleware` from `react-router-redux` so that I can navigate within the app (wondering if this shouldn't just be in the template?).

However in doing so I'm somewhat confused by `boot-server.tsx` as whilst it does`import createMemoryHistory from 'history/lib/createMemoryHistory';` it never creates or uses a memory history. Is this intentional?

The reason this came up is that to apply `routerMiddleware`, so I can send redux actions to navigate, I need to pass it in the history module in use, and what this for `boot-server.tsx` isn't apparent. Right now I've put my change into `configureStore.ts` but I think it's probably incorrect because it's currently binding to `browserHistory` for both entrypoints.

```
\\ configureStore.ts
...
    const createStoreWithMiddleware = compose(
        applyMiddleware(thunk),
        applyMiddleware(routerMiddleware(browserHistory)),
        devToolsExtension ? devToolsExtension() : f => f,
    )(createStore);
...
```

**Comment by SteveSandersonMS** [comment]
You're quite right - importing `createMemoryHistory` into that file, when it's not even used, is not intentional. I'll remove that.

To integrate routing with server-side rendering, `boot-server.tsx` doesn't need to create a history instance. It just asks `react-router` to match against the server-provided `location`, and then use the resulting `renderProps` to initialise the `<RouterContext>` with those props.

If you want to change how routing works and introduce some extra thing (`routerMiddleware`), I'm not sure exactly how they'd expect you to set that up for server-side rendering. The `react-router-redux` people probably have docs for that, and whatever they say you should do should work the same here, because there's nothing ASP.NET-specific about the code you put in your `createServerRenderer` function.

**Comment by DanHarman** [comment]
@SteveSandersonMS the `routerMiddleware` is part of `react-router-redux` and is used to intercept push actions that it exports, so that they can trigger navigation. Being able to redirect is a fairly common requirement and I would have thought it should also work when rendering on the server, e.g. someone loads a page that immediately redirects, shouldn't that happen on the server too?

If that is the case, then the memoryHistory would be required to feed into the middleware, to support push(location), replace(location), go(number), goBack(), goForward().

The other option would be to detect if running in node in configureStore and not put the middleware in, but that won't support routing on the server which could be a problem.

Happy to do a pull request to get the middleware working if this is useful and there is a solution you are happy with.

**Comment by SteveSandersonMS** [comment]
We already do support redirects during SSR - that's what the `if (redirectLocation) { ... }` code block in `boot-server.tsx` is about. This gets triggered if your routing config specifies a redirection for the matched URL. No extra special middleware is needed for this.

I'm not sure what extra functionality you need (I'm guessing it's something specific to a particular pattern with Redux) but if you can distill it down to an exact, minimal case, ideally with a proposed implementation, we can definitely consider it!
