### ISSUE TITLE
Node.js Security

### ISSUE THREAD

**Issue by antmdvs** [aspnet/JavaScriptServices#791]
What are the recommendations for locking down the Node process for a production deployment? As we are a .NET shop, our enterprise architects are pushing back on SSR due to lack of Node security knowledge. Please consider adding this to the Wiki. Thanks!

**Comment by SteveSandersonMS** [comment]
When you're using SSR, you're not exposing Node to receive requests directly - the Node process is only listening for requests from `localhost`, because it's only serving as an RPC service for your .NET application. So most aspects of web server hardening are not applicable - the attack surface just isn't there.

As for any further recommendations, I'd recommend raising this with the Node community at large, as they would be much better positioned to discuss this than anyone on this repo. Hope that's OK!

**Comment by antmdvs** [comment]
Thanks @SteveSanderson! One more question specific to this repo: Is the transport between .NET and Node encrypted? This is a requirement for us.

**Comment by SteveSandersonMS** [comment]
No, it's going over a TCP socket on `localhost`, not between machines. I can't think of any reason you'd want that to be encrypted.
