### ISSUE TITLE
Angular 2 RouterPreloader with  aspnet core template

### ISSUE THREAD

**Issue by seven1986** [aspnet/JavaScriptServices#792]
### Could you give me an example?  I have tried many times , some code like below, but still can not find the right way .

``` typescript
export const routes: Routes = [
  { path: '', redirectTo: 'contact', pathMatch: 'full'},
  { path: 'crisis', loadChildren: 'app/crisis/crisis.module#CrisisModule' },
  { path: 'heroes', loadChildren: 'app/hero/hero.module.3#HeroModule' }
];
```

**Comment by SteveSandersonMS** [comment]
Here's an example of how I once set up Angular lazy loading: https://github.com/aspnet/JavaScriptServices/commit/7ded0a0b60ce3a5356417a5d6102a376fe5f6802

However, since then, I've heard that there's an issue between `angular2-router-loader` and Webpack 2: https://github.com/aspnet/JavaScriptServices/issues/660#issuecomment-278737939. I don't know whether they have resolved that or not since then, but if you need to, please discuss this with the `angular2-router-loader` maintainers, as it's not specific to any of the code in this repo (if things work between `angular2-router-loader` and Webpack 2 in general, then they will work with these templates, as we're not doing anything special to change how things work).
