### ISSUE TITLE
VueSpa template missing node_modules

### ISSUE THREAD

**Issue by Gsonovb** [aspnet/JavaScriptServices#793]
VueSpa template use  `dotnet publish`  no response (missing node_modules)

and , how to use VSCODE or VS2017 to start quickly? (e.g. Lauch.json and tasks.json)

**Comment by SteveSandersonMS** [comment]
`dotnet publish` is not meant to deploy `node_modules`, because the Webpack build process produces completely self-contained `.js` bundles that never try load load anything from `node_modules` at runtime.

I'm not sure what's not working in your case. If you're implemented something custom that does need `node_modules` at runtime, then you'll need to change your `csproj` to cause that directory to be included in the publish output.

If you are able to track down the issue to something you think is a bug in the code in this repo, could you please file an issue with repro steps? Thanks!
