### ISSUE TITLE
Support V8 Inspector Integration for Node.js

### ISSUE THREAD

**Issue by novascreen** [aspnet/JavaScriptServices#796]
It would be great if we could debug the Node instance with Chrome dev tools:

https://nodejs.org/api/debugger.html#debugger_v8_inspector_integration_for_node_js

Or maybe make it possible to pass any arguments to the Node process?

**Comment by SteveSandersonMS** [comment]
Agreed. Currently we support `node-inspector` (https://github.com/aspnet/JavaScriptServices/blob/dev/src/Microsoft.AspNetCore.SpaServices/README.md#debugging-your-projects), but it would be better if we changed this to pass `--inspect` instead of `--debug` to support newer versions of Node.

Do you have any interest in submitting a pull request that changes how `OutOfProcessNodeInstance.cs` deals with the `launchWithDebugging` flag? It should be changed to pass `--inspect` to the Node process instead of `--debug`.

> Or maybe make it possible to pass any arguments to the Node process?

Agreed that would also be good, but since we already have a defined API for starting in debugging mode, we should consider "arbitrary arguments" to be a separate feature.

**Comment by novascreen** [comment]
Sounds good. I can look into submitting a pull request. Do you think it makes sense to add another option for break on first line?

**Comment by SteveSandersonMS** [comment]
> Do you think it makes sense to add another option for break on first line?

Since (as a separate work item) we'll add the ability to pass arbitrary params, we're probably OK without additional startup options. Then at least if Node changes its debugging option names again, we won't have another issue to fix :)

**Comment by SteveSandersonMS** [comment]
> Sounds good. I can look into submitting a pull request

Excellent - thanks! I'll close this issue then, and will await your PR.

**Comment by novascreen** [comment]
> Since (as a separate work item) we'll add the ability to pass arbitrary params, we're probably OK without additional startup options
I was thinking the same thing. I've already created that PR: #804 
Btw. I have another PR waiting: #714
