### ISSUE TITLE
Why is Angular Http.get running at server and client's browser?

### ISSUE THREAD

**Issue by felipedrumond** [aspnet/JavaScriptServices#80]
Why `http.get('/api/albums/mostPopular')` runs at serve and delivers the pre-renderized html, but my code bellow runs at the **client's browser**?

`http.get('http://localhost://api/v1/listaprodutosservice/?term=bolsa&pagina=1&filtros=(724,691)&filtrovalor=0_0&quantidade=39&ordem=relevancia').subscribe(result => {
            this.lista = result.json();
         });`

Is there any way to run external gets running at server?

**Comment by SteveSandersonMS** [comment]
There are probably two things to consider:

1. Is your server-side code waiting for the `http` request to complete before it returns the response? In other words, if you disable JavaScript completely in the browser, do you see the prerendered HTML with your data in it, or does it look as if the data hasn't loaded yet? If it looks as if the data hasn't loaded yet, you might have not enabled the `angular2-universal` implementation of `http` in your server-side `componentProviders` config. See https://github.com/aspnet/JavaScriptServices/blob/master/templates/Angular2Spa/ClientApp/boot-server.ts for a correctly-configured example.
2. Is your client-side code repeating the same `http` request that the server already resolved? If so, you might want to use something like `Html.PrimeCache` ([example here](https://github.com/aspnet/JavaScriptServices/blob/master/samples/angular/MusicStore/Views/Home/Index.cshtml#L7)) so that the client-side code doesn't need to make a second request.

I'll close this, because it doesn't sound like you're reporting an issue in JavaScriptServices. Hope that's OK.

**Comment by felipedrumond** [comment]
Hi Steve, I noticed that PrimeCache is built to not do requests to external APIs, am I right?
What about creating a PrimeCache for external requests?
