### ISSUE TITLE
ReactReduxSpa boot-server.tsx sending "wrong" initialReduxState to client

### ISSUE THREAD

**Issue by HaraldMuehlhoffCC** [aspnet/JavaScriptServices#808]
While working on redux stores for my ReactReduxSpa based framework I noticed a problem where the `initialReduxState` computed in `boot-server.tsx` didn't include the result of async domainTasks.

The issue is that `boot-server.tsx` calls `renderToString(app)`, waits for the domainTasks to complete &ndash; at this stage `store.getState()` includes the results from my fetch operation &ndash; and then calls `renderToString(app)` again BEFORE `store.getState()`. The side-effect of the second call to `renderToString(app)` is that some data in my redux stores is reset because the actions are firing again and this time the system doesn't wait for the domainTasks to complete (my request action resets the request result and also `isLoaded` &hellip;).

My solution for now is pretty straight-forward. Before the second call to `renderToString` I save the redux store state:

`const initialReduxState = JSON.parse(JSON.stringify(store.getState()));
`

and use this const instead of `store.getState()` when setting

`globals: { initialReduxState: initialReduxState }
`

[https://github.com/aspnet/JavaScriptServices/blob/dev/templates/ReactReduxSpa/ClientApp/boot-server.tsx](https://github.com/aspnet/JavaScriptServices/blob/dev/templates/ReactReduxSpa/ClientApp/boot-server.tsx)

**Comment by SteveSandersonMS** [comment]
Thanks for the suggestion!

I'm looking at the out-of-the-box ReactReduxSpa, and can't see any case where it would make a difference. As we have it there, the second call to `renderToString` doesn't cause the `store` to change, so it seems like we don't need to do this? Am I right in understanding that your change is needed only if you modify your app logic so that further calls to `renderToString` trigger a change to your store?

If I'm right about this, I think it's something we should leave up to developers to choose how to handle in their own apps. If they are modifying the state of their store, we don't know for sure whether they want the "before" or "after" version of it to be serialized - developers should implement logic to choose for themselves.

So, on the assumption that this doesn't affect the out-of-the-box ReactReduxSpa, I'm going to mark this closed. But if I'm wrong and you know of some case where out-of-the-box ReactReduxSpa needs this to behave consistently, could you please let me know? Do you have repro steps? If I'm misjudging how Redux is going to behave (e.g., if there's a race condition I've just never personally observed), I'd really like to know about that so we can be sure to implement your fix or something similar!

**Comment by HaraldMuehlhoffCC** [comment]
Thanks for your thoughful answer! From looking at the out-of-the-box code at least `requestWeatherForecasts` is called by the second `renderToString` and the reducer changes the state to:

```
case 'REQUEST_WEATHER_FORECASTS':
            return {
                startDateIndex: action.startDateIndex,
                forecasts: state.forecasts,
                isLoading: true
            };
```

So even though the forecasts where loaded by waiting for the `domainTasks` to finish the returned state has `isLoading` set to true (In my case I reset the equivalent to forecasts so the difference is even more striking).

Since the result of the second `renderToString` was created using the state waited for my feeling is that this is the correct state to return in any case.

**Comment by SteveSandersonMS** [comment]
`requestWeatherForecasts` doesn't dispatch `REQUEST_WEATHER_FORECASTS` if the existing state already contains the required data, so the second call is a no-op. So, I don't think there is a problem here, at least not out-of-the-box.

I appreciate your broader point that for general side-effecting `renderToString` calls, you're more likely to reproduce the same result if starting with the same input store state rather than the post-`renderToString` store state. I'm curious about what other Redux developers do (e.g., what the most authoritative Redux app templates do).
