### ISSUE TITLE
Trying to use the angular template in an ASP.NET Core Web Application (.NET Framework)

### ISSUE THREAD

**Issue by pafrench** [aspnet/JavaScriptServices#823]
Hello. I've used the ASP.NET Core spa template for Angular 2 to generate an ASP.NET Core Web Application (.NET Core) and it works out of the box with no problems.

I've created a new ASP.NET Core Web Application targeting the .NET Framework and have attempted to transfer all of the Angular code over, but I'm getting the following exception when running:

Call to Node module failed with error: Error: No ResourceLoader implementation has been provided. Can't read the url "app.component.html"
at Object.get (C:\Source\Angular2\UI2\ClientApp\dist\vendor.js:59627:19) [angular-universal request]

Not sure what I'm missing? There's talk of swapping out the templateUrl with template and require, but why would the change from .NET Core to .NET Framework require that?

**Comment by SteveSandersonMS** [comment]
Sorry, I don't know. In theory it certainly *should* work, so if it doesn't, I suspect you haven't transferred all the code properly. Maybe it's easier to take a working .NET Core version of the template and change it to target .NET Framework (there are probably a lot fewer changes with that starting point, and you'd be able to find out what they are by diffing a File->New .NET Core app vs a File->New .NET Framework app).

Since this is a support request rather than a bug report or feature request, I'll mark this as closed (as there are no changes for us to make in this repo). But please feel free to continue posting here if you discover more!

**Comment by pafrench** [comment]
Thanks for the prompt reply Steve. Quick (potentially stupid) question - how *do* you change the platform of an existing .NET Core project to .NET Framework (I'm new to .NET Core)??

The project properties only allow switching between .NET Core 1.0 and 1.1.

**Comment by SteveSandersonMS** [comment]
I was suggesting diffing a File->New .NET Core app vs a File->New .NET Framework app so you can see exactly what changes would be needed. I don't know if there's any GUI-based way to do this.

**Comment by pafrench** [comment]
FYI I got this working by simply editing the csproj from:

`<PropertyGroup>
    <TargetFramework>netcoreapp1.1</TargetFramework>
    <TypeScriptCompileBlocked>true</TypeScriptCompileBlocked>
    <IsPackable>false</IsPackable>
  </PropertyGroup>`

to

`<PropertyGroup>
    <TargetFramework>net461</TargetFramework>
    <RuntimeIdentifier>win7-x86</RuntimeIdentifier>
    <TypeScriptCompileBlocked>true</TypeScriptCompileBlocked>
  </PropertyGroup>`

I also had to add a reference to System.Net.Http, as app.UseWebpackDevMiddleware was throwing a FileLoadException regarding the System.Diagnostics.DiagnosticSource assembly.
