### ISSUE TITLE
Any idea when this will move out of "beta"? 

### ISSUE THREAD

**Issue by tylerjgarland** [aspnet/JavaScriptServices#825]
Some larger companies are risk-adverse and see anything with beta in the name as a no-no. Any ideas when you'll promote this to RC for 1.0?

**Comment by MarkPieszak** [comment]
Which part is stating beta?

**Comment by tylerjgarland** [comment]
![image](https://cloud.githubusercontent.com/assets/1291826/24477682/cb828b1a-148c-11e7-8616-2ce0e23ee262.png)

**Comment by SteveSandersonMS** [comment]
The `NodeServices` and `SpaServices` NuGet packages are already released as final ("RTM"), non-beta versions. The current templates produce projects that *only* use those (they don't use `AngularServices` any more, because it doesn't contain any additional functionality besides what `SpaServices` provides). We haven't released an RTM version of `AngularServices` because there's no need to have an extra thing to document and support - it's no longer used in the current templates.

I'd recommend removing your reference to `AngularServices` and adding a reference to `Microsoft.AspNetCore.SpaServices` instead.

**Comment by tylerjgarland** [comment]
@SteveSandersonMS , Apologies for the confusion. Thanks for responding.
