### ISSUE TITLE
Combining this JavaScriptServices with pre-existing .Net Framework 4.6.1

### ISSUE THREAD

**Issue by GlennBrand** [aspnet/JavaScriptServices#826]
Hi Steve,

Great job on this. Best I have seen yet after reading all that I have seen.

Our application is running on .Net Framework 4.6.1 and was working fine with an Angular 2 framework and used systemjs.config to build it. However I was told by your colleague Prashanth Madi that I could not deploy our app to azure web service with systemjs.config that we had to use webpack 2. 
It looks like you have done this with .Net Core 1.1. Is this compatible with DLLs compiled from .Net Framework 4.6.1 or do I have to switch over everything.

Glenn

**Comment by SteveSandersonMS** [comment]
Glad to hear this looks useful to you.

I don't really follow the question, because System.js vs Webpack is a question about client-side technologies, whereas .NET Core vs .NET Framework is a question about server-side technologies. They are independent matters - you can use either client-side technology with either server-side technology. Further, Azure doesn't care whether you use System.js or Webpack - it doesn't know about either, because how you built your `.js` files makes no difference to them being hosted in the cloud.

If you [generate a SPA project using the SpaTemplates package](https://blogs.msdn.microsoft.com/webdev/2017/02/14/building-single-page-applications-on-asp-net-core-with-javascriptservices/), then by default you'll be using .NET Core on the server. However you can [change your generated app to run on .NET Framework if you want](https://github.com/aspnet/JavaScriptServices/issues/823#issuecomment-290302930).

**Comment by GlennBrand** [comment]
Thanks Steve,
I was told that System.js was not usable in the builds process for Azure applications. This solves a huge number of refactoring problems.
