### ISSUE TITLE
EventSource's response has a MIME type ("text/html") that is not "text/event-stream".

### ISSUE THREAD

**Issue by skorunka** [aspnet/JavaScriptServices#827]
Got this client side error while running application in Production mode:
"EventSource's response has a MIME type ("text/html") that is not "text/event-stream". Aborting the connection."

In "Development" mode, all works.

Any idea what's wrong?

I did no changes to webpack configs, except adding my dependencies.

**Comment by SteveSandersonMS** [comment]
Yes, you built your `.js` files in development mode, but are now trying to use them in production mode. That will lead to this error.

Solution: rebuild your JS files in production mode

```
webpack --config webpack.config.vendor.js --env.prod
webpack --env.prod
```

... or use .NET's "publish" feature and run the application it puts in your publish output directory (because that automatically does prod-mode Webpack builds).

**Comment by skorunka** [comment]
Oh, u r right. Thank you. At least, it is now "documented" somewhere.
