### ISSUE TITLE
React SPA Template site.css 404

### ISSUE THREAD

**Issue by VSDekar** [aspnet/JavaScriptServices#839]
Somewhere in the configuration there is a wrong setting.

When you create a clean new react project with Yeoman or with `dotnet new react` and then running the applicaton you will get a 404 for the site.css File.

In the reactredux template everything is ok.

**Comment by SteveSandersonMS** [comment]
If you check your `_Layout.cshtml` file, you'll see that the React template only references `site.css` when it's in staging or production modes:

        <environment names="Staging,Production">
            <link rel="stylesheet" href="~/dist/site.css" asp-append-version="true" />
        </environment>

To run your app locally in development (without first running Webpack to produce a production build), you *must* have the app in development mode, otherwise various things don't work. Not sure if you were following a tutorial or something, but please have a look at [this post](https://blogs.msdn.microsoft.com/webdev/2017/02/14/building-single-page-applications-on-asp-net-core-with-javascriptservices/) and its *Option 1: Running via the Command Line*, or for more general info, see https://docs.microsoft.com/en-us/aspnet/core/fundamentals/environments
