### ISSUE TITLE
Repository code style

### ISSUE THREAD

**Issue by laskoviymishka** [aspnet/JavaScriptServices#84]
Hi i'm trying to implement couple enhancement into this repository but faced with couple code style problems.
It reaaaaly hard to jump into code when it bad formated. Right now there is total mess in couple areas:

1. Where to place `{`. Some code written in java style, some code in c#. Sometime both this aproach live in really same file.
2. Single file agreement. It really not really usefull when you have more than one class in single file. 

Also there is couple light problems with library design:

1. To much static stuff, which could be easily replaced by DI. It not hard to fix actually. 
2. Total count of unit tests - 0. At this point nothing to say, but threre is already issue for these (#9).

In a fact there is a reference to aspnet contributing guide which is not followed.
I understand that this repository is mostly playground for experiments, but such problems make it really hard to perform any reasonable contribution in it for anyone except author.

I'm not blaming anyone for this. I just try to help made this tools production ready (I have big plan for this technology). 

So i propose to perform some refactor for this code. 

1. Reformat all code according to common aspnet standarts (4 space, private field with _, c# style of `{` bla-bla). 
2. Extract all classes and interfaces into separate files
3. Remove dependency `Prerenderer` static class inside of tag helper to some `IPrerenderer` interface, which be injected via standart DI process (and could be mocked for testing purpose). And remove all possible static accessors and classes  for better testability and extensibility.
4. Add unit tests for all this stuff (well this issue already exist).

Any thoughts on this @SteveSandersonMS ?

**Comment by SteveSandersonMS** [comment]
Thanks for raising this. It ties in with plans I was already working towards. The code style stuff just comes from my personal preferences, but you're right that as this becomes more a part of ASP.NET it does need to conform to the style of its peers.

> Reformat all code according to common aspnet standarts (4 space, private field with _, c# style of { bla-bla). 

Great, sounds good. The conventions need to be the same as other repos in https://github.com/aspnet/.

If you want to do this for any files, I'd be pleased to take a pull request (or no worries if not - I will do it for all files eventually). But one thing I'd ask: please ensure that pull requests for style changes contain **only style changes and zero functional differences - no refactoring or anything like that**. Actual functional differences or nontrivial refactorings should be in separate pull requests, so that the code can be reviewed effectively.

It might be a good plan to try to sweep through the whole repo with style changes before doing anything else, because otherwise there will end up being complex order dependencies between different pull requests. Don't want to get into a situation where a functional change has to be packaged with a style change or vice-versa.

> Extract all classes and interfaces into separate files

Great. I'd count "splitting a file into two files without otherwise changing the functionality" as a trivial mechanical change and could be included in code style pull requests.

> Remove dependency Prerenderer static class inside of tag helper to some IPrerenderer interface

No objections, assuming it doesn't change the API for developers who aren't trying to configure anything. It should remain usable with no extra config added to `Startup.cs`.

> Add unit tests for all this stuff

Also great. As for what should be tested and how, more discussion would be useful.

Thanks for your involvement here!

**Comment by SteveSandersonMS** [comment]
Also please note it's going to be a week before I attend to any issues in this repo as I'll be otherwise occupied for that period.

**Comment by laskoviymishka** [comment]
I can handle this issue, and you are right about refactoring PRs. There's should be zero functionality changes in it. If you not be accessible can you may be grant for me a commit permission to this repo? I'm not sure does it possible or not regards to MS permissions policy. But I swear to not break anything :). Just cleaning up some stuff here. Every new feature will be proposed as a regular PRs.
