### ISSUE TITLE
Counter doesn't work in IE11 react-redux example

### ISSUE THREAD

**Issue by jckh1234** [aspnet/JavaScriptServices#854]
I just installed this generator and created a project using React-Redux config

and then dotnet run

In IE 11, click on the Increment button on Counter does nothing.
No error show in console.

It works on Chrome.

**Comment by SteveSandersonMS** [comment]
IE requires some extra polyfills. If you need to support it, run:

    npm install --save corejs

... and then at the top of your `boot-client.tsx` file, add this:

    import 'core-js/shim';

We haven't included those polyfills by default because not a lot of people need them, and they make the compiled application bigger. However we might review this if we get more reports along these lines. Hope that's OK!

**Comment by SteveSandersonMS** [comment]
> No error show in console.

BTW there are errors in the console if you don't have the polyfills. Note that IE doesn't show console entries that were posted before you opened the console window, so you might need to be in the habit of reloading the page while the console is opened if you need to see errors :)
