### ISSUE TITLE
Unable to run on Azure - Failed to start Node process

### ISSUE THREAD

**Issue by kiwijus** [aspnet/JavaScriptServices#874]
I am unable to deploy my application to azure, I get the following error saying node is not available:

![image](https://cloud.githubusercontent.com/assets/16914559/25104211/5eab1568-23b7-11e7-85d7-7de5289cc934.png)

I have already tried setting WEBSITE_NODE_DEFAULT_VERSION to the version on the Azure web service (6.10.0) and also checked the version using the console which returns the correct version: 
![image](https://cloud.githubusercontent.com/assets/16914559/25104324/babd5078-23b7-11e7-8825-4238a70eb350.png)

I'm now stuck at what else to try!

**Comment by rgamage** [comment]
I have the same issue, trying to publish the Angluar2 SPA template.  Anyone have any ideas to troubleshoot this issue?

**Comment by rgamage** [comment]
Update - my issue turned out to be that I specified a version of node that does not exist on my Azure environment.  I specified v 6.10.3.  Looking at the Azure CLI, in the program files (x86)\nodejs dir, you can see which versions of Node are installed. Make sure you pick one of those versions.  This resolved my issue.

**Comment by SteveSandersonMS** [comment]
Thanks @rgamage for confirming that worked.

I also just checked today and Azure deployment worked out-of-the-box with no config needed (because new web apps on Azure automatically use Node 6.x at the time of writing).

Closing as resolved, but please let me know if you are still hitting this, and give detailed repro steps. Thanks!
