### ISSUE TITLE
Difference between MVC & Angular symbiotic project, vs. them being separate?

### ISSUE THREAD

**Issue by amivit** [aspnet/JavaScriptServices#879]
What specific advantages would I get from generating a MVC+Angular integrated project via. yo aspnetcore-spa, as opposed to using a pure [angular boilerplate](https://github.com/AngularClass/angular2-webpack-starter) in a separate project, but it talking with my REST MVC Web-api's backend running by itself?

I've been working on an MVC project with basic views, but would like to spike out for an angular frontend.
I know I can simply consume my MVC REST web-api's from angular, but what exactly am I losing as opposed to doing everything over in a fully integrated angular & mvc single project.

Is it simply a quesiton of ease of life? Press F5 to launch both back- and frontend?

**Comment by MarkPieszak** [comment]
You're also gaining server side rendering of your Application in this case, where the app gets serialized to a string on the server and sent to the browser as HTML. So with the possibility of better perceived performance you get SEO &a social media sharing benefits as well.

The only downside is that it raises the complexity by a lot, as dependency injection and being very cautious which libraries you chose becomes more paramount. (Since everything is rendering in 2 platforms, not just the browser anymore).

Good news is we have plans to improve universal within Angular (down the line) to better handle 3rd party libraries that aren't very server friendly. 

So it just depends on what you want, if you don't need all of that I'd honestly not integrate the 2. The CLI will be all you need.
