### ISSUE TITLE
domain-task: TypeScript cannot find names "Request" and "RequestInit"

### ISSUE THREAD

**Issue by robedmo** [aspnet/JavaScriptServices#887]
After setting up the ReactReduxSpa template, Visual Studio is listing errors from the following files in the `domain-task` package (the errors don't always appear; to force them to show up, open one of the files):
- `/fetch.d.ts`
- `/src/fetch.ts`

For both files, the errors are about being unable to find the names `Request` and `RequestInit`. It seems that these are interfaces from `isomorphic-fetch`, on which `domain-task` depends.

I was able to fix these errors by taking the following steps:
- Add a dependency to my project's package.json for `@types/isomorphic-fetch`. This fixed the errors in `/src/fetch.ts`.
- Add the statement `import 'isomorphic-fetch';` to the top of `/fetch.d.ts`. Without this the file is still unable to find the names.

I think the `domain-task` package should be updated to include `@types/isomorphic-fetch` as a dependency and to import `isomorphic-fetch` in `/fetch.d.ts`. I'm new to TypeScript so if I've missed anything or did something wrong to fix the problem I'd appreciate any feedback.

Edit: I also noticed that `aspnet-prerendering` installs it's own instance of `domain-task` (`aspnet-prerendering` depends on version 2.x.x of `domain-task` while the project directly depends on version 3.x.x). This instance would also need to be fixed in the same way, either by making `aspnet-prerendering` depend on `domain-task` version 3.x.x or by releasing a new 2.x.x version as well.

**Comment by SteveSandersonMS** [comment]
I'm not certain I understand the issue you're raising. Does this somehow affect your builds, or the application at runtime? If it's just that manually opening a `.d.ts` file from your `node_modules` dir in VS (which is not a typical scenario) shows a red squiggly underline, I'm not sure that it would lead to any problem.

> Edit: I also noticed that aspnet-prerendering installs it's own instance of domain-task

Yes, in general that's how NPM works and is fine.

I hope you don't mind, but I'll close this because it doesn't appear that there's a problem that would affect anyone in any typical scenario. If I'm mistaken and there are cases where this actually causes build or runtime problems, could you please reopen with details? Thanks!
