### ISSUE TITLE
React: Server side redirects that rely on data fetching. 

### ISSUE THREAD

**Issue by andrewl913** [aspnet/JavaScriptServices#896]
I am currently hitting bottleneck with handling server side redirects that require a DB fetch to get the resolved redirect location. The naive approach was making a request in the onEnter of the matched route.  With this method, the store will be configured and  renderToString will be called 3 times with 2 of those times  occuring before the domainTasks resolve. I have a workaround that uses function generators, but I figured there is a better method of doing this.

**Comment by SteveSandersonMS** [comment]
Interesting question. I'm afraid I don't personally have any better suggestion than what you currently have!

I'll mark this as closed since as far as I can tell it doesn't imply any bug or missing feature in the code here, but if you investigate this further and decide that there's something in particular we should change, please let us know!
