### ISSUE TITLE
Passing Environment Variables to 

### ISSUE THREAD

**Issue by levarcooper** [aspnet/JavaScriptServices#900]
I'm having issues trying to pass environment variables (API Keys, etc) into angular. I've followed the recommendations in the documentation but `Zone.current.get("PROPERTY");` is undefined both on the server and client-side. Here's my code:

**Index.cshtml**
`...
<app asp-prerender-module="ClientApp/dist/main-server" asp-prerender-data="new {
        secretURL = @Environment.GetEnvironmentVariable("secretURL "),
        secretKey = @Environment.GetEnvironmentVariable("secretKey ")
        }">Preparing your content...</app>
...`

**boot-server.ts**
`...
export default function (params: any) : Promise<{ html: string, globals?: any }> {
    return new Promise((resolve, reject) => {
        const requestZone = Zone.current.fork({
            name: 'angular-universal request',
            properties: {
                baseUrl: '/',
                requestUrl: params.url,
                originUrl: params.origin,
                preboot: false,
                specialKey: params.data.specialKey,
                specialURL: params.data.specialURL,
                document: '<!DOCTYPE html><html><head></head><body><app></app></body></html>'
            },
            onHandleError: (parentZone, currentZone, targetZone, error) => {
                reject(error);
                return true;
            }
        });
        return requestZone.run<Promise<string>>(() => platform.serializeModule(AppModule)).then(html => {
            resolve({
                html: html
            });
        }, reject);
    });
}
...`

**app.module**
`...
export class AppModule {
    constructor() {
        console.log(Zone.current.get("specialURL")); // undefined
    }
}
...`

Alternatively, I've tried using webpack's DefinePlugin but was still unsuccessful in passing the properties to my application. The webpack code is below.

**webpack.config.js**
`...
var DefinePlugin = require('webpack/lib/DefinePlugin');
...
var clientBundleConfig = merge(sharedConfig, {
    entry: { 'main-client': './ClientApp/boot-client.ts' },
    output: { path: path.join(__dirname, clientBundleOutputDir) },
    plugins: [
        new webpack.DllReferencePlugin({
            context: __dirname,
            manifest: require('./wwwroot/dist/vendor-manifest.json')
        }),
        new webpack.DefinePlugin({
            'process.env': {
                'SECRET_KEY': JSON.stringify('SecretKey')
            }
        })
    ].concat(isDevBuild ? [ ...`

**Comment by SteveSandersonMS** [comment]
Your code is mostly correct, but there are some inconsistencies that prevent it from working.

In your `aspnet-prerender-data` attribute, your values are called `secretURL` and `secretKey`, but in your `boot.ts` file, you're trying to read them as `specialURL` and `specialKey`.

Also in your `GetEnvironmentVariable` calls, you have trailing spaces (e.g., `@Environment.GetEnvironmentVariable("secretURL ")`) which might also prevent it from working.

Finally, when I tried, I had to use single quotes around the `aspnet-prerender-data` attribute value to avoid clashes with the double quotes inside it.

Having resolved all these, you should get your data passed through during server-side prerendering. Note that the same data won't be available during client-side rendering, because there's no logic in `boot-client.ts` to put it here (or at least you didn't imply that there is from your post).

**Comment by levarcooper** [comment]
Thanks for the reply, Steve. Sorry for the typos... those were added in place of the real values. The issues you mentioned (single quotes, naming consistency, space) are not present in my actual code. My question is actually with regard to adding logic to pass those variables during client-side rendering.

**Comment by anpetral-msft** [comment]
I would be interested in hearing this too: how to pass environment variables to the client side renderer, if possible at all.

**Comment by J0hnRoger** [comment]
I'm interesting too. Redux allows us to configure different files in function of the current environment (dev or production, example here: [configureStore redux](https://github.com/reactjs/redux/blob/master/examples/real-world/src/store/configureStore.js)) 

Can we access to the  $Env:ASPNETCORE_ENVIRONMENT in the client side, like `process.env.NODE_ENV` in NodeJs ?
