### ISSUE TITLE
Debugging server-side/pre-rendering JavaScript

### ISSUE THREAD

**Issue by rosieks** [aspnet/JavaScriptServices#901]
If some JavaScript is run on pre-rendering phase I receive exception. But how can I diagnose what's exactly wrong? Is there any way to debug that code?

**Comment by andrewl913** [comment]
Since it is all on node, I usually throw a bunch of console logs in app-server

**Comment by DanHarman** [comment]
This might help:

https://github.com/aspnet/JavaScriptServices/tree/dev/src/Microsoft.AspNetCore.SpaServices#debugging-your-javascripttypescript-code-when-it-runs-on-the-server

**Comment by rosieks** [comment]
@DanHarman - thank's that helps. I will keep this open to discuss if it's possible to have debugging experience in Visual Studio.

**Comment by SteveSandersonMS** [comment]
@DanHarman Thanks for answering!

**Comment by SteveSandersonMS** [comment]
> discuss if it's possible to have debugging experience in Visual Studio.

Yes, please see the docs starting at https://github.com/aspnet/JavaScriptServices/tree/dev/src/Microsoft.AspNetCore.SpaServices#debugging-your-javascripttypescript-code-when-its-running-in-a-browser - it describes how to connect the VS debugger.

**Comment by rosieks** [comment]
@SteveSandersonMS - Thanks for answer, but as I understand this describes only debugging client-side code and the only way to debug server-side javascript/typescript is Node Inspector.

**Comment by MarkPieszak** [comment]
Yes basically Node inspector is the only way (at the moment) to debug server-side JS execution. @rosieks

**Comment by JohnGalt1717** [comment]
The issue with this is if you have a DI Error (you just get a generic error message instead of telling you the actual root error of the DI Error in the console) while the app is spinning up you'll never get the URL for the node inspector so you can't find where to go to hook to it and get the actual issue.

This is a major blocker for us because we cannot find any way to get this message and as a result we can use server side pre-render which is vital for our public release in the next 2 weeks.

**Comment by jubishkammily** [comment]
this link for debugging gives me page not found error . Can you please update the correct link ?
