### ISSUE TITLE
1.0.0 release

### ISSUE THREAD

**Issue by dazinator** [aspnet/JavaScriptServices#904]
Hi,
I have an asp.net core 1.0.0 compatible library,
I was consuming beta's of `Microsoft.AspNetCore.NodeService`, version `1.0.0-beta-000021` to be precise.
I have upgraded my solution recently from project.json (vs2015) to csproj (vs2017) and I notice that tests that previous succeeded, now fail:

![image](https://cloud.githubusercontent.com/assets/3176632/25543428/719e538e-2c4e-11e7-8326-547e41d81735.png)

Downgrading to `1.0.0-beta-000020` seems solves this problem - not sure why. 
I have created a repro here: https://github.com/dazinator/NetPack/tree/repro-assy-resolve (just open and run the unit test to see what I mean): 

@natemcmaster suggested I should upgrade to the RTM version anyway. However I can't see a release of `nodeservices` for asp.net core 1.0.0 - it seems to jump from the beta's which target 1.0.0 to the RTM which targets `1.1.0` dependencies. If I upgrade to the RTM, I will have to upgrade all consuming applications from 1.0.0 to 1.1.0 - and sadly, at the current time, this is too much work, for which there is not enough time.

So my question is - would you perhaps consider releasing a version of nodeservices that targets asp.net core 1.0.0 dependencies? 

Pretty please with a cherry on top.

**Comment by dazinator** [comment]
.. Anticipating that releasing a version of nodeservices for asp.net core 1.0.0 isn't an option, then I'd be very greatful if perhaps you could help identify why the `1.0.0-beta-000021` version of the nuget package seems to produce assembly singing problems when attempting to run a unit test in vs2017 as per my repro here: https://github.com/dazinator/NetPack/tree/repro-assy-resolve

**Comment by SteveSandersonMS** [comment]
@dazinator It's possible that `1.0.0-beta-000021` is just not strong named. I don't recall exactly when we started doing strong naming on this package - it was a long time ago, but maybe was roughly when we move to take the 1.1.0 dependencies.

> Anticipating that releasing a version of nodeservices for asp.net core 1.0.0 isn't an option

I'm afraid not! We have many other work items to focus on, only one person is asking for this one, and it doesn't add any long-term value because eventually nobody will need that anyway. So I'm afraid that job would never get to the front of the priority queue.

**Comment by dazinator** [comment]
Ok thanks
