### ISSUE TITLE
Vue.js Framework Support

### ISSUE THREAD

**Issue by ajayj-cmas** [aspnet/JavaScriptServices#906]
Since [Vue.js](https://vuejs.org/) is emerging as a popular front-end framework, adding support for it would really be a great thing.

**Comment by sutherlandm2** [comment]
It's currently an option when I use the Yeoman generator.

**Comment by chrismckelt** [comment]
Is this what you are looking for?

https://github.com/aspnet/JavaScriptServices/tree/dev/templates/VueSpa

**Comment by ajayj-cmas** [comment]
Cool. I didn't know that it exist :) Thanks.

**Comment by ajayj-cmas** [comment]
When I ran `yo aspnetcore-spa` I don't see Vue as an option.
<img width="365" alt="screen shot 2017-05-02 at 7 38 37 pm" src="https://cloud.githubusercontent.com/assets/24539524/25621485/1df049bc-2f6f-11e7-9f29-054cbce40938.png">

**Comment by SteveSandersonMS** [comment]
@ajayj-cmas Please update to the latest generator (run `npm install -g generator-aspnetcore-spa`).

**Comment by ajayj-cmas** [comment]
@SteveSandersonMS  I uninstalled  `generator-aspnetcore-spa` package and installed it again, still I don't see Vue.js option in the framework list.

**Comment by SteveSandersonMS** [comment]
@ajayj-cmas It's definitely included in the latest generator (v0.9.1). I'm not sure why your upgrade isn't taking effect - it's probably something to do with how you have Node installed. You might need to reinstall Node, or otherwise debug where it's looking for the packages. If you try on a clean machine, I'm sure you'll see Vue is there.
