### ISSUE TITLE
Cannot Use Visual Studio 2017 Add Controller Feature

### ISSUE THREAD

**Issue by jkruer01** [aspnet/JavaScriptServices#909]
If you open the project file in Visual Studio right click the controllers folder and chose add new Controller, you will get an error that states "No executable found matching command dotnet-aspnet-codegenerator".

In order to fix this issue, the following lines need to be added to the CSProj file:
```xml
    <ItemGroup>
        <DotNetCliToolReference Include="Microsoft.VisualStudio.Web.CodeGeneration.Tools" Version="1.0.0" />
    </ItemGroup>
```

Stack Overflow Question for Reference:
http://stackoverflow.com/questions/41450148/no-executables-found-matching-command-dotnet-aspnet-codegenerator

**Comment by SteveSandersonMS** [comment]
Thanks very much for raising this point. I did some investigation to track down what's going on.

The templates here are trying to be consistent with the default `mvc` template, which doesn't include the `Microsoft.VisualStudio.Web.CodeGeneration.Tools` package by default either. I'm not totally sure why it doesn't, but it doesn't, and we want to stay consistent with that.

However, when I click "Add Controller", I don't get the error you describe. Instead VS gives a prompt like this:

![image](https://cloud.githubusercontent.com/assets/1101362/26194700/2eb3e2d8-3bb1-11e7-8ced-efca45f8885f.png)

... which sorts out the package dependencies.

I'm not sure why you're not getting that prompt. Perhaps you just need to update to a newer version of VS2017, but in any case it's a separate question.

Since we're trying to be consistent with the `mvc` template, and since VS2017 has a built-in system for setting up this dependency (albeit not working in your case, but that's a separate issue), I'll close this. Hope that seems reasonable, and thanks again for bringing this up!

For anyone else who gets the error (rather than the VS prompt that you should get), please see @jkruer01's manual workaround above.

**Comment by jkruer01** [comment]
Thanks @SteveSandersonMS!
