### ISSUE TITLE
baseUrl is not always correct?

### ISSUE THREAD

**Issue by rosieks** [aspnet/JavaScriptServices#912]
In `aspnet-prendering` package `baseUrl` of the `domain-task` package is setup to absolute path of request as I understand this line https://github.com/aspnet/JavaScriptServices/blob/dev/src/Microsoft.AspNetCore.SpaServices/npm/aspnet-prerendering/src/Prerendering.ts#L38

It works fine when I try to reach the following pages:
* http://localhost:5000/
* http://localhost:5000/customer

When I call controller with address `api/customers` then it's changed to http://localhost:5000/api/customers.

But when I have page with address http://localhost:5000/customer/new then my http call is effectively http://localhost:5000/customer/api/customers which is wrong. I would expect that baseUrl will be set to something like `~/`

Is there something what I missing?

**Comment by SteveSandersonMS** [comment]
You should probably change your HTTP calls to use base-independent URLs, e.g., `/api/customers` instead of `api/customers`. Then it will work no matter what URL you're on.

We *could* change the prerendering logic to obtain the base URL from the application hosting information, but then there'd be an inconsistency between server-side code that knows about this, and client-side code that doesn't. So it's better if you just use slash-rooted URLs to get consistent behaviour everywhere.

**Comment by rosieks** [comment]
But then slash will work only if my site is deployed directly under some domain for example: www.my-site.com, and will not work if it's for example www.my-site.com/staging/.

Maybe this address could be exported to client side like as well like redux store state.

**Comment by rosieks** [comment]
Just noticed that the same issue is with images, but this one can be easily solved by `<base>` element: https://www.w3schools.com/tags/tag_base.asp.

    <base href="~/" />
