### ISSUE TITLE
Angular routes with a canActivate guard not working (sometimes) with prerendering

### ISSUE THREAD

**Issue by bperry77** [aspnet/JavaScriptServices#913]
I have routes defined where the home route is a type of landing page.  Other routes within the app are protected with an authentication guard.

In prerender mode I see the following behaviour:

1.  In-app routing, typically using router.navigate or routerLink works fine from the landing page.  It also redirects correctly if my auth guard fails (returns false).
2.  Direct navigation to a protected route by entering the url in a browser's address bar gives me the following error:

`Exception: Call to Node module failed with error: Error: Uncaught (in promise): TypeError: You provided 'undefined' where a stream was expected. You can provide an Observable, Promise, Array, or Iterable.
TypeError: You provided 'undefined' where a stream was expected. You can provide an Observable, Promise, Array, or Iterable.
at Object.subscribeToResult (/home/vcap/app/ClientApp/dist/vendor.js:69061:27)`

If I turn pre-rendering off, I do not see the error described in 2.

**Comment by SteveSandersonMS** [comment]
What version of Angular are you using? I've just tried this with the latest template that's using Angular 4, and that error doesn't occur. Instead, it renders a blank page (whether or not that's what you want, it appears to be Angular's default, which is not a behaviour we control).

Since this is a no-repro, I'll mark this as closed (most likely having been fixed implicitly by a newer version of Angular). However if I'm wrong and you can still repro this on the latest template which uses Angular 4, could you post more detailed repro steps, starting from a clean new project? Thanks!
