### ISSUE TITLE
Support for Semantic UI

### ISSUE THREAD

**Issue by Gimly** [aspnet/JavaScriptServices#916]
Hi,
I'd like to use Semantic UI instead of Bootstrap for an application and I'm a bit lost on how to integrate it into the SPA template. It would be nice if we had the choice from the generator directly, like for the aspnet generator.

In the meantime, if anyone has an idea that could send me to the right direction, I'll be very happy. Thanks!

**Comment by SteveSandersonMS** [comment]
Thanks for the suggestion. We're unlikely to make this a native option in the generator, because this is just one of dozens of possible third-party libraries that people request, and it would be impractical to try to cover everything. I hope you agree that's reasonable!

As for how to integrate Semantic UI, I'd start by looking at how others have added it to their Webpack builds, since the project templates here just use Webpack in a standard way, so similar techniques should apply: https://github.com/Semantic-Org/Semantic-UI/issues/3533
