### ISSUE TITLE
Please provide guidance on how to upgrade

### ISSUE THREAD

**Issue by aligneddev** [aspnet/JavaScriptServices#920]
It would be really helpful if there was instructions provided on how to upgrade from one JavaScriptServices version to the next. I need to update my Aurelia app to pull in the [HMR](https://github.com/aspnet/JavaScriptServices/pull/853) that was just completed.

**Comment by SteveSandersonMS** [comment]
The changes we're making to the libraries don't require you to change your application. The changes to the templates also don't require you to update in any way, since they are templates, rather than something you're taking an ongoing dependency on.

However I appreciate it's nice to get the features in the latest templates. @MeirionHughes, do you have any advice for people who want to update their Aurelia apps? Failing that, please check the diff in the relevant commits (37df30929cbb6b0b1cb41cf66c12413b873694e6, e3a8c13c22d72eb75cf6fd636c4731eeba627fcc, 018a3e65ffe5bcafb1032467ec4bdbac523732ed) - applying the same changes to your app is the quickest way to follow along - I'm not aware of any shortcut beyond that. Hope that's OK!

**Comment by aligneddev** [comment]
That helps, thank you. I was wondering if I could update through a command-line, similar to creating the project with `dotnet new aurelia` or the yoeman generator.

**Comment by aligneddev** [comment]
This was pretty easy.
I overwrote my files from those commits, added in PLATFORM.moduleName( for the routing and a few other places.
ran `npm install` after the package.json changes
then `npm update` after a run-time error about async not being available.
Then after that I can add to my html and it shows up in the browser without refreshing!!

[Here's my commit](https://github.com/aligneddev/aureliaEnergyJSServices/commit/6a34babd2b1476181e853e75a6b5dde9d53dedd4)

**Comment by MeirionHughes** [comment]
Glad you got it working. There are only a few important things that need to be done really (for anyone still unclear). 

* installing  `"aurelia-webpack-plugin": "^2.0.0-rc.2",`
* `publicPath: '/dist/',` in webpack.json
* `new AureliaPlugin({ aureliaApp: 'boot' })` in plugins. 

the style loader was removed (for new templates) because Aurelia tries to load them up at runtime if you require the files within your html templates; and they are missing due to the style-bundling.
