### ISSUE TITLE
Question reactredux and Node.js

### ISSUE THREAD

**Issue by EmmaHansson** [aspnet/JavaScriptServices#932]
I simply interesting in one question, because I don't really know how it works in result.
Expert thought needed.

If I use reactredux. And then I publish it to somewhere (for example local folder).
In published folder I have a lot of .dll files and some fat .js (I guess they made by webpack).

Theoretically I guess in this case I will # **need not any Node.js at production** server where I gonna deploy this stuff. Is that true ?

**Comment by SteveSandersonMS** [comment]
If you're *not* doing server-side prerendering, then you will not need Node.js on your production server, because all the JS will be executed on the client side.

If you *are* doing server-side prerendering (which is the default in the React-Redux template in this repo), then you *do* need Node.js on your production server, because the prerendering process involves executing your JavaScript code on the server.
