### ISSUE TITLE
aspnetcore spa for angular 4 template

### ISSUE THREAD

**Issue by kannan2106** [aspnet/JavaScriptServices#954]
is there any aspnetcore spa for angular 4 template available?

**Comment by SteveSandersonMS** [comment]
Yes, the current template packages (version 0.9.3) produce Angular 4 applications. Just update your template package and create a new app :)

**Comment by Axel3232** [comment]
Nice, those this template includes AOT feature ?

**Comment by kannan2106** [comment]
thanks @SteveSandersonMS :)

**Comment by SteveSandersonMS** [comment]
@Axel3232 No, that's something we're still looking into adding. If you find what seems like a clean and simple setup for that, please let us know!

**Comment by Semm12** [comment]
Hi I add ng-boostrap in angular 4 spa template but i got error 

Exception: Call to Node module failed with error: Prerendering timed out after 30000ms because the boot function in 'ClientApp/dist/main-server' returned a promise that did not resolve or reject. Make sure that your boot function always resolves or rejects its promise. You can change the timeout value using the 'asp-prerender-timeout' tag helper.

some help

my conf files

entry: {
            vendor: [
                '@angular/animations',
                '@angular/common',
                '@angular/compiler',
                '@angular/core',
                '@angular/forms',
                '@angular/http',
                '@angular/platform-browser',
                '@angular/platform-browser-dynamic',
                '@angular/router',
                'bootstrap',
                'bootstrap/dist/css/bootstrap.css',
                'es6-shim',
                'es6-promise',
                'event-source-polyfill',
                'jquery',
                'zone.js',
                '@ng-bootstrap/ng-bootstrap'
            ]
        },


import { NgbModule } from '@ng-bootstrap/ng-bootstrap';
import { AppComponent } from './components/app/app.component'
import { NavMenuComponent } from './components/navmenu/navmenu.component';
import { HomeComponent } from './components/home/home.component';
import { FetchDataComponent } from './components/fetchdata/fetchdata.component';
import { CounterComponent } from './components/counter/counter.component';
import { ScrollerDirective } from './components/directive/scrool.directive';


export const sharedConfig: NgModule = {
    bootstrap: [ AppComponent ],
    declarations: [
        AppComponent,
        NavMenuComponent,
        CounterComponent,
        FetchDataComponent,
        HomeComponent,
        ScrollerDirective
    ],
    imports: [
        NgbModule.forRoot(),
        RouterModule.forRoot([
            { path: '', redirectTo: 'home', pathMatch: 'full' },
            { path: 'home', component: HomeComponent },
            { path: 'counter', component: CounterComponent },
            { path: 'fetch-data', component: FetchDataComponent },
            { path: '**', redirectTo: 'home' }
        ])
    ]
};
