### ISSUE TITLE
Unable to resolve 'Microsoft.AspNetCore.SpaServices (>= 2.0.0)

### ISSUE THREAD

**Issue by bdicioccio** [aspnet/JavaScriptServices#959]
I am getting the following error after downloading the latest dev branch (Angular2Spa) during package restore:
Unable to resolve 'Microsoft.AspNetCore.SpaServices (>= 2.0.0)' for '.NETCoreApp,Version=v2.0'.

I have the latest preview version of VS2017 and
dotnet --version =  2.0.0-preview1-005977

I am able to go into VS2017 Preview and create a new ASP.NET Core Web API application using 2.0.0 and everything works fine. I see this in the .csproj:
`<PackageReference Include="Microsoft.AspNetCore.All" Version="2.0.0-preview1-final" />`

Not sure why the error is occurring after downloading the dev branch and adding the AngularSpa template to the same solution with the .NET Core 2.0 Web API.

**Comment by SteveSandersonMS** [comment]
Until the 2.0.0 packages are published as final releases, you probably just need to add a `NuGet.config` file that configures your tooling to fetch packages from the prerelease MyGet feed, like this: https://github.com/aspnet/JavaScriptServices/blob/dev/NuGet.config

**Note for anyone else reading**: If you just use the project templates here in the regular way (e.g., via `dotnet new`), then this will not affect you - you'll still be using the 1.x packages that are published as final versions. The only way it affects anyone is if you pull sources directly from this repo rather than using the template packages.
