### ISSUE TITLE
Add VueVuex template which works same as ReactRedux

### ISSUE THREAD

**Issue by mika76** [aspnet/JavaScriptServices#962]
I think the two frameworks have the same functionality so a similar template would be helpful...

**Comment by villanus** [comment]
I think nuxt is what is really necessary for a vue spa

**Comment by mika76** [comment]
I think "necessary" is a strong word here - what does Nuxt supply that you can't do with basic Vue and Vuex?

**Comment by SteveSandersonMS** [comment]
Thanks for the suggestion! @MarkPieszak has already published a Vuex-based template here: https://github.com/MarkPieszak/aspnetcore-Vue-starter

In general it's not our goal in this repo to provide templates for a really wide range of framework combinations. It's only scalable if people publish and support their own templates. That's why `dotnet new` is fully extensible. If you want to make your own Vuex or Nuxt template, please feel free to copy the basic design of the templates here and let us know.

I'll close this as it's not something we'd take action on in the short term. If people keep asking, and if there is a really clear consensus on which specific state framework becomes standard, we can definitely reconsider. Hope that's OK!

**Comment by mika76** [comment]
Thanks @SteveSandersonMS if there is one available then that's great 😄
