### ISSUE TITLE
Question: Does ReactSpa template really need *isomorphic*-fetch?

### ISSUE THREAD

**Issue by antmdvs** [aspnet/JavaScriptServices#970]
..or would whatwg-fetch be sufficient, considering that ReactSpa doesn't support SSR?

**Comment by SteveSandersonMS** [comment]
It may well be that `whatwg-fetch` would be sufficient, but since (in the browser) `isomorphic-fetch` is just a thin wrapper around that, there's probably no substantial disadvantage to using `isomorphic-fetch`.

If it turns out to cause specific problems we can look at changing it. Otherwise, for consistency across the templates, it would be good to keep it as-is.
