### ISSUE TITLE
React template missing a couple of typings packages

### ISSUE THREAD

**Issue by enkafan** [aspnet/JavaScriptServices#975]
Resharper throws a couple of errors related to the hotloader and router components. Adding these definitions to packages.json seems to resolve things there. Versions don't line up though, but I'm not seeing any issues.

```
    "@types/react-hot-loader": "3.0.1",
    "@types/react-router-dom": "4.0.4",
```

Happy to submit a PR if this is the right direction to take.

**Comment by SteveSandersonMS** [comment]
Could you clarify exactly what errors you're seeing, and why there's a difference between what Resharper reports and what the TypeScript compiler itself reports?

If this is a bug in Resharper, I think we would want them to fix that rather than add workarounds. However if Resharper is somehow more correct than TypeScript is natively (in such a way that TypeScript is planning to update to be the same) then yes we would like to allow for that :)

**Comment by enkafan** [comment]
You bet. Sorry for the lack of info, I thought this was pretty cut and dry but that might be due to some false assumptions I'm making. 

So after loading up a new solution I see errors from R# (and in Rider) such as this

![image](https://cloud.githubusercontent.com/assets/2447331/26467522/f4b9cf38-4160-11e7-908e-1388be83a90a.png)

Now everything runs fine and the compiler is happy, it is just R#'s intellisense not being able to figure out what's going on. My understanding is that's why where the typings come into play. I notice the ones R# isn't happy with don't have an entry in packages.json but do exist out on NPM so I went ahead and added them and the errors went away so I figured that was the end of the story. 

To complicate matters, I didn't see this in VS Code. I suspected that this was due to the [Automatic Type Acquisition](https://code.visualstudio.com/docs/languages/javascript#_automatic-type-acquisition) or it just being a bit more flexible about missing typing files, but again just making blind guess as to how the magic happens. I suspect it is the later because if I add `taco="yummy"` to the AppContainer element it is fine with it but running `npm install --save-dev @types/react-hot-loader` results in VS Code's intellisense picking up the bad attribute

![image](https://cloud.githubusercontent.com/assets/2447331/26467963/aba73b26-4162-11e7-9ac8-ec1cf8e065ba.png)

**Comment by SteveSandersonMS** [comment]
Since this is specific to Resharper, and isn't a complaint from the TypeScript compiler itself, I can only understand it as a bug or missing feature in Resharper. I'm glad you've got a solution for your own purposes and hopefully anyone else using the same system will be able to do the same thing.

We probably wouldn't want to put in special workarounds by default for bugs in third-party tools, when those third-party tools will probably get fixed soon anyway. I'll close. Hope that seems reasonable!

**Comment by stephtr** [comment]
That's not an issue with Resharper. ```react-hot-loader``` doesn't supply a TypeScript definition. Setting ```"strict": true``` in tsconfig.json throws ```TS7016: Could not find a declaration file for module 'react-hot-loader'. './node_module
s/react-hot-loader/index.js' implicitly has an 'any' type.```, which can be resolved by installing ```@types/react-hot-loader```.

**Comment by SteveSandersonMS** [comment]
For anyone else reading, @stephtr submitted a PR that includes a reference to the `@types/react-hot-loader` package, which is now merged.
