### ISSUE TITLE
Compile errors

### ISSUE THREAD

**Issue by samcov** [aspnet/JavaScriptServices#981]
I tried this about 7 months ago and nothing but errors in VS2015, now today it's the same in VS2017, this thing isn't compiling right out of the box, any idea why?

[builderrors.txt](https://github.com/aspnet/JavaScriptServices/files/1030247/builderrors.txt)

**Comment by samcov** [comment]
It appears that for whatever reason you have required .net core 2.0 which isn't released yet.

**Comment by cvanslimming** [comment]
You have run a dotnet restore and npm install command first?

**Comment by ADefWebserver** [comment]
If you are puling the GitHub code down and trying to run it you will probably get compile errors because the code is usually "in progress" (this is a good thing 👍). Your particular error is probably that you need .Net 2.0 Preview: https://www.microsoft.com/net/core/preview#windowscmd

If you just want to use JavaScriptServices, try this tutorial: [Hello World Angular 2+ Data Sample Using JavaScriptServices .Net Core and PrimeNg](http://lightswitchhelpwebsite.com/Blog/tabid/61/EntryId/3304/Hello-World-Angular-2-Data-Sample-Using-JavaScriptServices-Net-Core-and-PrimeNg.aspx)

**Comment by samcov** [comment]
Yes, I didn't want to install a preview, I took a quick look and I'll try your tutorial. Thanks!
