### ISSUE TITLE
WebpackDevMiddlewareOptions Es6 webpack

### ISSUE THREAD

**Issue by MartinDawson** [aspnet/JavaScriptServices#985]
Error: Unexpected token 'import' in webpack.config.babel.js

I want to use ES6 syntax in webpack.
The webpack middleware doesn't seem to be requiring babel-register to make webpack work with ES6.

It works if just run webpack-dev-server normally.

Can this be looked in to?

If I could require babel-register somehow then it should work. E.G

node -r babel-register node_modules/.bin/webpack -p --config=webpack.config.babel.js

**Comment by SteveSandersonMS** [comment]
Sounds like your version of Node is too old to recognise `import` directly.

I'm not sure how you would want Babel to be involved, but since none of the templates have any dependency on Babel any more, we most likely would prefer not to add a strict dependency on Babel. If you can come up with a specific proposal for what we should change (e.g., a simple PR) we can certainly consider it though! Hope that's OK.

**Comment by MartinDawson** [comment]
@SteveSandersonMS Thanks for reply. Forgive my ignorance but I'm not sure I understand fully because I don't know how this works behind the scenes.

Is it not possible to somehow require files to be loaded before webpack using this package? Like you can do with Node.js --require? https://nodejs.org/api/cli.html#cli_r_require_module

**Comment by SteveSandersonMS** [comment]
Aha, I see what you mean now. No, sorry, there's no exact equivalent to the `--require` option in the Webpack dev middleware feature.

However, I'd expect it to be possible for you to reference `babel-register` manually if you needed. For example, if you changed your entry point to some other file called `webpack-wrapper.js` containing

```
require('babel-register');
module.exports = require('./webpack.config.js`);
```

... or something like that, and then changed your `Startup.cs` code to:

```
app.UseWebpackDevMiddleware(new WebpackDevMiddlewareOptions
{
    HotModuleReplacement = true,
    ConfigFile = "webpack-wrapper.js"
});
```

... then I'd expect it to have a similar effect. Haven't tested this though, and I'm not familiar with `babel-register` so I don't know for sure whether it has additional requirements.

**Comment by QuantumHive** [comment]
@SteveSandersonMS When trying your untested suggestion, the ES6 `import` syntax gets transpiled correctly by `babel-register`. However a new issue arises and the `WebpackDevMiddleware` throws the following exception:

```
System.AggregateException occurred
  HResult=0x80131500
  Message=One or more errors occurred.
  Source=<Cannot evaluate the exception source>
  StackTrace:
   at System.Threading.Tasks.Task.ThrowIfExceptional(Boolean includeTaskCanceledExceptions)
   at System.Threading.Tasks.Task`1.GetResultCore(Boolean waitCompletionNotification)
   at Microsoft.AspNetCore.Builder.WebpackDevMiddleware.UseWebpackDevMiddleware(IApplicationBuilder appBuilder, WebpackDevMiddlewareOptions options)
   at rowinpt.api.Startup.Configure(IApplicationBuilder app, IHostingEnvironment environment) in D:\dev\quantumhive\rowinpt\src\rowinpt.api\Startup.cs:line 110

Inner Exception 1:
Exception: Call to Node module failed with error: TypeError: Cannot read property 'publicPath' of undefined
    at D:\dev\quantumhive\rowinpt\src\rowinpt.api\node_modules\aspnet-webpack\WebpackDevMiddleware.js:205:59
    at Array.forEach (native)
    at Server.<anonymous> (D:\dev\quantumhive\rowinpt\src\rowinpt.api\node_modules\aspnet-webpack\WebpackDevMiddleware.js:194:32)
    at Server.g (events.js:292:16)
    at emitNone (events.js:86:13)
    at Server.emit (events.js:185:7)
    at emitListeningNT (net.js:1284:10)
    at _combinedTickCallback (internal/process/next_tick.js:77:11)
    at process._tickCallback (internal/process/next_tick.js:104:9)

```

I've already looked into #430, but what's being described there as a possible solution is unrelated to my issue, because I did the following:
- Make the `webpack.config.js` file ES5 compatible
- Using the config file directly from the middleware
- Run the app
- Application is running fine and the middleware is doing it's work

As a reference, this is my `webpack.config.js`:

```
import Path from "path";
import Webpack from "webpack";
import Autoprefixer from "autoprefixer";

//const Path = require("path");
//const Webpack = require("webpack");
//const Autoprefixer = require("autoprefixer");

export default {
    resolve: {
        extensions: ["*", ".js"]
    },

    context: Path.resolve(__dirname, "./App"),
    entry: { main: "./index.js" },
    output: {
        path: Path.resolve(__dirname, "./wwwroot/dist"),
        filename: "[name].js",
        publicPath: "/dist/"
    },

    plugins: [
        new Webpack.DefinePlugin({
            'process.env.NODE_ENV': JSON.stringify("development"),
            __DEV__: true
        })
    ],

    module: {
        rules: [
            { test: /\.jsx?$/, exclude: /node_modules/, loaders: ["babel-loader"] },
            { test: /\.eot(\?v=\d+.\d+.\d+)?$/, loader: "file-loader" },
            { test: /\.woff(2)?(\?v=[0-9]\.[0-9]\.[0-9])?$/, loader: "url-loader?limit=10000&mimetype=application/font-woff" },
            { test: /\.[ot]tf(\?v=\d+.\d+.\d+)?$/, loader: "file-loader?limit=10000&mimetype=application/octet-stream" },
            { test: /\.svg(\?v=\d+\.\d+\.\d+)?$/, loader: "file-loader?limit=10000&mimetype=image/svg+xml" },
            { test: /\.(jpe?g|png|gif)$/i, loader: "file-loader?name=[name].[ext]" },
            { test: /\.ico$/, loader: "file-loader?name=[name].[ext]" },

            {
                test: /(\.css|\.scss|\.sass)$/,
                use: [
                    "style-loader",
                    "css-loader",
                    {
                        loader: "postcss-loader",
                        options: {
                            plugins: [Autoprefixer]
                        }
                    },
                    {
                        loader: "sass-loader",
                        options: {
                            //so I can use @import in my custom styles that are relative to the /styles folder
                            includePaths: [Path.resolve(__dirname, "./App/styles")]
                        }
                    }
                ]
            }
        ]
    }
};

```

My devDependencies in `package.json`:

```
"devDependencies": {
    "aspnet-webpack": "1.0.29",
    "autoprefixer": "7.1.2",
    "babel-cli": "6.24.1",
    "babel-core": "6.25.0",
    "babel-loader": "7.1.1",
    "babel-plugin-transform-object-rest-spread": "6.23.0",
    "babel-plugin-transform-react-constant-elements": "6.9.1",
    "babel-plugin-transform-react-remove-prop-types": "0.2.11",
    "babel-polyfill": "6.23.0",
    "babel-preset-env": "1.5.2",
    "babel-preset-es2015": "6.24.1",
    "babel-preset-react": "6.24.1",
    "babel-register": "6.24.1",
    "css-loader": "0.28.4",
    "extract-text-webpack-plugin": "2.1.0",
    "file-loader": "0.11.2",
    "node-sass": "4.5.3",
    "postcss-loader": "2.0.6",
    "prop-types": "15.5.10",
    "redux-immutable-state-invariant": "2.0.0",
    "rimraf": "2.6.1",
    "sass-loader": "6.0.6",
    "style-loader": "0.18.2",
    "url-loader": "0.5.9",
    "webpack": "3.1.0"
  }
```

**Note:** I'm using `webpack 3.1.0` (which is the latest version as of writing), but I don't expect this to be an issue since the middleware works when using the es5 compliance version of the config file.

**Comment by ljani** [comment]
@QuantumHive You can debug the error by running `webpack.config.js` directly and logging the `module.exports`.

For example, I was trying to setup `webpack.config.ts` with the following `webpack.config.js`:

```
require("ts-node/register");
module.exports = require("./webpack.config.ts");
console.log(module.exports);
```

Running `node webpack.config.js` shows the problem:

```
❯❯❯ node webpack.config.js
{ default:
   { entry: './index.tsx',
     output:
      { path: './dist',
        filename: 'bundle.js' } } }
```

This means that `webpack.config.js` should actually contain this:
```
require("ts-node/register");
module.exports = require("./webpack.config.ts").default;
```
Notice the `.default`, it'll probably solve your problem too. The actual reason for this problem is in the difference between how CommonJS and ES modules handle the default exports.

I too hope a solution to preload modules such as `ts-node/register` before calling the `ConfigFile`.
