### ISSUE TITLE
Two state to one component

### ISSUE THREAD

**Issue by SpyRefused** [aspnet/JavaScriptServices#993]
Hello; I'm quite new to React & Redux. I have taken the spa template React & Redux as a template to develop my app, I have a question I can not solve:

The props of the components are defined as "type", would not be much better as "interface"?

I can not send two ApplicationState state to a single component. That is, starting from the template, in what way can I send FectchData props their own state and Counter state? (If this has any sense....)

Thanks!

**Comment by SteveSandersonMS** [comment]
> The props of the components are defined as "type", would not be much better as "interface"?

That would not really make any difference that I can think of. Types in TypeScript are extremely flexible (far more so than in something like C#). Declaring this as a `type` does not prevent you from mixing in other types in various ways.

>  starting from the template, in what way can I send FectchData props their own state and Counter state? (If this has any sense....)

For example, change the type definition to something like:

```
type WeatherForecastProps =
    { weatherForecasts: WeatherForecastsState.WeatherForecastsState, counter: CounterState.CounterState }
    & typeof WeatherForecastsState.actionCreators      // ... plus action creators we've requested
    & RouteComponentProps<{ startDateIndex: string }>; // ... plus incoming routing parameters   
```

... and then the `connect` call to something like:

```
export default connect(
    (state: ApplicationState) => {state.weatherForecasts, state.counter }, // Selects which state properties are merged into the component's props
    WeatherForecastsState.actionCreators                 // Selects which action creators are merged into the component's props
)(FetchData) as typeof FetchData;
```

You will also need to import the relevant symbols from `../store/Counter` and fix all the references to properties on `props` (e.g., change `this.props.forecasts` to `this.props.weather.forecasts`, etc.), since you now have new subproperties.

In general this is a TypeScript usage question, so for more details, could you check TypeScript docs? Thanks!
