### ISSUE TITLE
NTLM Auth. returns 401 Unauthorized response

### ISSUE THREAD

**Issue by jmzagorski** [aspnet/JavaScriptServices#994]
I am using this **version 1.1.1** with NTLM authorization in my startup below so I can utilize `dotnet run` in a development environment. However, all my client requests to the server result in a 401 when I have the `[Authorize]` attribute on a controller. How do I tell webpack to forward my credentials? All the research I have done was directing me to add the properties to the `devServer` property in my `webpack.config`.

```
  public class Program
  {
    public static void Main(string[] args)
    {
      var host = new WebHostBuilder()
// support dotnet run with windows auth in debug mode
#if DEBUG
        .UseWebListener(opts =>
        {
          opts.ListenerSettings.Authentication.Schemes = Microsoft.Net.Http.Server.AuthenticationSchemes.NTLM;
        })
#else
          .UseKestrel()
#endif
          .UseContentRoot(Directory.GetCurrentDirectory())
          .UseIISIntegration()
          .UseStartup<Startup>()
          .Build();

      host.Run();
    }
  }
}
```

**Comment by SteveSandersonMS** [comment]
Webpack is not involved in this sort of thing at runtime.

You didn't mention which template you're using, but if it's the Angular or React-Redux one, then it's likely that your issue is that server-side prerendering does not (by design) pass through cookies or other arbitrary HTTP headers when making `fetch` calls. Does the problem go away if you remove the `asp-prerender-module` attribute from your `/Views/Home/Index.cshtml` file (to disable server-side prerendering)? If so, I'd recommend keeping server-side prerendering disabled unless you feel comfortably able to plumb through whatever's needed to authenticate the user to your backend via server-side prerendering.

**Comment by jmzagorski** [comment]
I think this issue was an oversight on my part. I was using the Aurelia template in addition to https://github.com/EisenbergEffect/aspnetcore-aurelia-build-2017/ and tried to transplant it in an existing .NET core project that was working. I must have mis-configured something with intranet security because it was sending a first request without an `Identity.Name` and then a second request with those credentials (i reconfigured and it working now). I appreciate the response though, it made me move my debugging out of webpack, as I was originally doing with the webpack-dev-server, and into my .NET code.
